import {QuestionCandidate,type ReviewCandidate} from './QuestionCandidate'
import {CreationChoices} from './CreationChoices'
import {z} from 'zod'
import {generationInputSchema} from '@/shared/generation'
import {useEffect,useId,useMemo,useRef,useState} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {useTranslation} from 'react-i18next'
import {X,FileText,Upload,ArrowLeft,Sparkles} from 'lucide-react'
import {api,ApiError,teaching,type ActivityRecord,type QuestionRecord,type Material,type QuestionProvenance} from '@/lib/api'
import {Button,LoadingIndicator,Select} from '@/design'
import {type GenerationDraft} from './session-drafts'
import styles from './GenerationPanel.module.css'
import {authoringDirection} from '../../lib/textDirection'

type Candidate=ReviewCandidate
type Job={id:number;task:string;state:string;questionId:number|null;origin:string;materialTitle?:string|null;sourceKind?:string|null;materialRevisionId?:number|null;settledMillicents:number;errorCode:string|null;result:{candidates:Candidate[];appliedIndexes:number[];nextRevision:number}|null}
type Quote={quoteId:string;quoteExpiresAt:string;estimateMillicents:number;maxAuthorizedMillicents:number;usableMillicents:number;affordable:boolean;generationAvailable:boolean;pricingAvailable:boolean}
type Recovery={mode?:'generate'|'extract';tone?:'clear'|'conversational'|'formal';sourceChosen?:boolean;origin:'file'|'text'|'topic';objective:string;text:string;count:number;language:'ar'|'en';difficulty:'easy'|'medium'|'hard';kinds:string[];revisionId:number|null;segments:number[];jobId:number|null;requestKey:string;submitted?:{input:string;quote:Quote};sourceRunId?:number|null;target?:QuestionRecord|null;edits?:Record<number,Candidate>;selected?:number[]}
export function parsePageRange(text:string):number[]{const pages=new Set<number>();for(const part of text.replaceAll('،',',').split(/[,\s]+/)){const m=/^(\d+)(?:[-–](\d+))?$/.exec(part);if(!m)continue;const from=Number(m[1]),to=Number(m[2]??m[1]);if(!from||to<from||to-from>500)continue;for(let n=from;n<=to;n++)pages.add(n)}return [...pages]}
const recoverySchema=z.object({mode:z.enum(['generate','extract']).optional(),tone:z.enum(['clear','conversational','formal']).optional(),sourceChosen:z.boolean().optional(),origin:z.enum(['file','text','topic']),objective:z.string(),text:z.string(),count:z.number().int().min(1).max(10),language:z.enum(['ar','en']),difficulty:z.enum(['easy','medium','hard']),kinds:z.array(z.enum(['mcq','tf'])).min(1).max(2),revisionId:z.number().int().positive().nullable(),segments:z.array(z.number().int().positive()),jobId:z.number().int().positive().nullable(),requestKey:z.string().min(10),submitted:z.object({input:z.string(),quote:z.object({quoteId:z.string(),quoteExpiresAt:z.string(),estimateMillicents:z.number(),maxAuthorizedMillicents:z.number(),usableMillicents:z.number(),affordable:z.boolean(),generationAvailable:z.boolean(),pricingAvailable:z.boolean()})}).optional(),target:z.object({id:z.number().int().positive(),revision:z.number().int().positive(),prompt:z.string(),kind:z.enum(['mcq','tf','order','match','hotspot']),ordinal:z.number().optional(),mediaKey:z.string().nullable().optional(),timeLimitS:z.number().optional(),payload:z.unknown().optional()}).nullable().optional(),sourceRunId:z.number().int().positive().nullable().optional(),selected:z.array(z.number().int().nonnegative()).optional(),edits:z.record(z.string(),z.object({mediaKey:z.string().max(500).nullable().optional(),prompt:z.string(),kind:z.string(),payloadJson:z.string(),explanation:z.string().optional(),sourceSegments:z.array(z.number()).optional(),concept:z.string().optional(),reasons:z.array(z.unknown()).optional()})).optional()})
const intentSchema=generationInputSchema.omit({maxAuthorizedMillicents:true,idempotencyKey:true,quoteId:true})
function restore(key:string):Partial<Recovery>|null{try{const r=recoverySchema.safeParse(JSON.parse(sessionStorage.getItem(key)??'null'));if(!r.success)return null;if(r.data.submitted)intentSchema.parse(JSON.parse(r.data.submitted.input));return r.data as Partial<Recovery>}catch{return null}}

export function GenerationPanel({startWithChoices=false,activity,question,onClose,onApplied,initialDraft=null,replacement=false,provenance=null}:{startWithChoices?:boolean;activity:ActivityRecord;question:QuestionRecord|null;onClose:()=>void;onApplied:()=>Promise<void>;initialDraft?:GenerationDraft|null;replacement?:boolean;provenance?:QuestionProvenance|null}){
 const {t:translate,i18n}=useTranslation(),ar=i18n.language.startsWith('ar')
 const t=(key:string,values:Record<string,unknown>={})=>String(translate(`questionCreation.${key}` as never,values as never))
 const number=(value:number)=>new Intl.NumberFormat(ar?'ar':'en').format(value)
 const usd=(value:number)=>new Intl.NumberFormat(ar?'ar':'en',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:5}).format(value/100000)
 const key=`asasera:question-creation:v2:${activity.authorId}:${activity.id}:${replacement?question?.id:'batch'}`
 const [saved]=useState(()=>initialDraft?null:restore(key)),initial=initialDraft??{}
 const [choosing,setChoosing]=useState(()=>!replacement&&!saved?.jobId&&!saved?.submitted&&(startWithChoices||(!initialDraft&&!provenance&&!saved?.sourceChosen&&!saved?.objective&&!saved?.revisionId)))
 const sourceRunId=saved?.sourceRunId??initial.sourceRunId??null
 const resumeTarget=!!(saved?.jobId||saved?.submitted)
 const [target,setTarget]=useState(()=>replacement?(resumeTarget?saved?.target??question:question):null)
 const [origin,setOrigin]=useState<'file'|'text'|'topic'>((replacement&&!resumeTarget?undefined:saved?.origin)??(initial.origin==='file'||provenance?.origin==='file'||initial.materialRevisionId?'file':'topic'))
 const [objective,setObjective]=useState(replacement&&!resumeTarget?question?.prompt??'':saved?.objective??initial.objective??(replacement?question?.prompt??'':''))
 const [text,setText]=useState(saved?.text??''),[count,setCount]=useState(saved?.count??initial.count??5)
 const [language,setLanguage]=useState<'ar'|'en'>(saved?.language??initial.language??(ar?'ar':'en'))
 const explicitLanguage=useRef(!!saved?.language||!!initial.language)
 const [mode,setMode]=useState<'generate'|'extract'>(saved?.mode??'generate'),[tone,setTone]=useState<'clear'|'conversational'|'formal'>(saved?.tone??'clear')
 const [difficulty,setDifficulty]=useState<Recovery['difficulty']>(saved?.difficulty??initial.difficulty??'medium')
 const [kinds,setKinds]=useState<string[]>(()=>{const supported=(saved?.kinds??initial.kinds??['mcq','tf']).filter(k=>k==='mcq'||k==='tf');return supported.length?supported:['mcq','tf']})
 const [revisionId,setRevisionId]=useState<number|null>((replacement&&!resumeTarget?undefined:saved?.revisionId)??initial.materialRevisionId??provenance?.materialRevisionId??null)
 const [segments,setSegments]=useState<number[]>((replacement&&!resumeTarget?undefined:saved?.segments)??initial.segments??provenance?.segmentIndexes??[])
 const [jobId,setJobId]=useState<number|null>(saved?.jobId??null),[requestKey,setRequestKey]=useState(saved?.requestKey??crypto.randomUUID())
 const [submitted,setSubmitted]=useState<Recovery['submitted']>(saved?.submitted)
 const [uploadingImages,setUploadingImages]=useState<number[]>([])
 const [edits,setEdits]=useState<Record<number,Candidate>>(saved?.edits??{})
 const [selected,setSelected]=useState<number[]>(saved?.selected??[]),[pending,setPending]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [quoted,setQuoted]=useState<{input:string;quote:Quote}|null>(saved?.submitted??null),[quoting,setQuoting]=useState(false),[quoteAttempt,setQuoteAttempt]=useState(0)
 const [showSaved,setShowSaved]=useState(false),[materialsPage,setMaterialsPage]=useState(1),[pageRange,setPageRange]=useState('')
 const [uploaded,setUploaded]=useState<Material|null>(null),[source,setSource]=useState<{text:string;index:number}|null>(null)
 const recoveryCleared=useRef(false)
 const dialog=useRef<HTMLDialogElement>(null),close=useRef<HTMLButtonElement>(null),inFlight=useRef(false),titleId=useId(),inputId=useId(),queryClient=useQueryClient()
 useEffect(()=>{const d=dialog.current,prior=document.activeElement,overflow=document.body.style.overflow;d?.showModal();document.body.style.overflow='hidden';close.current?.focus();return()=>{d?.close();document.body.style.overflow=overflow;if(prior instanceof HTMLElement&&prior.isConnected)prior.focus()}},[])
 const recoverySnapshot=(patch:Partial<Recovery>={}):Recovery=>({mode,tone,sourceChosen:!choosing,origin,objective,text,count,language,difficulty,kinds,revisionId,segments,jobId,requestKey,submitted,target,edits,selected,sourceRunId,...patch})
 const persistRecovery=(value:Recovery)=>{try{sessionStorage.setItem(key,JSON.stringify(value))}catch{/* Retain in memory when browser storage is blocked. */}}
 useEffect(()=>{if(!recoveryCleared.current)persistRecovery(recoverySnapshot())},[key,mode,tone,choosing,origin,objective,text,count,language,difficulty,kinds,revisionId,segments,jobId,requestKey,submitted,target,edits,selected,sourceRunId])
 const limits=useQuery({queryKey:['material-limits'],queryFn:()=>teaching.limits(),staleTime:300000})
 const materials=useQuery({queryKey:['generation-materials',materialsPage],queryFn:()=>teaching.materials({page:materialsPage,limit:50}),enabled:showSaved})
 const revision=useQuery({queryKey:['generation-revision',revisionId],queryFn:()=>teaching.revision(revisionId!),enabled:!!revisionId&&origin!=='topic',refetchInterval:q=>['pending','running'].includes(q.state.data?.revision.state??'')?1500:false})
 const pages=useQuery({queryKey:['generation-segments',revisionId],queryFn:()=>teaching.segments(revisionId!),enabled:!!revisionId&&origin!=='topic'&&revision.data?.revision.state==='ready'})
 const jobs=useQuery({queryKey:['activity-generation',activity.id],queryFn:()=>api.get<{jobs:Job[]}>(`/api/v1/activity-generation/activities/${activity.id}`)})
 const active=useQuery({queryKey:['activity-generation-job',jobId],queryFn:()=>api.get<{job:Job}>(`/api/v1/activity-generation/jobs/${jobId}`),enabled:!!jobId,refetchInterval:q=>['queued','running'].includes(q.state.data?.job.state??'queued')?1500:false})
 const job=active.data?.job,result=job?.result,preparing=!!job&&['queued','running'].includes(job.state)
 const fileOrigin=origin!=='topic',caps=limits.data
 const readable=useMemo(()=>(pages.data?.segments??[]).filter(s=>s.charCount>0&&s.text.trim()&&s.warning!=='unreadable'),[pages.data])
 const selectedChars=readable.filter(s=>segments.includes(s.segmentIndex)).reduce((n,s)=>n+s.charCount,0)
 const over=!!caps&&(segments.length>caps.maxSegmentsPerGeneration||selectedChars>caps.maxSelectionChars)
 const autoScope=useRef<number|null>(null)
 useEffect(()=>{if(submitted||!revisionId||!pages.data||!caps||autoScope.current===revisionId)return;autoScope.current=revisionId;if(segments.length)return;const chars=readable.reduce((n,s)=>n+s.charCount,0);if(readable.length<=caps.maxSegmentsPerGeneration&&chars<=caps.maxSelectionChars)setSegments(readable.map(s=>s.segmentIndex))},[revisionId,pages.data,caps,readable,segments.length])
 useEffect(()=>{const value=(revision.data?.revision as {contentLanguage?:string}|undefined)?.contentLanguage;if(!submitted&&!explicitLanguage.current&&(value==='ar'||value==='en'))setLanguage(value)},[revision.data])
 useEffect(()=>{if(replacement&&!submitted&&!jobId&&question&&target?.revision!==question.revision){setTarget(question);setObjective(question.prompt)}},[replacement,submitted,jobId,question,target?.revision])
 const ready=!choosing&&!jobId&&!pending&&(!!submitted||(!!kinds.length&&!over&&(fileOrigin?!!revisionId&&revision.data?.revision.state==='ready'&&segments.length>0:objective.trim().length>=3)))
 const proposedRequest={mode:fileOrigin?mode:'generate',tone,activityId:activity.id,task:'questions',origin:fileOrigin?'file':'topic',objective:objective.trim(),language,count:replacement?1:count,kinds,difficulty,questionId:target?.id??null,expectedRevision:target?.revision??activity.revision,materialRevisionId:fileOrigin?revisionId:null,segments:fileOrigin?segments:[],sourceRunId}
 const request=submitted?intentSchema.parse(JSON.parse(submitted.input)):proposedRequest
 const requestText=submitted?.input??JSON.stringify(request)
 const lastRequest=useRef(requestText)
 useEffect(()=>{if(!submitted&&lastRequest.current!==requestText){lastRequest.current=requestText;setSubmitted(undefined);setRequestKey(crypto.randomUUID())}},[requestText])
 const describe=(e:unknown)=>{const code=e instanceof ApiError?e.code:'';if(code==='question_invalid'||code==='validation_error')return t('questionInvalid');if(['insufficient_credit','exposure_cap_reached'].includes(code))return t('credit');if(['quote_changed','quote_expired','quote_policy_changed','stale_quote'].includes(code))return t('changed');if(['revision_conflict','stale_revision','question_changed'].includes(code))return t('stale');return t('failed')}
 useEffect(()=>{if(submitted?.input===requestText){setQuoted(submitted);return}setQuoted(null);setError('');if(!ready){setQuoting(false);return}let cancelled=false;setQuoting(true);const timer=setTimeout(()=>{void api.post<Quote>('/api/v1/activity-generation/quote',request).then(quote=>{if(!cancelled)setQuoted({input:requestText,quote})}).catch(e=>{if(!cancelled)setError(describe(e))}).finally(()=>{if(!cancelled)setQuoting(false)})},450);return()=>{cancelled=true;clearTimeout(timer)}},[requestText,ready,quoteAttempt]) // eslint-disable-line react-hooks/exhaustive-deps
 const run=async(action:string,work:()=>Promise<void>)=>{if(inFlight.current)return;inFlight.current=true;setPending(action);setError('');try{await work()}catch(e){if(e instanceof ApiError&&(e.code.startsWith('quote_')||(action==='generate'&&e.status>=400&&e.status<500))){setSubmitted(undefined);setQuoted(null);setRequestKey(crypto.randomUUID());setQuoteAttempt(n=>n+1)}setError(describe(e));if(e instanceof ApiError&&e.code==='revision_conflict')await onApplied()}finally{inFlight.current=false;setPending('')}}
 const setMaterial=(m:Material)=>{setUploaded(m);setRevisionId(m.revisionId);setSegments([]);setPageRange('');autoScope.current=null;setShowSaved(false)}
 const generate=async()=>{const q=quoted?.quote;if(!q||quoted?.input!==requestText)return;if(!submitted&&new Date(q.quoteExpiresAt).getTime()<=Date.now()){setQuoted(null);setQuoteAttempt(n=>n+1);setError(t('changed'));return}const approved={input:requestText,quote:q};setSubmitted(approved);persistRecovery(recoverySnapshot({jobId:null,submitted:approved}));const r=await api.post<{job:Job}>('/api/v1/activity-generation/jobs',{...request,quoteId:q.quoteId,maxAuthorizedMillicents:q.maxAuthorizedMillicents,idempotencyKey:requestKey});queryClient.setQueryData(['activity-generation-job',r.job.id],r);setJobId(r.job.id);setSelected([]);setEdits({});await jobs.refetch()}
 const remaining=result?.candidates.map((_,i)=>i).filter(i=>!result.appliedIndexes.includes(i))??[]
 const apply=async(indexes=selected)=>{if(!job||!result||!indexes.length||uploadingImages.length)return;const applying=replacement?[indexes[0]]:indexes;await api.post(`/api/v1/activity-generation/jobs/${job.id}/apply`,{selected:applying,expectedRevision:result.nextRevision,edits:Object.entries(edits).filter(([i])=>applying.includes(Number(i))).map(([i,{mediaKey,...c}])=>({index:Number(i),...(mediaKey!==undefined?{mediaKey}:{}),question:{...c,explanation:c.explanation??'',concept:c.concept??'',reasons:c.reasons??[],sourceSegments:c.sourceSegments??[]}}))});setEdits(old=>Object.fromEntries(Object.entries(old).filter(([i])=>!applying.includes(Number(i)))));setSelected(old=>old.filter(i=>!applying.includes(i)));setNotice(t('stored'));await active.refetch();await onApplied();if(applying.length>=remaining.length){recoveryCleared.current=true;try{sessionStorage.removeItem(key)}catch{/* Already saved by the server. */}}}
 const refreshTarget=()=>{if(!question)return;recoveryCleared.current=false;setTarget(question);setObjective(question.prompt);setOrigin(provenance?.origin==='file'?'file':'topic');setRevisionId(provenance?.materialRevisionId??null);setSegments(provenance?.segmentIndexes??[]);setJobId(null);setSubmitted(undefined);setQuoted(null);setSelected([]);setEdits({});setRequestKey(crypto.randomUUID());setError('');setNotice('')}
 const staleTarget=replacement&&!!question&&!!target&&question.revision!==target.revision
 const chooseJob=(j:Job)=>{setChoosing(false);if(pending||(submitted&&!jobId))return;setJobId(j.id);setSelected([]);setEdits({});setSource(null)}
 const chooseSource=(value:'file'|'text'|'topic')=>{if(pending||submitted&&!jobId)return;if(value!==origin){setMode('generate');setRevisionId(null);setSegments([]);setUploaded(null);setPageRange('');autoScope.current=null}setOrigin(value);setChoosing(false);setSubmitted(undefined);setRequestKey(crypto.randomUUID());requestAnimationFrame(()=>close.current?.focus())}
 const uploadFile=(f:File)=>{if(!caps||pending||submitted||inFlight.current)return;void run('upload',async()=>{const kind=f.name.split('.').at(-1)?.toLowerCase()??'';if(f.size>caps.maxBytes||!caps.acceptedKinds.includes(kind as 'pdf'))throw new Error('unsupported');const r=await teaching.uploadFile(f.name,f.name,caps.acceptedContentTypes[kind]??f.type,f);setMaterial(r.material)})}
 const title=revision.data?.revision.title??uploaded?.title??t('source')
 const locator=job?.sourceKind?(job.sourceKind==='pptx'?'slide':job.sourceKind==='pdf'?'page':'section'):revision.data?.revision.locatorKind??'section'
 const selectedNames=readable.filter(s=>segments.includes(s.segmentIndex)).map(s=>s.printedLabel??number(s.pageIndex??s.segmentIndex)).join(', ')
 const currentQuote=quoted?.input===requestText?quoted.quote:null
 return <dialog ref={dialog} aria-labelledby={titleId} dir={ar?'rtl':'ltr'} className={`asas ${styles.dialog} ${!replacement?(choosing?styles.chooser:styles.workspace):''} ${!choosing&&!replacement&&!jobId?styles.creationWorkspace:''} ${origin==='file'?styles.fileWorkspace:styles.topicWorkspace}`} onCancel={onClose} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();return}if(event.key!=='Tab')return;const items=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled),summary,[tabindex="0"]')??[]).filter(el=>el.tabIndex>=0&&el.getClientRects().length>0&&!el.closest('[hidden],[inert]'));const first=items[0],last=items.at(-1);if(!first)return;if(event.shiftKey&&(document.activeElement===first||!dialog.current?.contains(document.activeElement))){event.preventDefault();last?.focus()}else if(!event.shiftKey&&(document.activeElement===last||!dialog.current?.contains(document.activeElement))){event.preventDefault();first.focus()}}}>
  <header className={styles.header}><div className={styles.heading}>{!replacement&&!choosing&&!jobId&&!submitted&&<button type="button" aria-label={t('backChoices')} onClick={()=>setChoosing(true)}><ArrowLeft className={styles.backIcon}/></button>}<h2 id={titleId}>{choosing?t('chooseTitle'):replacement?t('suggest'):jobId?t('review'):origin==='file'&&revisionId?(ar?'اختر الصفحات وإعدادات الأسئلة':'Select pages and question options'):t(origin)}</h2></div><button ref={close} type="button" aria-label={t('close')} onClick={onClose}><X/></button></header>
  {choosing?<div className={styles.choices}><p className={styles.choiceLead}>{t('chooseLead')}</p><CreationChoices onChoose={method=>method==='manual'?onClose():chooseSource(method)}/>{!!jobs.data?.jobs.filter(j=>j.task==='questions'&&!j.questionId).length&&<details className={styles.recent}><summary>{t('recent')}</summary>{jobs.data.jobs.filter(j=>j.task==='questions'&&!j.questionId).slice(0,10).map((j,i)=><Button key={j.id} onClick={()=>chooseJob(j)}>{t('resume')} {number(i+1)}</Button>)}</details>}</div>:<>
  <div className={styles.body}>
   {replacement&&target&&<section className={styles.original}><strong>{t('original')}</strong><p dir="auto">{target.prompt}</p>{fileOrigin&&<small>{title} · {selectedNames||t('scope',{number:number(segments.length)})}</small>}</section>}
   {!jobId&&<fieldset className={`${styles.form} ${!replacement?styles.creationForm:''}`} disabled={!!pending||!!submitted}>
    {!replacement&&origin!=='file'&&<div className={styles.inputModes}><Button variant="quiet" disabled={!!pending||!!submitted} onClick={()=>chooseSource('topic')}>{t('topic')}</Button><Button variant="quiet" disabled={!!pending||!!submitted} onClick={()=>chooseSource('text')}>{t('text')}</Button></div>}
    {!replacement&&origin==='topic'&&<label htmlFor={inputId}>{t('topicLabel')}<textarea id={inputId} rows={3} value={objective} onChange={e=>{setObjective(e.target.value);setSubmitted(undefined)}} maxLength={1000} placeholder={t('example')} dir={authoringDirection(objective,ar)}/></label>}
    {origin==='topic'&&<><p className={styles.muted}>{t('topicNote')}</p>{!replacement&&<div className={styles.topicSuggestions} aria-label={t('topicIdeas')}>{(ar?['دورة الماء','المجموعة الشمسية','حماية البيانات']:['The water cycle','The solar system','Data protection']).map(idea=><Button key={idea} variant="secondary" disabled={!!pending||!!submitted} onClick={()=>setObjective(idea)}>{idea}</Button>)}</div>}</>}
    {!replacement&&origin==='text'&&<><label htmlFor={inputId}>{t('textLabel')}<textarea id={inputId} rows={7} value={text} maxLength={caps?.maxPastedChars??120000} dir={authoringDirection(text,ar)} onChange={e=>{setText(e.target.value);setRevisionId(null);setSegments([]);setSubmitted(undefined)}}/></label>{!revisionId&&<Button loading={pending==='text'} disabled={!!pending||!text.trim()} onClick={()=>void run('text',async()=>{const r=await teaching.createTextMaterial({title:activity.title||t('textLabel'),text});setMaterial(r.material)})}>{t('saveText')}</Button>}</>}
    {!replacement&&origin==='file'&&<>
     {!revisionId&&<label className={styles.upload} onDragOver={e=>{e.preventDefault()}} onDrop={e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)uploadFile(file)}}><Upload size={40} aria-hidden="true"/><strong>{t('dropFile')}</strong><span>{t('fileChoose')}</span><input type="file" accept={caps?.acceptedKinds.map(k=>`.${k}`).join(',')??'.pdf,.docx,.pptx'} disabled={!!pending||!caps} onChange={e=>{const f=e.target.files?.[0];if(f)uploadFile(f)}}/>{caps&&<small>{t('uploadHint',{types:caps.acceptedKinds.map(k=>k.toUpperCase()).join(', '),size:Math.round(caps.maxBytes/1048576)})}</small>}</label>}
     <Button variant="quiet" disabled={!!pending} onClick={()=>setShowSaved(v=>!v)}>{t('saved')}</Button>
     {showSaved&&<div className={styles.saved}>{materials.isPending?<LoadingIndicator label={t('loadPages')}/>:<><label>{t('choose')}<Select disabled={!!pending||!!submitted} value={revisionId??''} onValueChange={v=>{const m=materials.data?.materials.find(m=>m.revisionId===Number(v));if(m)setMaterial(m)}}><option value="">{t('choose')}</option>{materials.data?.materials.map(m=><option key={m.id} value={m.revisionId??''} disabled={!m.revisionId}>{m.title}</option>)}</Select></label>{materials.data?.total===0&&<p>{t('none')}</p>}{(materials.data?.total??0)>50&&<div className={styles.row}><Button disabled={materialsPage===1} onClick={()=>setMaterialsPage(n=>n-1)}>{t('previous')}</Button><Button disabled={materialsPage*50>=(materials.data?.total??0)} onClick={()=>setMaterialsPage(n=>n+1)}>{t('next')}</Button></div>}</>}</div>}
    </>}
    {!replacement&&fileOrigin&&revisionId&&<fieldset className={styles.extractionMode}><legend>{ar?'كيف تريد إنشاء الأسئلة؟':'How should we create questions?'}</legend><label className={styles.check}><input type="radio" name="creation-mode" checked={mode==='generate'} onChange={()=>setMode('generate')}/>{ar?'توليد أسئلة جديدة':'Generate new questions'}</label><label className={styles.check}><input type="radio" name="creation-mode" checked={mode==='extract'} onChange={()=>setMode('extract')}/>{ar?'استخراج الأسئلة الموجودة':'Extract existing questions'}</label><p>{mode==='extract'?(ar?'نسخ الأسئلة الموجودة في الصفحات المحددة دون اختراع أسئلة أو إجابات جديدة. تُحفظ لغة النص الأصلية.':'Copy questions already in the selected pages without inventing questions or answer options. The original language is preserved.'):(ar?'إنشاء أسئلة جديدة بناءً على الصفحات المحددة.':'Create new questions based on the selected pages.')}</p></fieldset>}
    {!replacement&&(origin!=='file'||revisionId)&&<details className={styles.settings} open><summary><span>{t(language==='ar'?'arabic':'english')} · {t(difficulty)} · {t(kinds.length===2?'mixed':kinds[0]??'mixed')}</span><strong>{t('settings')}</strong></summary><div className={styles.settingsFields}><label>{t('difficulty')}<Select disabled={!!pending||!!submitted||mode==='extract'} value={difficulty} onValueChange={v=>{setDifficulty(v as Recovery['difficulty']);setSubmitted(undefined)}}>{['easy','medium','hard'].map(v=><option key={v} value={v}>{t(v)}</option>)}</Select></label><label>{t('language')}<Select disabled={!!pending||!!submitted||mode==='extract'} value={language} onValueChange={v=>{explicitLanguage.current=true;setLanguage(v as 'ar'|'en');setSubmitted(undefined)}}><option value="ar">{t('arabic')}</option><option value="en">{t('english')}</option></Select></label><label>{t('format')}<Select disabled={!!pending||!!submitted} value={kinds.length===2?'mixed':kinds[0]} onValueChange={v=>{setKinds(v==='mixed'?['mcq','tf']:[v]);setSubmitted(undefined)}}>{['mixed','mcq','tf'].map(v=><option value={v} key={v}>{t(v)}</option>)}</Select></label><label>{ar?'أسلوب الصياغة':'Tone'}<Select disabled={!!pending||!!submitted||mode==='extract'} value={tone} onValueChange={v=>setTone(v as typeof tone)}><option value="clear">{ar?'واضح ومباشر':'Clear and direct'}</option><option value="conversational">{ar?'حواري':'Conversational'}</option><option value="formal">{ar?'رسمي':'Formal'}</option></Select></label></div></details>}
    {replacement&&fileOrigin&&!revisionId&&<p role="alert">{t('noText')}</p>}
    {fileOrigin&&revisionId&&<section className={styles.fileSummary}><strong><FileText size={18} aria-hidden="true"/> {title}</strong>{revision.isPending||['pending','running'].includes(revision.data?.revision.state??'')?<LoadingIndicator label={t('processing')}/>:revision.isError?<p role="alert">{t('failed')}</p>:revision.data?.revision.state==='failed'?<p role="alert">{t('noText')}</p>:<>
     {pages.isPending?<LoadingIndicator label={t('loadPages')}/>:<p>{selectedNames?t('scope',{number:number(segments.length)})+' · '+selectedNames:t('tooLarge')}</p>}
     {(!!revision.data?.revision.unreadableSegments||(pages.data?.segments??[]).some(s=>s.warning==='unreadable'||!s.text.trim()))&&<p className={styles.muted}>{t('unreadable')} {(pages.data?.segments??[]).filter(s=>s.warning==='unreadable'||!s.text.trim()).map(s=>number(s.pageIndex??s.segmentIndex)).join(', ')}</p>}
     {!replacement&&<details open><summary>{t('pages')}</summary><label>{t('range')}<input dir="ltr" value={pageRange} placeholder={t('rangeExample')} onChange={e=>{setPageRange(e.target.value);const wanted=parsePageRange(e.target.value);setSegments(readable.filter(s=>wanted.includes(s.pageIndex??s.segmentIndex)).map(s=>s.segmentIndex));setSubmitted(undefined)}}/></label><Button variant="quiet" onClick={()=>setSegments(segments.length===readable.length?[]:readable.map(s=>s.segmentIndex))}>{segments.length===readable.length?t('deselect'):t('selectAll')}</Button><div className={styles.pagePreviews}>{readable.map(s=><label key={s.segmentIndex} className={styles.pagePreview}><input type="checkbox" checked={segments.includes(s.segmentIndex)} onChange={()=>{setSegments(old=>old.includes(s.segmentIndex)?old.filter(n=>n!==s.segmentIndex):[...old,s.segmentIndex]);setSubmitted(undefined)}}/><strong>{t(locator,{number:number(s.pageIndex??s.segmentIndex)})}</strong><span dir="auto">{s.text}</span></label>)}</div></details>}
    </>}{!replacement&&<Button variant="quiet" onClick={()=>{setRevisionId(null);setSegments([]);setUploaded(null)}}>{t('change')}</Button>}</section>}
    {over&&<p className={styles.error} role="alert">{t('tooLarge')}</p>}
    {!replacement&&(origin!=='file'||revisionId)&&<div className={styles.count}><label>{t('count')}<Select disabled={!!pending||!!submitted} style={{width:100,flex:'0 0 100px'}} value={count} onValueChange={v=>{setCount(Number(v));setSubmitted(undefined)}}>{[...new Set([5,10,count])].filter(n=>n<=(caps?.maxQuestionsPerGeneration??10)).sort((a,b)=>a-b).map(n=><option key={n} value={n}>{number(n)}</option>)}</Select></label></div>}
   </fieldset>}
   {submitted&&!jobId&&!pending&&<p role="status">{t('pendingRecovery')}</p>}
   {error&&<p role="alert" className={styles.error}>{error} <Button variant="quiet" onClick={()=>setQuoteAttempt(n=>n+1)}>{t('retry')}</Button></p>}{notice&&<p role="status">{notice}</p>}
   {jobId&&active.isPending&&<LoadingIndicator label={t('loadPages')}/>}
   {active.isError&&<p role="alert">{t('failed')} <Button onClick={()=>void active.refetch()}>{t('retry')}</Button></p>}
   {preparing&&<div className={styles.progress}><LoadingIndicator size="large" label={t('preparing')}/><p>{t('recoverNote')}</p><Button disabled={!!pending} loading={pending==='cancel'} onClick={()=>void run('cancel',async()=>{await api.post(`/api/v1/activity-generation/jobs/${jobId}/cancel`);await active.refetch()})}>{t('cancel')}</Button></div>}
   {job?.state==='needs_review'&&<p role="status">{t('held')}</p>}
   {job&&['failed','cancelled'].includes(job.state)&&<p role="status">{job.errorCode==='no_valid_candidates'?(ar?'لم نعثر على أسئلة صالحة في الصفحات المحددة. اختر صفحات أخرى أو استخدم توليد أسئلة جديدة.':'No usable questions were found in the selected source. Choose other pages or generate new questions.'):t(job.state==='failed'?'failed':'cancelled')}</p>}
   {staleTarget&&job?.state==='succeeded'&&<p role="status">{t('stale')} <Button onClick={refreshTarget}>{t('freshSuggestion')}</Button></p>}
   {result&&<section><p>{t('reminder')}</p>{!result.candidates.length&&<p>{t('reviewEmpty')}</p>}{!replacement&&remaining.length>0&&<Button variant="quiet" onClick={()=>setSelected(selected.length===remaining.length?[]:remaining)}>{t(selected.length===remaining.length?'deselect':'selectAll')}</Button>}
    <div className={styles.reviewList}>{result.candidates.map((original,index)=>{const c=edits[index]??original,added=result.appliedIndexes.includes(index);return <QuestionCandidate key={index} candidate={c} index={index} added={added} selected={selected.includes(index)} busy={!!pending||staleTarget||uploadingImages.length>0} onUploadBusy={busy=>setUploadingImages(old=>busy?[...new Set([...old,index])]:old.filter(i=>i!==index))} replacement={replacement} ar={ar} onSelect={()=>setSelected(old=>replacement?[index]:old.includes(index)?old.filter(i=>i!==index):[...old,index])} onChange={patch=>setEdits(old=>({...old,[index]:{...(old[index]??original),...patch}}))} onAdd={()=>void run('apply',()=>apply([index]))}>{c.sourceSegments?.map(segment=><Button variant="quiet" key={segment} loading={pending===`source${segment}`} onClick={()=>void run(`source${segment}`,async()=>setSource(await api.get(`/api/v1/activity-generation/jobs/${job.id}/source/${segment}`)))}><FileText size={16}/>{job.materialTitle??title} · {t(job.sourceKind==='text'?'textSource':locator,{number:number(segment)})}</Button>)}</QuestionCandidate>})}</div>
   </section>}
   {source&&<section className={styles.source}><p dir="auto">{source.text}</p><Button onClick={()=>setSource(null)}>{t('sourceClose')}</Button></section>}
   {!replacement&&!!jobs.data?.jobs.filter(j=>j.task==='questions'&&!j.questionId).length&&<details className={styles.recent}><summary>{t('recent')}</summary>{jobs.data.jobs.filter(j=>j.task==='questions'&&!j.questionId).slice(0,10).map((j,i)=><Button key={j.id} variant="quiet" disabled={!!pending||!!submitted&&!jobId} onClick={()=>chooseJob(j)}>{t('resume')} {number(i+1)}</Button>)}</details>}
  </div>
  <footer className={styles.footer}>
   {!jobId?<><div className={styles.cost} aria-live="polite">{quoting?t('estimating'):currentQuote?<>{t('estimated')} <bdi>{usd(currentQuote.estimateMillicents)}</bdi> · {t('maximum')} <bdi>{usd(currentQuote.maxAuthorizedMillicents)}</bdi> · {t('available')} <bdi>{usd(currentQuote.usableMillicents)}</bdi>{currentQuote.generationAvailable&&currentQuote.pricingAvailable&&!currentQuote.affordable&&<p>{t('credit')}</p>}{(!currentQuote.generationAvailable||!currentQuote.pricingAvailable)&&<p>{t('unavailable')}</p>}</>:t('readyHint')}</div><Button variant="primary" icon={<Sparkles size={18}/>} loading={pending==='generate'||pending==='upload'||pending==='text'} disabled={!!pending||!ready||!currentQuote?.affordable||!currentQuote.generationAvailable||!currentQuote.pricingAvailable} onClick={()=>void run('generate',generate)}>{submitted&&!pending?t('resume'):replacement?t('suggest'):mode==='extract'?(ar?'استخراج الأسئلة بالذكاء الاصطناعي':'Extract questions with AI'):(ar?`توليد ${number(count)} أسئلة بالذكاء الاصطناعي`:`Generate ${number(count)} questions with AI`)}</Button></>:result&&remaining.length?<><span>{t('selected',{number:number(selected.length)})}</span>{!replacement&&<Button disabled={!!pending||uploadingImages.length>0} onClick={()=>void run('apply',()=>apply(remaining))}>{ar?`إضافة جميع الأسئلة المتبقية (${number(remaining.length)})`:`Add all remaining (${number(remaining.length)})`}</Button>}{replacement&&<Button onClick={onClose}>{t('keep')}</Button>}<Button variant="primary" loading={pending==='apply'} disabled={!!pending||uploadingImages.length>0||!selected.length||staleTarget} onClick={()=>void run('apply',()=>apply())}>{replacement?t('replace'):t('add',{count:selected.length,number:number(selected.length)})}</Button></>:replacement&&job&&['failed','cancelled'].includes(job.state)?<><Button onClick={onClose}>{t('keep')}</Button><Button variant="primary" onClick={refreshTarget}>{t('retry')}</Button></>:!preparing&&<Button onClick={()=>{if(replacement){onClose();return}recoveryCleared.current=false;setChoosing(true);setJobId(null);setSubmitted(undefined);setRequestKey(crypto.randomUUID());setNotice('')}}>{replacement?t('keep'):t('new')}</Button>}
  {jobId&&!preparing&&<Button disabled={!!pending} onClick={onClose}>{ar?'تم':'Done'}</Button>}</footer></>}
 </dialog>
}
