import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {useTranslation} from 'react-i18next'
import {api,type QuestionRecord} from '@/lib/api'
import {Button, Select } from '@/design'
type Vocabulary={labels:{id:number;labelAr:string;labelEn:string|null;canonicalId:number}[];pairs:{questionId:number;elementKey:string;wrongTargetKey:string|null;reason:string;misconceptionId:number|null}[];decisions:{id:number;sourceId:number;targetId:number;reason:string;revokedAt:string|null}[];schedule:{enabled:boolean;nextRunAt:string;maxAuthorizedMillicents:number}|null}
export function LabelReview({activityId,question,onChanged,weeklyCap}:{activityId:number;question:QuestionRecord|null;onChanged:()=>Promise<void>;weeklyCap?:number|undefined}){
 const {i18n}=useTranslation(),ar=i18n.language.startsWith('ar'),t=(a:string,e:string)=>ar?a:e
 const [arabic,setArabic]=useState(''),[english,setEnglish]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const vocabulary=useQuery({queryKey:['activity-labels',activityId,question?.revision],queryFn:()=>api.get<Vocabulary>(`/api/v1/activity-generation/activities/${activityId}/labels`)})
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await onChanged();await vocabulary.refetch()}catch(e){setError(e instanceof Error?e.message:t('تعذّر الحفظ','Could not save'))}finally{setBusy(false)}}
 const label=(id:number)=>{const l=vocabulary.data?.labels.find(l=>l.id===id);return l?(ar?l.labelAr:l.labelEn||l.labelAr):String(id)}
 return <details><summary>{t('تسميات التصورات والمراجعة الأسبوعية','Misconception labels and weekly review')}</summary>
  <p>{t('التسمية وصف قابل للمراجعة، وليست تشخيصًا للطالب. ترتبط بأسبابك المكتوبة.','Labels describe patterns for review; they do not diagnose learners. Link them to your written reasons.')}</p>
  {vocabulary.isPending?<p>{t('جارٍ التحميل…','Loading…')}</p>:vocabulary.error?<p role="alert">{vocabulary.error.message}</p>:<>
   {question&&vocabulary.data?.pairs.filter(p=>p.questionId===question.id).map(p=><label key={`${p.elementKey}:${p.wrongTargetKey}`} style={{display:'grid',gap:8,marginBlock:16}}><span>{p.elementKey}{p.wrongTargetKey?` → ${p.wrongTargetKey}`:''}: {p.reason}</span><Select value={p.misconceptionId??''} disabled={busy} onValueChange={e=>void act(async()=>{await api.put(`/api/v1/activity-generation/questions/${question.id}/label`,{elementKey:p.elementKey,wrongTargetKey:p.wrongTargetKey,misconceptionId:Number(e)||null,expectedRevision:question.revision})})}><option value="">{t('دون تسمية','No label')}</option>{vocabulary.data?.labels.map(l=><option key={l.id} value={l.id}>{label(l.id)}{l.canonicalId!==l.id?` → ${label(l.canonicalId)}`:''}</option>)}</Select></label>)}
   <div style={{display:'grid',gap:12,marginBlock:16}}><label>{t('تسمية عربية جديدة','New Arabic label')}<input value={arabic} onChange={e=>setArabic(e.target.value)} maxLength={200}/></label><label>{t('التسمية الإنجليزية (اختياري)','English label (optional)')}<input value={english} onChange={e=>setEnglish(e.target.value)} maxLength={200}/></label><Button disabled={busy||!arabic.trim()} onClick={()=>void act(async()=>{await api.post(`/api/v1/activity-generation/activities/${activityId}/labels`,{labelAr:arabic,labelEn:english});setArabic('');setEnglish('')})}>{t('أضف التسمية إلى قائمتي','Add to my labels')}</Button></div>
   <p>{t('قبول اقتراح دمج ينشئ ربطًا في قائمتك مع سجل قرار. لا يغيّر إجابات سابقة أو قوائم المعلمين الآخرين.','Accepting a merge creates a mapping in your own list with an audit record. It preserves past answers and other teachers’ labels.')}</p>
   {vocabulary.data?.decisions.map(d=><div key={d.id} style={{marginBlock:12}}><strong>{label(d.sourceId)} → {label(d.targetId)}</strong><p>{d.reason}</p>{d.revokedAt?<small>{t('تم التراجع مع الاحتفاظ بسجل القرار','Reverted; the decision remains in the audit trail')}</small>:<Button disabled={busy} onClick={()=>void act(async()=>{await api.post(`/api/v1/activity-generation/decisions/${d.id}/revoke`)})}>{t('تراجع عن هذا الربط','Revert this mapping')}</Button>}</div>)}
   {vocabulary.data?.schedule?.enabled?<><p>{t('المراجعة الأسبوعية مفعّلة. الموعد التالي:','Weekly review enabled. Next run:')} {new Date(vocabulary.data.schedule.nextRunAt).toLocaleString(ar?'ar':'en')}</p><Button disabled={busy} onClick={()=>void act(async()=>{await api.put(`/api/v1/activity-generation/activities/${activityId}/schedule`,{enabled:false,maxAuthorizedMillicents:vocabulary.data!.schedule!.maxAuthorizedMillicents})})}>{t('أوقف المراجعة الأسبوعية','Stop weekly review')}</Button></>:<><p>{t('اختياري: اطلب اقتراحات أسبوعية مدفوعة ضمن حد تحدده. لا تُطبّق الاقتراحات تلقائيًا. اعرض تكلفة مهمة مراجعة التسميات أولًا.','Optional: request paid weekly suggestions within your cap. Suggestions are never applied automatically. First review the cost cap for the label-review task.')}</p><Button disabled={busy||!weeklyCap} onClick={()=>void act(async()=>{await api.put(`/api/v1/activity-generation/activities/${activityId}/schedule`,{enabled:true,maxAuthorizedMillicents:weeklyCap})})}>{t('فعّل الاقتراحات الأسبوعية','Enable weekly suggestions')}{weeklyCap?` · ${t('حتى','up to')} $${(weeklyCap/100000).toFixed(3)}`:''}</Button></>}
  </>}{error&&<p role="alert">{error}</p>}
 </details>
}
