import {useCallback} from 'react'
import {useTranslation} from 'react-i18next'
const english:Record<string,string>={
  "تغييرات غير محفوظة": "Unsaved changes",
  "جارٍ الحفظ…": "Saving…",
  "محفوظ": "Saved",
  "تعذّر الحفظ — تعديلك لم يُفقد": "Could not save. Your edits are still here.",
  "أعد المحاولة": "Retry",
  "تعذّر تحميل النشاط": "Could not load activity",
  "خطأ غير معروف": "Unknown error",
  "تعذّرت إضافة السؤال": "Could not add question",
  "تعذّر النشر.": "Could not publish.",
  "تعذّر فتح النشاط": "Activity unavailable",
  "الأسئلة": "Questions",
  "عنوان النشاط": "Activity title",
  "الخصائص": "Properties",
  "تعذّر حفظ التعديلات": "Could not save changes",
  "خروج": "Exit",
  "شغّل الحصة": "Play",
  "إعادة النشر": "Publish changes",
  "انشر": "Publish",
  "أسئلة النشاط": "Activity questions",
  "أغلق قائمة الأسئلة": "Close question list",
  "تعذّر حفظ السؤال": "Could not save question",
  "يحتاج إكمالًا": "Needs attention",
  "سؤال بلا نص": "Untitled question",
  "أضف سؤالًا": "Add question",
  "توليد بالذكاء الاصطناعي": "Generate with AI",
  "لا أسئلة بعد": "No questions yet",
  "أضف سؤالًا لتبدأ. النوع والمؤقّت مضبوطان مسبقًا.": "Add your first question. Type and timer are already set.",
  "اكتب السؤال هنا": "Type your question here",
  "نص السؤال": "Question text",
  "خصائص السؤال": "Question settings",
  "أغلق الخصائص": "Close settings",
  "نوع السؤال": "Question type",
  "اختيار من متعدد": "Multiple choice",
  "صح / خطأ": "True / false",
  "ترتيب العناصر": "Ordering",
  "مطابقة البطاقات": "Matching",
  "مناطق الصورة": "Image hotspots",
  "أضف الصورة أولًا لرسم مناطق الإجابة.": "Add an image first, then draw the answer regions.",
  "الافتراضي اختيار من متعدد. لا تحتاج فتح هذه اللوحة لتأليف نشاط ونشره.": "Multiple choice is the default. These settings are optional when creating and publishing an activity.",
  "المؤقّت": "Time limit",
  "مدة السؤال بالثواني": "Time limit in seconds",
  "ثانية": "seconds",
  "تعذّر تطبيق المدة على الكل": "Could not update all time limits",
  "طبّق على الكل": "Apply to all",
  "مظهر الحصة": "Game theme",
  "تعذّر حفظ المظهر": "Could not save theme",
  "كلاسيكي": "Classic",
  "الغابة": "Forest",
  "الفضاء": "Cosmic",
  "مرجاني": "Coral",
  "تعذّر الحفظ": "Could not save",
  "اربط سؤال تحقق": "Link verification question",
  "تعذّر ترتيب الأسئلة": "Could not reorder questions",
  "للأعلى": "Move up",
  "للأسفل": "Move down",
  "تعذّر تكرار السؤال": "Could not duplicate question",
  "تكرار السؤال": "Duplicate question",
  "تعذّر حذف السؤال": "Could not delete question",
  "حذف السؤال": "Delete question",
  "تعذّر التحميل": "Could not load",
  "تعذّر إنشاء النشاط": "Could not create activity",
  "الأنشطة": "Activities",
  "نشاط جديد": "New activity",
  "العنوان": "Title",
  "مثال: جمع الكسور": "Example: adding fractions",
  "المادة": "Subject",
  "المستوى": "Level",
  "الرفّ": "Shelf",
  "أنشئ وابدأ التأليف": "Create and start editing",
  "لا أنشطة بعد": "No activities yet",
  "أنشئ نشاطك الأول من النموذج أعلاه.": "Create your first activity with the form above.",
  "منشور": "Published",
  "مسوّدة": "Draft",
  "افتح المحرّر": "Open editor"
}
export function useEditorText(){const {i18n}=useTranslation();const ar=i18n.language.startsWith('ar');return useCallback((text:string)=>ar?text:english[text]??text,[ar])}
