export type DemoMediaId = 'reef' | 'bee' | 'space' | 'desert' | 'balloon' | 'waterfall' | 'bicycle' | 'seedling'
export type DemoLocale = 'en' | 'ar'
export type DemoQuestionText = { title: string; answers: [string, string, string, string]; explanation: string }
export type DemoQuestion = { id: string; media: DemoMediaId; correct: number; en: DemoQuestionText; ar: DemoQuestionText }

// Each row pairs the same four meanings in both languages. Display order is shuffled separately.
type TextRow = [title: string, options: string, explanation: string]
function q(media: DemoMediaId, n: number, correct: number, en: TextRow, ar: TextRow): DemoQuestion {
  function localize([title, options, explanation]: TextRow): DemoQuestionText {
    const answers = options.split('|')
    if (answers.length !== 4) throw new Error(`Expected four answers for ${media}-${n}`)
    return { title, answers: [answers[0]!, answers[1]!, answers[2]!, answers[3]!], explanation }
  }
  return { id: `${media}-${n}`, media, correct, en: localize(en), ar: localize(ar) }
}

export const demoQuestionBank: DemoQuestion[] = [
  q('reef', 1, 1,
    ['How does a sea turtle breathe?', 'Through gills|With lungs|Through its shell|Through its fins', 'Sea turtles are reptiles. They come to the surface to breathe air with their lungs.'],
    ['كيف تتنفّس السلحفاة البحرية؟', 'بالخياشيم|بالرئتين|بالصدفة|بالزعانف', 'السلاحف البحرية زواحف تصعد إلى السطح لتتنفّس الهواء برئتيها.']),
  q('reef', 2, 2,
    ['Corals belong to which group of living things?', 'Plants|Fungi|Animals|Bacteria', 'Corals are animals. Many tiny coral polyps together can build a reef.'],
    ['إلى أي مجموعة من الكائنات ينتمي المرجان؟', 'النباتات|الفطريات|الحيوانات|البكتيريا', 'المرجان حيوان. ويمكن لأعداد كبيرة من البوليبات المرجانية الصغيرة بناء شعاب مرجانية.']),
  q('reef', 3, 0,
    ['What makes seawater salty?', 'Dissolved salts|Sunlight|Fish scales|Ocean waves', 'Seawater contains dissolved salts, including sodium chloride.'],
    ['ما الذي يجعل مياه البحر مالحة؟', 'الأملاح الذائبة|ضوء الشمس|قشور الأسماك|أمواج البحر', 'تحتوي مياه البحر على أملاح ذائبة، منها كلوريد الصوديوم.']),
  q('reef', 4, 3,
    ['Which is the largest ocean on Earth?', 'Atlantic|Indian|Arctic|Pacific', 'The Pacific Ocean covers more area than any other ocean.'],
    ['ما أكبر محيط على الأرض؟', 'الأطلسي|الهندي|المتجمّد الشمالي|الهادئ', 'يغطي المحيط الهادئ مساحة أكبر من أي محيط آخر.']),
  q('reef', 5, 1,
    ['Which object has the strongest influence on Earth’s ocean tides?', 'Mars|The Moon|Saturn|Venus', 'The Moon’s gravity is the main influence on ocean tides; the Sun contributes too.'],
    ['أي جرم له التأثير الأكبر في المدّ والجزر على الأرض؟', 'المريخ|القمر|زحل|الزهرة', 'جاذبية القمر هي المؤثر الرئيسي في المدّ والجزر، وتسهم الشمس أيضًا.']),
  q('reef', 6, 2,
    ['What do most fish use to take oxygen from water?', 'Lungs|Wings|Gills|Fur', 'Gills take dissolved oxygen from water as it passes over them.'],
    ['بماذا تستخلص معظم الأسماك الأكسجين من الماء؟', 'الرئتين|الأجنحة|الخياشيم|الفرو', 'تستخلص الخياشيم الأكسجين الذائب في الماء عند مروره فوقها.']),
  q('reef', 7, 0,
    ['Which action helps protect a coral reef?', 'Keep plastic out of the sea|Break off coral|Drop fishing line|Leave litter on the beach', 'Keeping litter out of the ocean helps protect marine animals and their habitats.'],
    ['أي تصرّف يساعد على حماية الشعاب المرجانية؟', 'إبعاد البلاستيك عن البحر|كسر قطع المرجان|رمي خيوط الصيد|ترك القمامة على الشاطئ', 'إبعاد النفايات عن المحيط يساعد على حماية الحيوانات البحرية وموائلها.']),
  q('reef', 8, 3,
    ['Which body parts help a fish steer and balance?', 'Ears|Horns|Legs|Fins', 'Fish use their fins to help steer, balance and move through water.'],
    ['أي أجزاء الجسم تساعد السمكة على التوجيه والتوازن؟', 'الأذنان|القرون|الأرجل|الزعانف', 'تستخدم الأسماك زعانفها للتوجيه والتوازن والحركة في الماء.']),
  q('reef', 9, 1,
    ['Which living thing can make food using sunlight?', 'A shark|Algae|A sea turtle|A crab', 'Algae use photosynthesis and are important producers in aquatic food webs.'],
    ['أي كائن يستطيع صنع غذائه باستخدام ضوء الشمس؟', 'القرش|الطحالب|السلحفاة البحرية|السلطعون', 'تستخدم الطحالب البناء الضوئي، وهي من المنتجات المهمة في الشبكات الغذائية المائية.']),
  q('reef', 10, 0,
    ['Where do sea turtles lay their eggs?', 'In sandy nests on land|On coral underwater|In open water|On floating seaweed', 'Female sea turtles come onto beaches and lay their eggs in nests dug in the sand.'],
    ['أين تضع السلاحف البحرية بيضها؟', 'في أعشاش رملية على اليابسة|على المرجان تحت الماء|في المياه المفتوحة|على الطحالب العائمة', 'تصعد إناث السلاحف البحرية إلى الشواطئ وتضع بيضها في أعشاش تحفرها في الرمل.']),

  q('bee', 1, 0,
    ['How many legs does a honeybee have?', 'Six|Four|Eight|Ten', 'Honeybees are insects, and adult insects have six legs.'],
    ['كم رجلًا لنحلة العسل؟', 'ست|أربع|ثمانٍ|عشر', 'نحل العسل من الحشرات، وللحشرة البالغة ست أرجل.']),
  q('bee', 2, 3,
    ['What do honeybees collect to make honey?', 'Sand|Salt|Dew only|Nectar', 'Bees collect nectar from flowers and process it into honey.'],
    ['ماذا يجمع نحل العسل لصنع العسل؟', 'الرمل|الملح|الندى فقط|الرحيق', 'يجمع النحل الرحيق من الأزهار ويحوّله إلى عسل.']),
  q('bee', 3, 1,
    ['What can a bee carry from one flower to another?', 'Pebbles|Pollen|Tree bark|Roots', 'Pollen can stick to a bee and be carried to another flower, helping pollination.'],
    ['ماذا يمكن أن تنقل النحلة من زهرة إلى أخرى؟', 'الحصى|حبوب اللقاح|لحاء الأشجار|الجذور', 'قد تلتصق حبوب اللقاح بالنحلة وتنتقل إلى زهرة أخرى، مما يساعد على التلقيح.']),
  q('bee', 4, 2,
    ['What are the colorful parts around a flower’s center called?', 'Roots|Branches|Petals|Stems', 'Petals are parts of a flower and can help attract pollinators.'],
    ['ماذا تُسمّى الأجزاء الملوّنة حول مركز الزهرة؟', 'الجذور|الأغصان|البتلات|السيقان', 'البتلات أجزاء من الزهرة، وقد تساعد على جذب الكائنات التي تلقّحها.']),
  q('bee', 5, 0,
    ['A honeybee belongs to which animal group?', 'Insects|Birds|Reptiles|Fish', 'A honeybee is an insect, with six legs and three main body sections.'],
    ['إلى أي مجموعة حيوانية تنتمي نحلة العسل؟', 'الحشرات|الطيور|الزواحف|الأسماك', 'النحلة حشرة لها ست أرجل وثلاثة أجزاء رئيسية في جسمها.']),
  q('bee', 6, 3,
    ['What is a managed home for a honeybee colony called?', 'A kennel|An aquarium|A stable|A hive', 'A beehive houses a honeybee colony and its honeycomb.'],
    ['ماذا يُسمّى المسكن الذي يُربّى فيه نحل العسل؟', 'بيت الكلب|حوض السمك|الإسطبل|خلية النحل', 'تضم خلية النحل مستعمرة النحل وأقراص الشمع.']),
  q('bee', 7, 1,
    ['A honeycomb cell is usually shaped like a…', 'Circle|Hexagon|Triangle|Pentagon', 'The familiar cells in a honeycomb are hexagons, which fit together without gaps.'],
    ['ما الشكل المعتاد لخلايا قرص العسل؟', 'دائرة|سداسي|مثلث|خماسي', 'الخلايا المألوفة في قرص العسل سداسية الشكل، وتتجاور دون فراغات.']),
  q('bee', 8, 2,
    ['How many sides does a hexagon have?', 'Five|Eight|Six|Seven', 'A hexagon is a polygon with six sides.'],
    ['كم ضلعًا للشكل السداسي؟', 'خمسة|ثمانية|ستة|سبعة', 'الشكل السداسي مضلع له ستة أضلاع.']),
  q('bee', 9, 0,
    ['A bee visits 4 flowers, then 5 more. How many in total?', '9|8|10|7', 'Add the two visits: 4 + 5 = 9 flowers.'],
    ['زارت نحلة 4 أزهار ثم 5 أخرى. كم زهرة زارت؟', '9|8|10|7', 'نجمع الزيارتين: 4 + 5 = 9 أزهار.']),
  q('bee', 10, 3,
    ['Which part of a sunflower anchors it in the ground?', 'Petals|Pollen|Seeds|Roots', 'Roots anchor the plant and help it absorb water and minerals.'],
    ['أي جزء من دوّار الشمس يثبّته في الأرض؟', 'البتلات|حبوب اللقاح|البذور|الجذور', 'تثبّت الجذور النبات وتساعده على امتصاص الماء والمعادن.']),

  q('space', 1, 1,
    ['Which planet is illustrated here?', 'Mars|Saturn|Earth|Mercury', 'Saturn is recognizable by its broad, bright system of rings.'],
    ['أي كوكب يظهر في هذه الصورة التوضيحية؟', 'المريخ|زحل|الأرض|عطارد', 'يمكن تمييز زحل بحلقاته العريضة والمضيئة.']),
  q('space', 2, 2,
    ['Saturn’s rings are made mostly of…', 'Clouds of smoke|Liquid water|Ice particles with rock and dust|Tree roots', 'Saturn’s rings contain countless particles, mostly water ice, with rock and dust.'],
    ['ممّ تتكوّن حلقات زحل في معظمها؟', 'سحب من الدخان|ماء سائل|جسيمات جليد مع صخور وغبار|جذور أشجار', 'تضم حلقات زحل جسيمات لا تُحصى، معظمها جليد مائي مع صخور وغبار.']),
  q('space', 3, 0,
    ['What keeps planets in orbit around the Sun?', 'Gravity|Sound|Ocean currents|Magnetic bicycle brakes', 'Gravity pulls planets toward the Sun while their motion carries them along their orbits.'],
    ['ما الذي يبقي الكواكب في مداراتها حول الشمس؟', 'الجاذبية|الصوت|تيارات المحيط|مكابح الدراجة المغناطيسية', 'تجذب الجاذبية الكواكب نحو الشمس، بينما تحملها حركتها في مداراتها.']),
  q('space', 4, 3,
    ['About how long does Earth take to turn once on its axis?', 'One minute|One month|One year|One day', 'Earth’s daily rotation produces the familiar cycle of day and night.'],
    ['كم تستغرق الأرض تقريبًا لتدور مرة حول محورها؟', 'دقيقة|شهر|سنة|يوم', 'ينتج عن دوران الأرض اليومي تعاقب الليل والنهار.']),
  q('space', 5, 1,
    ['One full orbit of Earth around the Sun takes about…', 'One hour|One year|One week|Ten years', 'A year is the time Earth takes to complete an orbit around the Sun.'],
    ['تستغرق دورة الأرض حول الشمس نحو…', 'ساعة|سنة|أسبوع|عشر سنوات', 'السنة هي الزمن الذي تستغرقه الأرض لإكمال دورة حول الشمس.']),
  q('space', 6, 2,
    ['Why can we see the Moon shining?', 'It burns like a candle|It has streetlights|It reflects sunlight|It is made of lightning', 'The Moon shines in our sky because its surface reflects light from the Sun.'],
    ['لماذا نرى القمر مضيئًا؟', 'لأنه يحترق كالشمعة|لأن فيه مصابيح شوارع|لأنه يعكس ضوء الشمس|لأنه مصنوع من البرق', 'نرى القمر مضيئًا لأن سطحه يعكس ضوء الشمس.']),
  q('space', 7, 0,
    ['Our Sun is a…', 'Star|Planet|Moon|Comet', 'The Sun is the star at the center of our solar system.'],
    ['شمسنا هي…', 'نجم|كوكب|قمر|مذنّب', 'الشمس هي النجم الواقع في مركز مجموعتنا الشمسية.']),
  q('space', 8, 3,
    ['Which galaxy contains our solar system?', 'Andromeda|Whirlpool|Sombrero|Milky Way', 'Our solar system is part of the Milky Way galaxy.'],
    ['في أي مجرّة تقع مجموعتنا الشمسية؟', 'المرأة المسلسلة|الدوّامة|السومبريرو|درب التبانة', 'مجموعتنا الشمسية جزء من مجرّة درب التبانة.']),
  q('space', 9, 1,
    ['Which planet is closest to the Sun?', 'Neptune|Mercury|Earth|Saturn', 'Mercury has the closest orbit to the Sun of the eight planets.'],
    ['ما أقرب كوكب إلى الشمس؟', 'نبتون|عطارد|الأرض|زحل', 'مدار عطارد هو الأقرب إلى الشمس بين الكواكب الثمانية.']),
  q('space', 10, 2,
    ['Which planet is known as the Red Planet?', 'Venus|Jupiter|Mars|Saturn', 'Iron minerals on Mars give its surface a rusty red appearance.'],
    ['أي كوكب يُعرف بالكوكب الأحمر؟', 'الزهرة|المشتري|المريخ|زحل', 'تمنح معادن الحديد سطح المريخ مظهره الأحمر الشبيه بالصدأ.']),

  q('desert', 1, 0,
    ['How many humps does a dromedary camel have?', 'One|Two|Three|None', 'A dromedary has one hump. A Bactrian camel has two.'],
    ['كم سنامًا للجمل العربي؟', 'واحد|اثنان|ثلاثة|لا سنام له', 'للجمل العربي سنام واحد، وللجمل البختي سنامان.']),
  q('desert', 2, 3,
    ['What is stored in a camel’s hump?', 'Drinking water|Air|Sand|Fat', 'The hump stores fat, which the camel can use as an energy reserve.'],
    ['ماذا يخزّن الجمل في سنامه؟', 'ماء الشرب|الهواء|الرمل|الدهون', 'يخزّن السنام دهونًا يستطيع الجمل استخدامها مصدرًا احتياطيًا للطاقة.']),
  q('desert', 3, 1,
    ['What mainly defines a desert?', 'It is always hot|It gets very little precipitation|It has no rocks|It has no wind', 'Deserts receive very little precipitation. Some deserts are cold.'],
    ['ما الصفة الأساسية التي تميّز الصحراء؟', 'حارّة دائمًا|قليلة الهطول جدًا|بلا صخور|بلا رياح', 'تتلقّى الصحاري هطولًا قليلًا جدًا، وبعضها بارد.']),
  q('desert', 4, 2,
    ['How do a camel’s broad feet help on sand?', 'They create rain|They store food|They spread its weight|They make the sand freeze', 'Broad feet spread the camel’s weight over more sand, helping reduce sinking.'],
    ['كيف تساعد أقدام الجمل العريضة على الرمل؟', 'تصنع المطر|تخزّن الغذاء|توزّع وزنه|تجمّد الرمل', 'توزّع الأقدام العريضة وزن الجمل على مساحة أكبر، فتقلّل غوصه في الرمل.']),
  q('desert', 5, 0,
    ['What helps shape and move sand dunes?', 'Wind|Moonlight|Birdsong|Tree roots alone', 'Wind can pick up sand grains and deposit them to build and reshape dunes.'],
    ['ما الذي يساعد على تشكيل الكثبان الرملية وتحريكها؟', 'الرياح|ضوء القمر|تغريد الطيور|جذور الأشجار وحدها', 'تحمل الرياح حبيبات الرمل وتُرسبها، فتكوّن الكثبان وتعيد تشكيلها.']),
  q('desert', 6, 3,
    ['A grain of sand is which state of matter?', 'Gas|Liquid|Plasma|Solid', 'Although a pile of sand can flow, each grain is a solid.'],
    ['ما الحالة الفيزيائية لحبّة الرمل؟', 'غازية|سائلة|بلازما|صلبة', 'قد تنساب كومة الرمل، لكن كل حبّة منها جسم صلب.']),
  q('desert', 7, 1,
    ['In which general direction does the Sun rise?', 'West|East|North|South', 'The Sun appears to rise in the east because Earth rotates toward the east.'],
    ['من أي جهة تشرق الشمس عمومًا؟', 'الغرب|الشرق|الشمال|الجنوب', 'تبدو الشمس وكأنها تشرق من الشرق لأن الأرض تدور نحو الشرق.']),
  q('desert', 8, 2,
    ['Which instrument measures temperature?', 'Ruler|Compass|Thermometer|Stopwatch', 'A thermometer measures temperature; a compass indicates direction.'],
    ['أي أداة تقيس درجة الحرارة؟', 'المسطرة|البوصلة|مقياس الحرارة|ساعة الإيقاف', 'يقيس مقياس الحرارة درجة الحرارة، بينما تحدّد البوصلة الاتجاه.']),
  q('desert', 9, 0,
    ['A camel walks 3 km, then another 3 km. How far is that?', '6 km|3 km|9 km|12 km', 'Add the two distances: 3 + 3 = 6 kilometres.'],
    ['مشى جمل 3 كم ثم 3 كم أخرى. كم قطع؟', '6 كم|3 كم|9 كم|12 كم', 'نجمع المسافتين: 3 + 3 = 6 كيلومترات.']),
  q('desert', 10, 3,
    ['Oman is located on which peninsula?', 'Iberian|Italian|Scandinavian|Arabian', 'Oman is on the southeastern part of the Arabian Peninsula.'],
    ['في أي شبه جزيرة تقع عُمان؟', 'الإيبيرية|الإيطالية|الإسكندنافية|العربية', 'تقع عُمان في الجزء الجنوبي الشرقي من شبه الجزيرة العربية.']),

  q('balloon', 1, 1,
    ['Why can heating the air help a hot-air balloon rise?', 'It makes the air solid|It makes the air less dense|It removes gravity|It turns air into water', 'Warm air is less dense than the surrounding cooler air, helping the balloon rise.'],
    ['لماذا يساعد تسخين الهواء المنطاد على الارتفاع؟', 'يجعل الهواء صلبًا|يقلّل كثافة الهواء|يلغي الجاذبية|يحوّل الهواء إلى ماء', 'الهواء الدافئ أقل كثافة من الهواء الأبرد المحيط به، مما يساعد المنطاد على الارتفاع.']),
  q('balloon', 2, 2,
    ['Which force pulls a balloon toward Earth?', 'Friction only|Sound|Gravity|Magnetism only', 'Gravity pulls objects, including balloons, toward Earth.'],
    ['أي قوة تجذب المنطاد نحو الأرض؟', 'الاحتكاك وحده|الصوت|الجاذبية|المغناطيسية وحدها', 'تجذب الجاذبية الأجسام، ومنها المناطيد، نحو الأرض.']),
  q('balloon', 3, 0,
    ['Air is mostly a mixture of…', 'Gases|Metals|Liquids|Crystals', 'Air is a mixture of gases, mainly nitrogen and oxygen.'],
    ['الهواء في معظمه خليط من…', 'الغازات|المعادن|السوائل|البلّورات', 'الهواء خليط من غازات، أهمها النيتروجين والأكسجين.']),
  q('balloon', 4, 3,
    ['What does a hot-air balloon’s burner provide?', 'Ice|Soil|Magnetism|Heat', 'The burner heats the air inside the balloon’s envelope.'],
    ['ماذا يوفّر موقد منطاد الهواء الساخن؟', 'الجليد|التراب|المغناطيسية|الحرارة', 'يسخّن الموقد الهواء داخل غلاف المنطاد.']),
  q('balloon', 5, 1,
    ['What largely carries a free-flying balloon horizontally?', 'Ocean tides|Wind|Its shadow|The Moon’s light', 'A free-flying balloon moves horizontally with the wind around it.'],
    ['ما الذي يحمل المنطاد الحر أفقيًا في الغالب؟', 'مدّ المحيط|الرياح|ظلّه|ضوء القمر', 'يتحرّك المنطاد الحر أفقيًا مع الرياح المحيطة به.']),
  q('balloon', 6, 2,
    ['A balloon travels 40 km in 2 hours. Its average speed is…', '80 km/h|10 km/h|20 km/h|42 km/h', 'Average speed is distance divided by time: 40 ÷ 2 = 20 km/h.'],
    ['قطع منطاد 40 كم في ساعتين. ما متوسّط سرعته؟', '80 كم/ساعة|10 كم/ساعة|20 كم/ساعة|42 كم/ساعة', 'متوسّط السرعة هو المسافة مقسومة على الزمن: 40 ÷ 2 = 20 كم/ساعة.']),
  q('balloon', 7, 0,
    ['What usually happens to air as it warms at constant pressure?', 'It expands|It becomes metal|It disappears|It always freezes', 'When air warms at constant pressure, it expands and occupies more space.'],
    ['ماذا يحدث للهواء عند تسخينه تحت ضغط ثابت؟', 'يتمدّد|يصبح معدنًا|يختفي|يتجمّد دائمًا', 'عند تسخين الهواء تحت ضغط ثابت يتمدّد ويشغل حيّزًا أكبر.']),
  q('balloon', 8, 3,
    ['What is the upward force from the surrounding air called?', 'Weight|Friction|Tension|Buoyancy', 'Buoyancy is the upward force a fluid, including air, exerts on an immersed object.'],
    ['ماذا تُسمّى القوة الصاعدة التي يؤثّر بها الهواء المحيط؟', 'الوزن|الاحتكاك|الشدّ|الطفو', 'الطفو قوة صاعدة يؤثّر بها المائع، ومنه الهواء، في الجسم الموجود داخله.']),
  q('balloon', 9, 1,
    ['A balloon rises from 100 m to 250 m. How much did it climb?', '350 m|150 m|100 m|250 m', 'Subtract the starting height: 250 − 100 = 150 metres.'],
    ['ارتفع منطاد من 100 م إلى 250 م. كم بلغ ارتفاع صعوده؟', '350 م|150 م|100 م|250 م', 'نطرح الارتفاع الأول: 250 − 100 = 150 مترًا.']),
  q('balloon', 10, 2,
    ['Which tool can measure wind speed?', 'Thermometer|Ruler|Anemometer|Balance scale', 'An anemometer measures wind speed, which matters when planning a balloon flight.'],
    ['أي أداة يمكنها قياس سرعة الرياح؟', 'مقياس الحرارة|المسطرة|الأنيمومتر|ميزان الكتلة', 'يقيس الأنيمومتر سرعة الرياح، وهي معلومة مهمة عند التخطيط لرحلة منطاد.']),

  q('waterfall', 1, 0,
    ['What pulls the water downward in a waterfall?', 'Gravity|Moonlight|Magnetism|Sound', 'Gravity pulls the water toward Earth, carrying it down the falls.'],
    ['ما الذي يجذب مياه الشلال إلى الأسفل؟', 'الجاذبية|ضوء القمر|المغناطيسية|الصوت', 'تجذب الجاذبية الماء نحو الأرض فيندفع إلى أسفل الشلال.']),
  q('waterfall', 2, 3,
    ['When liquid water becomes water vapor, this is…', 'Freezing|Melting|Condensation|Evaporation', 'Evaporation changes liquid water into water vapor.'],
    ['عندما يتحوّل الماء السائل إلى بخار فإن ذلك يُسمّى…', 'التجمّد|الانصهار|التكاثف|التبخّر', 'يحوّل التبخّر الماء من الحالة السائلة إلى بخار ماء.']),
  q('waterfall', 3, 1,
    ['When water vapor forms liquid droplets, this is…', 'Melting|Condensation|Burning|Freezing', 'Condensation changes water vapor into liquid droplets, as in clouds.'],
    ['عندما يتحوّل بخار الماء إلى قطرات سائلة فإن ذلك يُسمّى…', 'الانصهار|التكاثف|الاحتراق|التجمّد', 'يحوّل التكاثف بخار الماء إلى قطرات سائلة، كما يحدث في السحب.']),
  q('waterfall', 4, 2,
    ['Ice is water in which state?', 'Gas|Plasma|Solid|Liquid', 'Ice is the solid form of water.'],
    ['الجليد هو الماء في أي حالة؟', 'غازية|بلازما|صلبة|سائلة', 'الجليد هو الشكل الصلب للماء.']),
  q('waterfall', 5, 0,
    ['At standard atmospheric pressure, pure water freezes at…', '0°C|50°C|100°C|200°C', 'Pure water freezes at 0°C under standard atmospheric pressure.'],
    ['عند الضغط الجوي القياسي، يتجمّد الماء النقي عند…', '0°C|50°C|100°C|200°C', 'يتجمّد الماء النقي عند صفر درجة مئوية تحت الضغط الجوي القياسي.']),
  q('waterfall', 6, 3,
    ['A river naturally flows from…', 'Lower to higher ground|Cold to hot places only|West to east only|Higher to lower ground', 'Gravity makes water flow downhill when there is a change in elevation.'],
    ['يتدفّق النهر طبيعيًا من…', 'المنخفض إلى المرتفع|البارد إلى الحار فقط|الغرب إلى الشرق فقط|المرتفع إلى المنخفض', 'تجعل الجاذبية الماء يتدفّق إلى الأسفل عند وجود فرق في الارتفاع.']),
  q('waterfall', 7, 1,
    ['What is the wearing away of rock by moving water called?', 'Pollination|Erosion|Photosynthesis|Germination', 'Moving water can wear away and carry rock and soil through erosion.'],
    ['ماذا يُسمّى تآكل الصخور بفعل الماء المتحرّك؟', 'التلقيح|التعرية|البناء الضوئي|الإنبات', 'قد ينحت الماء المتحرّك الصخور والتربة ويحملها بعملية التعرية.']),
  q('waterfall', 8, 2,
    ['Electricity made using moving water is called…', 'Solar power|Geothermal power|Hydropower|Nuclear power', 'Hydropower uses the energy of moving water to generate electricity.'],
    ['ماذا تُسمّى الطاقة الكهربائية الناتجة باستخدام الماء المتحرّك؟', 'الطاقة الشمسية|الطاقة الحرارية الجوفية|الطاقة الكهرومائية|الطاقة النووية', 'تستخدم الطاقة الكهرومائية طاقة الماء المتحرّك لتوليد الكهرباء.']),
  q('waterfall', 9, 0,
    ['What is the chemical formula for water?', 'H₂O|CO₂|O₂|NaCl', 'A water molecule contains two hydrogen atoms and one oxygen atom.'],
    ['ما الصيغة الكيميائية للماء؟', 'H₂O|CO₂|O₂|NaCl', 'يتكوّن جزيء الماء من ذرتي هيدروجين وذرة أكسجين واحدة.']),
  q('waterfall', 10, 3,
    ['River water is usually classified as…', 'Seawater|Lava|Oil|Freshwater', 'Rivers generally carry freshwater, which has much less dissolved salt than seawater.'],
    ['تُصنّف مياه الأنهار عادةً على أنها…', 'مياه بحر|حمم بركانية|زيت|مياه عذبة', 'تحمل الأنهار عادة مياهًا عذبة تقل فيها الأملاح الذائبة كثيرًا عن مياه البحر.']),

  q('bicycle', 1, 1,
    ['What shape are the wheels on this bicycle?', 'Triangles|Circles|Squares|Hexagons', 'Circular wheels can roll smoothly because the rim stays the same distance from the center.'],
    ['ما شكل عجلتي هذه الدراجة؟', 'مثلثان|دائرتان|مربّعان|سداسيان', 'تتدحرج العجلات الدائرية بسلاسة لأن حافتها تبعد المسافة نفسها عن المركز.']),
  q('bicycle', 2, 2,
    ['What helps bicycle brakes slow a moving wheel?', 'Photosynthesis|Buoyancy|Friction|Evaporation', 'Brakes use friction to oppose motion and slow the bicycle.'],
    ['ما الذي يساعد مكابح الدراجة على إبطاء العجلة؟', 'البناء الضوئي|الطفو|الاحتكاك|التبخّر', 'تستخدم المكابح الاحتكاك لمقاومة الحركة وإبطاء الدراجة.']),
  q('bicycle', 3, 0,
    ['What carries motion from the pedals toward the rear wheel on this bicycle?', 'The chain|The bell|The seat|The front reflector', 'The chain connects the front chainring to a rear sprocket, transmitting pedaling motion.'],
    ['ما الذي ينقل حركة الدوّاستين نحو العجلة الخلفية في هذه الدراجة؟', 'السلسلة|الجرس|المقعد|العاكس الأمامي', 'تربط السلسلة المسنّن الأمامي بمسنّن خلفي، فتنقل حركة التدويس.']),
  q('bicycle', 4, 3,
    ['How many degrees are in one full turn of a wheel?', '90°|180°|270°|360°', 'One full rotation is 360 degrees.'],
    ['كم درجة في دورة كاملة للعجلة؟', '90°|180°|270°|360°', 'الدورة الكاملة تساوي 360 درجة.']),
  q('bicycle', 5, 1,
    ['The distance from a circle’s center to its edge is the…', 'Diameter|Radius|Perimeter|Area', 'The radius runs from the center of a circle to any point on its edge.'],
    ['المسافة من مركز الدائرة إلى حافتها هي…', 'القطر|نصف القطر|المحيط|المساحة', 'يمتد نصف القطر من مركز الدائرة إلى أي نقطة على حافتها.']),
  q('bicycle', 6, 2,
    ['A wheel has a radius of 30 cm. What is its diameter?', '15 cm|30 cm|60 cm|90 cm', 'The diameter is twice the radius: 2 × 30 = 60 cm.'],
    ['نصف قطر عجلة 30 سم. ما قطرها؟', '15 سم|30 سم|60 سم|90 سم', 'القطر يساوي ضعفي نصف القطر: 2 × 30 = 60 سم.']),
  q('bicycle', 7, 0,
    ['You cycle 12 km in one hour. At the same speed, how far in half an hour?', '6 km|12 km|24 km|18 km', 'Half the time at the same speed gives half the distance: 6 km.'],
    ['تقطع بالدراجة 12 كم في ساعة. كم تقطع في نصف ساعة بالسرعة نفسها؟', '6 كم|12 كم|24 كم|18 كم', 'نصف الزمن بالسرعة نفسها يعطي نصف المسافة، أي 6 كم.']),
  q('bicycle', 8, 3,
    ['What does a bicycle reflector do?', 'Makes fuel|Stores water|Creates daylight|Reflects incoming light', 'A reflector sends incoming light back, helping a bicycle be seen.'],
    ['ما وظيفة عاكس الدراجة؟', 'يصنع الوقود|يخزّن الماء|يصنع ضوء النهار|يعكس الضوء الساقط عليه', 'يعيد العاكس الضوء الساقط عليه، مما يساعد على رؤية الدراجة.']),
  q('bicycle', 9, 1,
    ['Four bicycles have how many wheels altogether?', '6|8|10|12', 'An ordinary bicycle has two wheels, so 4 × 2 = 8 wheels.'],
    ['كم عجلة لأربع دراجات هوائية؟', '6|8|10|12', 'للدراجة العادية عجلتان، لذا 4 × 2 = 8 عجلات.']),
  q('bicycle', 10, 2,
    ['Which unit is suitable for measuring a long cycling route?', 'Millilitres|Grams|Kilometres|Degrees Celsius', 'Kilometres measure distance, while grams measure mass and millilitres measure volume.'],
    ['أي وحدة تناسب قياس طول مسار طويل للدراجات؟', 'الملليلتر|الغرام|الكيلومتر|الدرجة المئوية', 'يقيس الكيلومتر المسافة، بينما يقيس الغرام الكتلة والملليلتر الحجم.']),

  q('seedling', 1, 0,
    ['Which part of a young plant absorbs water from the soil?', 'Roots|Petals|Fruit|Pollen', 'Roots absorb water and dissolved minerals from the soil.'],
    ['أي جزء من النبات الصغير يمتص الماء من التربة؟', 'الجذور|البتلات|الثمرة|حبوب اللقاح', 'تمتص الجذور الماء والمعادن الذائبة من التربة.']),
  q('seedling', 2, 3,
    ['Which plant part supports its leaves above the ground?', 'Pollen|Fruit|Petal|Stem', 'The stem supports the leaves and transports water and other substances through the plant.'],
    ['أي جزء من النبات يحمل أوراقه فوق الأرض؟', 'حبوب اللقاح|الثمرة|البتلة|الساق', 'تحمل الساق الأوراق وتنقل الماء ومواد أخرى داخل النبات.']),
  q('seedling', 3, 1,
    ['What process do green plants use to make food with light?', 'Freezing|Photosynthesis|Rusting|Erosion', 'Photosynthesis uses light energy to make sugars from water and carbon dioxide.'],
    ['بأي عملية يصنع النبات الأخضر غذاءه باستخدام الضوء؟', 'التجمّد|البناء الضوئي|الصدأ|التعرية', 'يستخدم البناء الضوئي طاقة الضوء لصنع السكريات من الماء وثاني أكسيد الكربون.']),
  q('seedling', 4, 2,
    ['Which gas do plants take in for photosynthesis?', 'Helium|Hydrogen|Carbon dioxide|Neon', 'Plants use carbon dioxide, water and light to produce sugars during photosynthesis.'],
    ['أي غاز يأخذه النبات لعملية البناء الضوئي؟', 'الهيليوم|الهيدروجين|ثاني أكسيد الكربون|النيون', 'يستخدم النبات ثاني أكسيد الكربون والماء والضوء لإنتاج السكريات في البناء الضوئي.']),
  q('seedling', 5, 0,
    ['Which gas is released during photosynthesis?', 'Oxygen|Helium|Neon|Methane', 'Oxygen is released as plants carry out photosynthesis.'],
    ['أي غاز ينطلق خلال البناء الضوئي؟', 'الأكسجين|الهيليوم|النيون|الميثان', 'ينطلق الأكسجين عندما يقوم النبات بعملية البناء الضوئي.']),
  q('seedling', 6, 3,
    ['Where does a plant get the light energy used in photosynthesis outdoors?', 'Soil grains|Earth’s core|A magnet|The Sun', 'Sunlight supplies the energy plants use in photosynthesis outdoors.'],
    ['من أين يحصل النبات في الخارج على الطاقة الضوئية للبناء الضوئي؟', 'حبيبات التربة|لبّ الأرض|المغناطيس|الشمس', 'يوفّر ضوء الشمس الطاقة التي يستخدمها النبات في البناء الضوئي في الخارج.']),
  q('seedling', 7, 1,
    ['What is it called when a seed starts growing into a plant?', 'Condensation|Germination|Evaporation|Erosion', 'Germination is the beginning of a seed’s growth into a new plant.'],
    ['ماذا يُسمّى بدء نمو البذرة لتصبح نباتًا؟', 'التكاثف|الإنبات|التبخّر|التعرية', 'الإنبات هو بداية نمو البذرة لتصبح نباتًا جديدًا.']),
  q('seedling', 8, 2,
    ['The dew drop on a leaf is water in which state?', 'Solid|Gas|Liquid|Plasma', 'A visible dew drop is liquid water.'],
    ['في أي حالة يكون الماء في قطرة الندى على الورقة؟', 'صلبة|غازية|سائلة|بلازما', 'قطرة الندى المرئية ماء في الحالة السائلة.']),
  q('seedling', 9, 0,
    ['Which part of most green plants carries out much of their photosynthesis?', 'Leaves|Dry bark|Dead roots|Seed coats', 'Leaves contain chloroplasts that capture light for photosynthesis.'],
    ['أي جزء من معظم النباتات الخضراء يقوم بجزء كبير من البناء الضوئي؟', 'الأوراق|اللحاء الجاف|الجذور الميتة|أغلفة البذور', 'تحتوي الأوراق على بلاستيدات خضراء تلتقط الضوء للبناء الضوئي.']),
  q('seedling', 10, 3,
    ['You plant 3 rows of 4 seeds. How many seeds is that?', '7|9|10|12', 'Three rows with four seeds each gives 3 × 4 = 12 seeds.'],
    ['زرعت 3 صفوف في كل منها 4 بذور. كم بذرة زرعت؟', '7|9|10|12', 'ثلاثة صفوف، في كل منها أربع بذور، تعطي 3 × 4 = 12 بذرة.']),
]
