export const experienceEn = {
  title: 'A little play.', titleAccent: 'A lot of learning.',
  intro: 'Turn your lessons into lively quizzes. Create with AI, play together, and discover what really clicks.',
  create: 'Create your first activity', try: 'Try a quick quiz',
  note: 'Your material. Your classroom. A whole new energy.',
  teacher: 'For teachers', student: 'For students',
  demo: 'Try it yourself', demoNote: '3-question demo · No account needed',
  shuffle: 'New questions', imageLabel: 'AI-generated image', imageUnavailable: 'Photo unavailable',
  question: 'Question', of: 'of', choose: 'Pick an answer. Let’s see what you know!',
  correct: 'You’ve got it!', incorrect: 'A little discovery!', correctAnswer: 'Correct answer:',
  next: 'Next question', results: 'See my result', replay: 'Try another round',
  complete: 'That’s the joy of learning.', resultBody: 'Bring this energy to your next lesson.',
  scoreLabel: 'Your demo score', correctCount: 'correct answers',
  joinTitle: 'Class is starting?', joinBody: 'Enter your teacher’s code and jump in.',
  joinPlaceholder: 'Game code', join: 'Join the game',
  joinEmpty: 'Enter the code shown on your teacher’s screen.', joinShort: 'Enter all six letters or digits of your code.',
  ribbon: ['Create with AI', 'Play together', 'Learn by doing', 'See what clicks'],
  howTitle: 'Your lesson. Their next “aha!”',
  howBody: 'From the material you teach to the moment they understand. You’re in control at every step.',
  steps: [
    { title: 'Bring your material', body: 'Upload a PDF or start from scratch. Give your activity a home in your course.', action: 'Start with your lesson' },
    { title: 'Make it a question', body: 'Generate questions with AI, check their sources, and make them your own before publishing.', action: 'Create an activity' },
    { title: 'Bring the room to life', body: 'Host a live session or assign practice. Review answers, spot gaps, and help students try again.', action: 'Set up your classroom' },
  ],
  workflow: 'Explore the workflow', example: 'Example preview',
  source: 'Your course material', sourceFile: 'Biology · Plant life.pdf', sourcePage: 'Page 12',
  sourceHeading: 'How plants make food', sourceText: 'Plants use sunlight, water and carbon dioxide to produce glucose and release oxygen.',
  sourceSelection: 'Start with the pages you want to teach.',
  sourceLink: 'Linked to your source', editorTitle: 'What do plants need for photosynthesis?',
  editorOptions: ['Sunlight, water and CO₂', 'Only soil', 'Only oxygen', 'Only heat'],
  editorNote: 'Review, edit, then publish.', liveTitle: 'Everyone has a way in.',
  liveBody: 'One classroom. One join code. Ready to learn together.', liveCode: 'Example game code', liveFooter: 'Live play · Homework · Self-study',
  typesTitle: 'More ways to make it click.',
  typesBody: 'Choose the interaction that fits the idea. There’s more to understanding than picking A, B, C or D.',
  types: ['Quiz', 'True or false', 'Ordering', 'Drag and drop', 'Interactive images'],
  rolesTitle: 'Good questions bring us together.',
  teacherTitle: 'Your subject. Their attention.',
  teacherBody: 'Build activities from your own teaching material. Add a live challenge, assign homework, and follow each learner’s progress.',
  teacherAction: 'Start teaching', studentTitle: 'Find your next “I get it.”',
  studentBody: 'Join your class, practice at your pace, and turn every answer into another step forward.',
  studentAction: 'Start learning', photoAlt: 'A learner wearing headphones while studying on a laptop',
  teacherArtTitle: 'Make room for discovery.', teacherArtBody: 'Create. Play. Understand.',
  plansAction: 'Get started', plansContact: 'Talk to us',
}

export const experienceAr: typeof experienceEn = {
  title: 'نلعب قليلًا.', titleAccent: 'نتعلّم كثيرًا.',
  intro: 'حوّل دروسك إلى تحديات ممتعة. أنشئ أسئلة بالذكاء الاصطناعي، العب مع طلابك، واكتشف ما فهموه فعلًا.',
  create: 'أنشئ نشاطك الأول', try: 'جرّب تحديًا سريعًا',
  note: 'محتواك. صفّك. وحماس يتجدّد.',
  teacher: 'للمعلّمين', student: 'للطلاب',
  demo: 'جرّب بنفسك', demoNote: '3 أسئلة تجريبية · دون حساب',
  shuffle: 'أسئلة جديدة', imageLabel: 'صورة مولّدة بالذكاء الاصطناعي', imageUnavailable: 'الصورة غير متاحة',
  question: 'السؤال', of: 'من', choose: 'اختر إجابة. لنكتشف ما تعرفه!',
  correct: 'أحسنت، إجابة صحيحة!', incorrect: 'معلومة جديدة لك!', correctAnswer: 'الإجابة الصحيحة:',
  next: 'السؤال التالي', results: 'اعرض نتيجتي', replay: 'جرّب جولة جديدة',
  complete: 'هذه متعة التعلّم.', resultBody: 'انقل هذا الحماس إلى درسك القادم.',
  scoreLabel: 'نتيجتك في التجربة', correctCount: 'إجابات صحيحة',
  joinTitle: 'بدأت الحصة؟', joinBody: 'أدخل رمز معلّمك وانضم إلى التحدي.',
  joinPlaceholder: 'رمز الانضمام', join: 'انضم إلى اللعب',
  joinEmpty: 'أدخل الرمز الظاهر على شاشة المعلّم.', joinShort: 'أكمل الرمز المكوّن من ستة أحرف أو أرقام.',
  ribbon: ['أنشئ بالذكاء الاصطناعي', 'العبوا معًا', 'تعلّم بالتجربة', 'اكتشف ما فهموه'],
  howTitle: 'درسك. ولحظة «الآن فهمت!»',
  howBody: 'من المادة التي تدرّسها إلى اللحظة التي يفهمونها. القرار لك في كل خطوة.',
  steps: [
    { title: 'ابدأ بمحتواك', body: 'ارفع ملف PDF أو ابدأ من الصفر، وضع نشاطك ضمن مقرّرك الدراسي.', action: 'ابدأ بدرسك' },
    { title: 'حوّله إلى سؤال', body: 'ولّد أسئلة بالذكاء الاصطناعي، راجع مصادرها، وعدّلها بطريقتك قبل النشر.', action: 'أنشئ نشاطًا' },
    { title: 'أشعل حماس الصف', body: 'قدّم جلسة مباشرة أو كلّف طلابك بالتدريب. راجع إجاباتهم، واكتشف الصعوبات، وساعدهم على المحاولة مجددًا.', action: 'جهّز صفّك' },
  ],
  workflow: 'اكتشف خطوات العمل', example: 'معاينة توضيحية',
  source: 'محتوى مقرّرك', sourceFile: 'الأحياء · حياة النبات.pdf', sourcePage: 'صفحة 12',
  sourceHeading: 'كيف يصنع النبات غذاءه', sourceText: 'يستخدم النبات ضوء الشمس والماء وثاني أكسيد الكربون لإنتاج الجلوكوز وإطلاق الأكسجين.',
  sourceSelection: 'ابدأ بالصفحات التي تريد تدريسها.',
  sourceLink: 'مرتبط بمصدرك', editorTitle: 'ماذا يحتاج النبات للبناء الضوئي؟',
  editorOptions: ['ضوء الشمس والماء وثاني أكسيد الكربون', 'التربة فقط', 'الأكسجين فقط', 'الحرارة فقط'],
  editorNote: 'راجع، عدّل، ثم انشر.', liveTitle: 'مكان للجميع في التحدي.',
  liveBody: 'صف واحد. رمز واحد. وفرصة لنتعلّم معًا.', liveCode: 'رمز توضيحي للعبة', liveFooter: 'لعب مباشر · واجبات · تعلّم ذاتي',
  typesTitle: 'أكثر من طريقة للفهم.',
  typesBody: 'اختر التفاعل الذي يناسب الفكرة. الفهم أوسع من اختيار إجابة واحدة.',
  types: ['اختيار من متعدد', 'صح أم خطأ', 'ترتيب', 'سحب وإفلات', 'صور تفاعلية'],
  rolesTitle: 'الأسئلة الجيدة تجمعنا.',
  teacherTitle: 'مادتك. وانتباههم معك.',
  teacherBody: 'ابنِ أنشطة من محتواك التعليمي. أضف تحديًا مباشرًا، وكلّف طلابك بالواجبات، وتابع تقدّم كل متعلّم.',
  teacherAction: 'ابدأ التدريس', studentTitle: 'اكتشف لحظة «فهمتها!»',
  studentBody: 'انضم إلى صفّك، وتدرّب بالوتيرة التي تناسبك، واجعل كل إجابة خطوة جديدة إلى الأمام.',
  studentAction: 'ابدأ التعلّم', photoAlt: 'متعلّم يرتدي سماعات ويدرس باستخدام حاسوب محمول',
  teacherArtTitle: 'افتح باب الاكتشاف.', teacherArtBody: 'أنشئ. العب. افهم.',
  plansAction: 'ابدأ الآن', plansContact: 'تحدّث معنا',
}
