export const experienceEn = {
  title: 'Upload what you teach.', titleAccent: 'Turn it into a quiz.',
  intro: 'Upload a lesson, generate questions from it, review them, then run it live with your students or assign it as homework and see what needs review.',
  create: 'Create a quiz from your lesson', try: 'Try a quick quiz',
  note: 'Your material. Your questions. Your classroom.', games: 'Asasera adventures',
  teacher: 'For teachers', student: 'For students',
  demo: 'Try it yourself', demoNote: '3-question demo · No account needed',
  shuffle: 'New questions', imageLabel: 'AI-generated image', imageUnavailable: 'Photo unavailable',
  question: 'Question', of: 'of', choose: 'Pick an answer. Let’s see what you know!',
  correct: 'You’ve got it!', incorrect: 'A little discovery!', correctAnswer: 'Correct answer:',
  next: 'Next question', results: 'See my result', replay: 'Try another round',
  complete: 'That’s the joy of learning.', resultBody: 'Bring this energy to your next lesson.',
  scoreLabel: 'Your demo score', correctCount: 'correct answers',
  joinTitle: 'Class is starting?', joinBody: 'Enter the six-digit PIN from your teacher and jump in.',
  joinPlaceholder: 'Game PIN', join: 'Join the session',
  joinEmpty: 'Enter the PIN shown on your teacher’s screen.', joinShort: 'Enter all six digits of your PIN.',
  ribbon: ['Upload your lesson', 'Generate questions', 'Run it live or assign it', 'See what needs review'],
  howTitle: 'From your lesson to their next “aha!”',
  howBody: 'Four steps, and you stay in control of every question before students see it.',
  steps: [
    { title: 'Upload what you teach', body: 'Upload a PDF, slides or a document, or paste text. Pick the pages or section the quiz should cover.', action: 'Upload your lesson' },
    { title: 'Generate and review questions', body: 'Get multiple-choice and true/false questions grounded in your pages, with the source shown. Edit, delete or regenerate, then approve.', action: 'Create a quiz from your lesson' },
    { title: 'Run it live or assign homework', body: 'Start a live session students join with a PIN, or assign it as homework. See who struggled where, then create a short follow-up practice.', action: 'Run your first session' },
  ],
  workflow: 'Explore the workflow', example: 'Example preview',
  source: 'Your course material', sourceFile: 'Biology · Plant life.pdf', sourcePage: 'Page 12',
  sourceHeading: 'How plants make food', sourceText: 'Plants use sunlight, water and carbon dioxide to produce glucose and release oxygen.',
  sourceSelection: 'Start with the pages you want to teach.',
  sourceLink: 'Linked to your source', editorTitle: 'What do plants need for photosynthesis?',
  editorOptions: ['Sunlight, water and CO₂', 'Only soil', 'Only oxygen', 'Only heat'],
  editorNote: 'Review, edit, then approve.', liveTitle: 'Everyone has a way in.',
  liveBody: 'One classroom. One PIN. Ready to learn together.', liveCode: 'Example game PIN', liveFooter: 'Live session · Homework · See what needs review',
  typesTitle: 'Two question types that do the work.',
  typesBody: 'Multiple choice and true/false cover most of what a lesson needs to check, and every question stays linked to the page it came from.',
  types: ['Multiple choice', 'True or false'],
  typesAlso: 'Also supported: ordering, drag and drop, interactive images.',
  rolesTitle: 'Good questions bring us together.',
  teacherTitle: 'Your subject. Their attention.',
  teacherBody: 'Build quizzes from your own teaching material. Run a live session, assign homework, and see what each learner needs to review.',
  teacherAction: 'Start teaching', studentTitle: 'Find your next “I get it.”',
  studentBody: 'Join your class, practice at your pace, and turn every answer into another step forward.',
  studentAction: 'Start learning', photoAlt: 'A learner wearing headphones while studying on a laptop',
  teacherArtTitle: 'Make room for discovery.', teacherArtBody: 'Upload. Review. Teach.',
  pricingTitle: 'Free during the pilot.',
  pricingBody: 'Asasera is free for teachers and students while we pilot it. AI question generation comes with a small trial credit for each teacher; running saved quizzes, homework and reports never uses it.',
  pricingStudents: 'Students never pay.',
  pricingContact: 'Questions? Talk to us',
}

export const experienceAr: typeof experienceEn = {
  title: 'ارفع ما تدرّسه.', titleAccent: 'حوّله إلى اختبار.',
  intro: 'ارفع درسك، ولّد أسئلة منه، راجعها، ثم شغّلها مباشرة مع طلابك أو كلّفهم بها كواجب، واكتشف ما يحتاج إلى مراجعة.',
  create: 'أنشئ اختبارًا من درسك', try: 'جرّب تحديًا سريعًا',
  note: 'محتواك. أسئلتك. صفّك.', games: 'مغامرات أساسيرا',
  teacher: 'للمعلّمين', student: 'للطلاب',
  demo: 'جرّب بنفسك', demoNote: '3 أسئلة تجريبية · دون حساب',
  shuffle: 'أسئلة جديدة', imageLabel: 'صورة مولّدة بالذكاء الاصطناعي', imageUnavailable: 'الصورة غير متاحة',
  question: 'السؤال', of: 'من', choose: 'اختر إجابة. لنكتشف ما تعرفه!',
  correct: 'أحسنت، إجابة صحيحة!', incorrect: 'معلومة جديدة لك!', correctAnswer: 'الإجابة الصحيحة:',
  next: 'السؤال التالي', results: 'اعرض نتيجتي', replay: 'جرّب جولة جديدة',
  complete: 'هذه متعة التعلّم.', resultBody: 'انقل هذا الحماس إلى درسك القادم.',
  scoreLabel: 'نتيجتك في التجربة', correctCount: 'إجابات صحيحة',
  joinTitle: 'بدأت الحصة؟', joinBody: 'أدخل رمز الحصة المكوّن من ستة أرقام وانضم.',
  joinPlaceholder: 'رمز الحصة', join: 'انضم إلى الحصة',
  joinEmpty: 'أدخل الرمز الظاهر على شاشة المعلّم.', joinShort: 'أكمل الرمز المكوّن من ستة أرقام.',
  ribbon: ['ارفع درسك', 'ولّد الأسئلة', 'شغّلها مباشرة أو كواجب', 'اكتشف ما يحتاج مراجعة'],
  howTitle: 'من درسك إلى لحظة «الآن فهمت!»',
  howBody: 'أربع خطوات، وأنت تراجع كل سؤال قبل أن يراه طلابك.',
  steps: [
    { title: 'ارفع ما تدرّسه', body: 'ارفع ملف PDF أو عرضًا أو مستندًا، أو الصق نصًا. ثم اختر الصفحات أو الجزء الذي يغطيه الاختبار.', action: 'ارفع درسك' },
    { title: 'ولّد الأسئلة وراجعها', body: 'احصل على أسئلة اختيار من متعدد وصح أم خطأ مبنية على صفحاتك مع عرض المصدر. عدّل أو احذف أو أعد التوليد، ثم اعتمد.', action: 'أنشئ اختبارًا من درسك' },
    { title: 'شغّله مباشرة أو كلّف به كواجب', body: 'ابدأ جلسة مباشرة ينضم إليها الطلاب برمز، أو كلّفهم بها كواجب. اعرف من واجه صعوبة وأين، ثم أنشئ تدريبًا قصيرًا للمتابعة.', action: 'شغّل جلستك الأولى' },
  ],
  workflow: 'اكتشف خطوات العمل', example: 'معاينة توضيحية',
  source: 'محتوى مقرّرك', sourceFile: 'الأحياء · حياة النبات.pdf', sourcePage: 'صفحة 12',
  sourceHeading: 'كيف يصنع النبات غذاءه', sourceText: 'يستخدم النبات ضوء الشمس والماء وثاني أكسيد الكربون لإنتاج الجلوكوز وإطلاق الأكسجين.',
  sourceSelection: 'ابدأ بالصفحات التي تريد تدريسها.',
  sourceLink: 'مرتبط بمصدرك', editorTitle: 'ماذا يحتاج النبات للبناء الضوئي؟',
  editorOptions: ['ضوء الشمس والماء وثاني أكسيد الكربون', 'التربة فقط', 'الأكسجين فقط', 'الحرارة فقط'],
  editorNote: 'راجع، عدّل، ثم اعتمد.', liveTitle: 'مكان للجميع في الحصة.',
  liveBody: 'صف واحد. رمز واحد. وفرصة لنتعلّم معًا.', liveCode: 'رمز توضيحي للحصة', liveFooter: 'جلسة مباشرة · واجبات · ما يحتاج مراجعة',
  typesTitle: 'نوعان من الأسئلة يقومان بالمهمة.',
  typesBody: 'الاختيار من متعدد وصح أم خطأ يغطيان أغلب ما يحتاج الدرس إلى التحقق منه، ويبقى كل سؤال مرتبطًا بالصفحة التي جاء منها.',
  types: ['اختيار من متعدد', 'صح أم خطأ'],
  typesAlso: 'مدعوم أيضًا: الترتيب، والسحب والإفلات، والصور التفاعلية.',
  rolesTitle: 'الأسئلة الجيدة تجمعنا.',
  teacherTitle: 'مادتك. وانتباههم معك.',
  teacherBody: 'ابنِ اختباراتك من محتواك التعليمي. شغّل جلسة مباشرة، وكلّف طلابك بالواجبات، واعرف ما يحتاج كل متعلّم إلى مراجعته.',
  teacherAction: 'ابدأ التدريس', studentTitle: 'اكتشف لحظة «فهمتها!»',
  studentBody: 'انضم إلى صفّك، وتدرّب بالوتيرة التي تناسبك، واجعل كل إجابة خطوة جديدة إلى الأمام.',
  studentAction: 'ابدأ التعلّم', photoAlt: 'متعلّم يرتدي سماعات ويدرس باستخدام حاسوب محمول',
  teacherArtTitle: 'افتح باب الاكتشاف.', teacherArtBody: 'ارفع. راجع. درّس.',
  pricingTitle: 'مجاني خلال الفترة التجريبية.',
  pricingBody: 'أساسيرا مجاني للمعلّمين والطلاب خلال الفترة التجريبية. يشمل توليد الأسئلة بالذكاء الاصطناعي رصيدًا تجريبيًا صغيرًا لكل معلّم، أما تشغيل الاختبارات المحفوظة والواجبات والتقارير فلا يستهلك منه شيئًا.',
  pricingStudents: 'الطالب لا يدفع أبدًا.',
  pricingContact: 'لديك سؤال؟ تحدّث معنا',
}
