import {useEffect,useState} from 'react'
import {Check,Clock3,LockKeyhole,SkipForward,Star} from 'lucide-react'
import {Button,Field,Select} from '@/design'
import type {LivePresentationView,LivePresentationCommand} from '@/shared/live-presentation'
import type {SessionSnapshot,SessionState} from '@/shared/session'
import {wheelIsSpinning} from '@/shared/wheel'
import {WheelDisc} from '../wheel/RandomWheel'
import {useActivityMotion} from '../activity-themes/useActivityMotion'
import styles from './LivePresentationControls.module.css'

type Props={state:LivePresentationView;phase:SessionState;host:boolean;ar:boolean;disabled:boolean;participants:SessionSnapshot['participants'];clock:{now:()=>number};onCommand:(command:LivePresentationCommand)=>Promise<unknown>}
export function LivePresentationControls({state,phase,host,ar,disabled,participants,clock,onCommand}:Props){
 const t=(a:string,e:string)=>ar?a:e,motion=useActivityMotion()
 const [page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(clock.now())
 const active=state.active,selected=active?.status==='selected',open=active?.status==='open',available=!selected&&!open&&['lobby','revealing','podium'].includes(phase)
 const spinning=!!state.wheel&&wheelIsSpinning(state.wheel,now),locked=disabled||busy||spinning
 const completed=state.items.every(item=>item.status==='completed'||item.status==='skipped')
 const collective=['flashcards','speaking-cards','memory'].includes(state.selection.definitionId)||['discussion','self-rated'].includes(state.selection.config.semantics)
 const pages=Math.ceil(state.items.length/12),number=active?state.items.find(item=>item.questionId===active.questionId)?.number:null
 useEffect(()=>{if(!state.wheel?.spin)return;const timer=setInterval(()=>{setNow(clock.now());if(!wheelIsSpinning(state.wheel!,clock.now()))clearInterval(timer)},80);return()=>clearInterval(timer)},[state.wheel,clock])
 async function command(input:LivePresentationCommand){if(locked)return;setBusy(true);setError('');try{await onCommand(input)}catch(error){setError(error instanceof Error?error.message:t('تعذّر حفظ العملية. أعد المحاولة.','Could not save the action. Retry.'))}finally{setBusy(false)}}
 const title=state.selection.definitionId==='open-box'?t('افتح الصندوق','Open the box'):state.selection.definitionId==='question-wheel'?t('اختر سؤالًا','Pick a question'):state.selection.definitionId==='class-competition'?t('مسابقة الصف','Class competition'):state.selection.definitionId==='memory'?t('لعبة الذاكرة','Memory'):state.selection.definitionId==='flashcards'?t('بطاقات المراجعة','Flashcards'):state.selection.definitionId==='speaking-cards'?t('بطاقات النقاش','Speaking cards'):t('بطاقات الأسئلة','Question cards')
 const status=(value:string)=>value==='closed'?t('مغلق','Closed'):value==='selected'?t('محدد','Selected'):value==='open'?t('جارٍ الإجابة','Answering'):value==='completed'?t('مكتمل','Completed'):t('متجاوز','Skipped')
 return <section className={styles.panel} aria-label={title} dir={ar?'rtl':'ltr'}>
  <header className={styles.heading}><h2>{title}</h2><p>{t(`الجولة ${state.pass} · ${state.items.filter(item=>item.status==='closed').length} متبقٍ`,`Pass ${state.pass} · ${state.items.filter(item=>item.status==='closed').length} remaining`)}</p></header>
  {state.selection.config.semantics!=='scored'&&<p className={styles.note}>{state.selection.config.semantics==='practice'?t('هذا تدريب، وليس درجة تقييم','This is practice, not a grade'):t('نقاش ومراجعة، وليس تقييمًا فرديًا','Discussion and review, not individual assessment')}</p>}
  {available&&state.selection.definitionId==='open-box'&&<><ol className={styles.boxes}>{state.items.slice(page*12,page*12+12).map(item=><li key={item.elementId}>{host?<button type="button" className={styles.box} data-status={item.status} aria-label={t(`افتح الصندوق ${item.number}`,`Open box ${item.number}`)} disabled={locked||item.status!=='closed'} onClick={()=>void command({action:'select-box',elementId:item.elementId})}><strong>{item.number}</strong><span>{item.status==='completed'?<Check size={18}/>:item.status==='skipped'?<SkipForward size={18}/>:<LockKeyhole size={18}/>} {status(item.status)}</span></button>:<div className={styles.box} data-status={item.status}><strong>{item.number}</strong><span>{status(item.status)}</span></div>}</li>)}</ol>{pages>1&&<nav className={styles.actions} aria-label={t('صفحات الصناديق','Box pages')}><Button variant="secondary" disabled={page===0} onClick={()=>setPage(page-1)}>{t('السابق','Previous')}</Button><span>{page+1} / {pages}</span><Button variant="secondary" disabled={page+1>=pages} onClick={()=>setPage(page+1)}>{t('التالي','Next')}</Button></nav>}</>}
  {selected&&<div className={styles.selection}>
   {state.wheel?.spin&&<div className={styles.wheel} aria-hidden="true"><WheelDisc entries={state.wheel.spin.entries} spin={state.wheel.spin} clock={clock} animate={motion.enabled}/><svg className={styles.pointer} viewBox="0 0 36 44"><path d="M3 3H33L18 39Z" fill="currentColor"/></svg></div>}
   <h3>{t(`السؤال ${number}`,`Question ${number}`)}</h3><p>{spinning?t('تستقر العجلة…','The wheel is settling…'):host?t('السؤال جاهز. يبدأ وقت الإجابة عندما تضغط ابدأ.','The question is ready. The answer window starts when you press Begin.'):t('انتظر بدء السؤال من المعلّم.','Wait for your teacher to begin the question.')}</p>
  </div>}
  {selected&&active?.challenge&&<p className={styles.note}><Star size={20} aria-hidden="true"/>{t('سؤال تحدٍّ','Challenge question')}</p>}
  {selected&&!!active?.bonusPoints&&<p className={styles.note}>{t(`الإجابة الصحيحة: ${state.rules.baseGamePoints} + ${active.bonusPoints} نقطة لعب. لا تغير درجة التعلّم.`,`Correct response: ${state.rules.baseGamePoints} + ${active.bonusPoints} game points. Learning marks are unchanged.`)}</p>}
  {active?.thinkingAdded&&<p className={styles.note}><Clock3 size={18}/>{t('أضيفت 15 ثانية للجميع','15 seconds added for everyone')}</p>}
  {host&&<div className={styles.actions}>
   {selected&&<><Button disabled={locked} onClick={()=>void command({action:'begin'})}>{t('ابدأ السؤال','Begin question')}</Button><Button variant="secondary" disabled={locked} onClick={()=>void command({action:'skip'})}>{t('تجاوز الآن','Pass for now')}</Button></>}
   {available&&!completed&&state.selection.definitionId!=='open-box'&&<Button disabled={locked} onClick={()=>void command({action:'draw',animate:motion.enabled})}>{state.selection.definitionId==='question-wheel'?t('اختر سؤالًا','Pick a question'):t('اسحب بطاقة','Draw a card')}</Button>}
   {available&&completed&&<Button disabled={locked||state.pass>=10} onClick={()=>void command({action:'next-pass'})}>{t('ابدأ جولة مراجعة جديدة','Start a new review pass')}</Button>}
   {open&&active.hintAvailable&&!active.hint&&<Button variant="secondary" disabled={locked} onClick={()=>void command({action:'hint'})}>{t('أظهر تلميحًا','Show hint')}</Button>}
   {open&&state.rules.thinkTogether&&active.endsAt!==null&&!active.thinkingAdded&&<Button variant="secondary" disabled={locked} onClick={()=>void command({action:'think-together'})}>{t('فكّروا معًا · 15 ثانية','Think together · 15 seconds')}</Button>}
  </div>}
  {state.teamStandings.length>0&&<section className={styles.standings}><h3>{t('نقاط الفرق في الجولة','Team game points this round')}</h3><ol>{state.teamStandings.map(team=><li key={team.id}><span>{team.rank}. <bdi>{team.name}</bdi>{team.tied&&t(' · تعادل',' · tied')}</span><strong>{team.points}</strong></li>)}</ol><p>{t('متوسط نقاط الأعضاء عند بدء السؤال، بمن فيهم من لم يجب.','Average per member when the question began, including unanswered members.')}</p></section>}
  <details className={styles.rules}><summary>{t('قواعد هذه الحصة','Class rules')}</summary><p>{state.rules.timing==='host-paced'?state.selection.definitionId==='memory'?t('اقلب البطاقات حتى تكتمل الأزواج، دون مؤقت.','Turn the cards until every pair is found; no timer.'):t('المعلّم يغلق وقت الإجابة، دون مؤقت.','The host closes the answer window; no timer.'):t('يبدأ المؤقت عند بدء السؤال فقط.','The timer starts only when the question begins.')}</p>{collective?<p>{t('نشاط جماعي؛ لا تُسجّل إجابات فردية أو نقاط لعب.','A shared activity; individual answers and game points are not recorded.')}</p>:<><p>{state.rules.speedWeighting?t('نقاط السرعة مفعّلة لهذه الحصة.','Speed scoring is enabled for this class.'):t('الدقة أولًا؛ لا مكافأة للسرعة.','Accuracy first; no speed bonus.')}</p><p>{t(`${state.rules.baseGamePoints} نقطة لعب للإجابة الصحيحة؛ الدعم متاح للجميع بالتساوي.`,`${state.rules.baseGamePoints} game points for a correct response; support is equally available.`)}</p></>}{state.rules.extraPracticeAttempt&&<p>{t('محاولة تدريب إضافية واحدة، مع الاحتفاظ بالإجابة الأولى.','One extra practice attempt; the first response is preserved.')}</p>}</details>
  {host&&available&&!collective&&<TeamEditor key={JSON.stringify(state.teamAssignments)} teams={state.teamAssignments??[]} participants={participants} ar={ar} disabled={locked} onSave={teams=>command({action:'teams',teams})}/>}
  {error&&<p role="alert">{error}</p>}
 </section>
}
function TeamEditor({teams,participants,ar,disabled,onSave}:{teams:NonNullable<LivePresentationView['teamAssignments']>;participants:SessionSnapshot['participants'];ar:boolean;disabled:boolean;onSave:(teams:NonNullable<LivePresentationView['teamAssignments']>)=>Promise<void>}){
 const [draft,setDraft]=useState(teams.length?teams:[{id:crypto.randomUUID(),name:'',participantIds:[]},{id:crypto.randomUUID(),name:'',participantIds:[]}]),t=(a:string,e:string)=>ar?a:e
 return <details className={styles.rules}><summary>{t('إعداد الفرق','Set up teams')}</summary><form onSubmit={event=>{event.preventDefault();void onSave(draft)}}>
  <p>{t('من فريقين إلى ستة؛ يجيب كل طالب بنفسه. تُثبّت العضوية عند بدء السؤال.','Two to six teams; each learner answers independently. Membership freezes when the question begins.')}</p>
  <div className={styles.teamNames}>{draft.map((team,index)=><Field key={team.id} label={t(`اسم الفريق ${index+1}`,`Team ${index+1} name`)} maxLength={40} required value={team.name} disabled={disabled} onChange={event=>setDraft(draft.map(item=>item.id===team.id?{...item,name:event.target.value}:item))}/>)}</div>
  <div className={styles.assignments}>{participants.map(participant=><label key={participant.id}><bdi>{participant.name}</bdi><Select aria-label={t(`فريق ${participant.name}`,`Team for ${participant.name}`)} value={draft.find(team=>team.participantIds.includes(participant.id))?.id??''} disabled={disabled} onValueChange={id=>setDraft(draft.map(team=>({...team,participantIds:team.id===id?[...team.participantIds.filter(value=>value!==participant.id),participant.id]:team.participantIds.filter(value=>value!==participant.id)})))}><option value="">{t('دون فريق','No team')}</option>{draft.map((team,index)=><option key={team.id} value={team.id}>{team.name||t(`الفريق ${index+1}`,`Team ${index+1}`)}</option>)}</Select></label>)}</div>
  <div className={styles.actions}><Button type="submit" disabled={disabled}>{t('احفظ الفرق','Save teams')}</Button><Button variant="secondary" disabled={disabled||draft.length>=6} onClick={()=>setDraft([...draft,{id:crypto.randomUUID(),name:'',participantIds:[]}])}>{t('أضف فريقًا','Add team')}</Button>{teams.length>0&&<Button variant="secondary" disabled={disabled} onClick={()=>void onSave([])}>{t('المتابعة دون فرق','Continue without teams')}</Button>}</div>
 </form></details>
}
