import {selectOption} from './select-option'
import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {localTeacher} from './local-fixture'
test('existing live-provider results open citations and image proposals without a new paid request',async({page})=>{
 const fixture=JSON.parse(readFileSync('/tmp/asasera-evaluation-browser-access.json','utf8'))
 await page.addInitScript(()=>localStorage.setItem('asasera.language','en'))
 const login=await page.request.post('/api/v1/auth/login',{data:{email:fixture.email,password:fixture.password}});expect(login.ok()).toBe(true)
 let submissions=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/activity-generation/jobs'))submissions++})
 await page.setViewportSize({width:1440,height:900});await page.goto(`/teacher/activities/${fixture.activityId}`)
 await page.getByRole('button',{name:'Generate',exact:true}).click();await expect(page.getByRole('dialog',{name:'Prepare with AI',exact:true})).toBeVisible()
 await selectOption(page.getByRole('combobox',{name:'Previous jobs',exact:true}),'306')
 await expect(page.getByRole('button',{name:'Open source 1'}).first()).toBeVisible();await page.getByRole('button',{name:'Open source 1'}).first().click()
 await expect(page.getByRole('heading',{name:'Source 1',exact:true})).toBeVisible();await expect(page.locator('section[class*=sourceText] p')).not.toBeEmpty()
 await page.locator('section[class*=sourceText]').evaluate(el=>el.scrollIntoView({block:'center'}))
 await page.screenshot({path:'../screenshots/v4/generation-source-1440.png',fullPage:true})
 await selectOption(page.getByRole('combobox',{name:'Previous jobs',exact:true}),'307');await expect(page.getByAltText('Proposed image regions')).toBeVisible()
 await page.setViewportSize({width:390,height:844});await expect(page.locator('dialog')).toHaveJSProperty('scrollWidth',await page.locator('dialog').evaluate(el=>el.clientWidth))
 await page.screenshot({path:'../screenshots/v4/generation-zones-390.png',fullPage:true})
 await selectOption(page.getByRole('combobox',{name:'Previous jobs',exact:true}),'308');await expect(page.getByRole('status')).toContainText('Reserved credit was released')
 expect(submissions).toBe(0)
})
test('account deletion requires password confirmation, revokes access and clears shared-device state',async({page})=>{
 const fixture=localTeacher();await page.addInitScript(()=>{localStorage.setItem('asasera.language','en');localStorage.setItem('asasera:synthetic-private-key','synthetic')})
 const login=await page.request.post('/api/v1/auth/login',{data:{email:fixture.email,password:fixture.password}});expect(login.ok()).toBe(true);const {accessToken}=await login.json()
 await page.setViewportSize({width:390,height:844});await page.goto('/complete-profile');await page.getByRole('button',{name:'Delete account',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Delete your account?',exact:true});await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Delete my account',exact:true})).toBeDisabled()
 await dialog.getByRole('checkbox').check();await dialog.getByLabel('Current password, if your account uses one').fill('wrong password');await dialog.getByRole('button',{name:'Delete my account',exact:true}).click();await expect(dialog.getByRole('alert')).toBeVisible()
 await dialog.getByLabel('Current password, if your account uses one').fill(fixture.password)
 await expect(dialog.getByRole('button',{name:'Delete my account',exact:true})).toBeEnabled();await page.mouse.move(380,830);await page.waitForTimeout(250)
 await page.screenshot({path:'../screenshots/v4/account-deletion-390.png',fullPage:true,animations:'disabled'})
 await dialog.getByRole('button',{name:'Delete my account',exact:true}).click();await expect(dialog).not.toBeVisible()
 expect((await page.request.get('/api/v1/auth/me',{headers:{authorization:`Bearer ${accessToken}`}})).status()).toBe(401)
 expect(await page.evaluate(()=>localStorage.getItem('asasera:synthetic-private-key'))).toBeNull()
})
