import {test,expect} from '@playwright/test'
import {readFileSync,appendFileSync} from 'node:fs'
import {randomUUID} from 'node:crypto'
const state=process.env.PW_JOURNEY_STATE?JSON.parse(readFileSync(process.env.PW_JOURNEY_STATE,'utf8')):null
test.skip(!state,'Requires the isolated local SMTP account journey and its published activity')
test.use({baseURL:state?.web??'http://127.0.0.1:5201',actionTimeout:10_000})

test('a newly published activity reaches a signed-in student through live play, homework and self-study',async({page,browser})=>{
 test.setTimeout(100_000)
 const teacher=JSON.parse(readFileSync(`${state.directory}/teacher.json`,'utf8'))
 await page.addInitScript(()=>localStorage.setItem('asasera.language','en'))
 const signed=await page.request.post('/api/v1/auth/login',{data:{email:teacher.email,password:teacher.password}})
 expect(signed.ok()).toBe(true)
 const {accessToken}=await signed.json(),headers={authorization:`Bearer ${accessToken}`}
 await page.goto(`/teacher/activities/${teacher.activityId}`)
 await page.getByRole('button',{name:'Play',exact:true}).click()
 await page.getByRole('button',{name:'Start live game',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Let’s play together',exact:true})).toBeVisible()
 const pin=(await page.locator('strong[class*="pin"]').innerText()).trim()
 const runId=Number(new URL(page.url()).pathname.split('/').at(-1))
 const context=await browser.newContext({baseURL:state.web,viewport:{width:390,height:844}})
 const learner=await context.newPage()
 try{
  await learner.addInitScript(()=>localStorage.setItem('asasera.language','en'))
  const email=`learner-${randomUUID()}@example.test`,password='Complete student journey 2026'
  await learner.goto('/signup/student')
  await learner.locator('.tile-grid button').first().click()
  await learner.getByLabel('Email address',{exact:true}).fill(email)
  await learner.getByRole('button',{name:'Continue',exact:true}).click()
  await learner.getByLabel('Password',{exact:true}).fill(password)
  const login=learner.waitForResponse(r=>r.url().endsWith('/api/v1/auth/login')&&r.request().method()==='POST')
  await learner.getByRole('button',{name:'Create account',exact:true}).click()
  const session=await(await login).json()
  appendFileSync(`${state.directory}/owned-users.jsonl`,JSON.stringify({id:session.user.id,role:'student',database:state.database})+'\n',{mode:0o600})
  await expect(learner.getByLabel('Game PIN',{exact:true})).toBeVisible()
  await learner.getByLabel('Game PIN',{exact:true}).fill(pin.replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[Number(d)]!))
  await learner.getByRole('button',{name:'Join',exact:true}).click()
  await learner.getByLabel('Display name',{exact:true}).fill('Synthetic student')
  await learner.getByRole('button',{name:'Join class',exact:true}).click()
  await expect(learner.getByText('You are in. Wait for your teacher to start.',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Start class',exact:true}).click()
  await expect(learner.getByRole('heading',{name:'Choose your answer',exact:true})).toBeVisible()
  await learner.getByRole('button',{name:'triangle: Four',exact:true}).click()
  await expect(learner.getByRole('heading',{name:'Answer accepted',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Lock and reveal',exact:true}).click()
  await expect(learner.getByRole('heading',{name:/Correct answer/})).toBeVisible()
  await page.getByRole('button',{name:'Show podium',exact:true}).click()
  await expect(learner.getByRole('heading',{name:'Well played, everyone',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Finish class',exact:true}).click()
  await expect(learner.getByRole('heading',{name:'Class finished',exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Open class report',exact:true}).click()
  await expect(page.getByRole('rowheader',{name:'Synthetic student Participated',exact:true})).toBeVisible()
  const liveReport=await(await page.request.get(`/api/v1/reports/runs/${runId}`,{headers})).json()
  expect(liveReport.participants[0].correctCount).toBe(1)
  expect(liveReport.questions[0].distribution[0].label).toBe('Four')
  await expect(page.getByText('Four:',{exact:false})).toBeVisible()
  await expect(page.getByText('opt_a:',{exact:false})).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('rowheader',{name:'Synthetic student Participated',exact:true})).toBeVisible()
  await page.evaluate(()=>document.fonts.ready)
  await page.screenshot({path:'.impeccable/review/journeys/teacher-report-desktop-en.png',fullPage:true,animations:'disabled'})
  for(const mode of ['Assign homework','Self-study']){
   await page.goto(`/teacher/activities/${teacher.activityId}/play`)
   await page.getByRole('radio',{name:new RegExp(mode)}).check()
   await page.getByRole('button',{name:'Create assignment link',exact:true}).click()
   const link=await page.getByLabel('Assignment link',{exact:true}).inputValue()
   const assignmentId=new URL(link).pathname.split('/').at(-1)!
   await learner.goto('/student')
   await learner.getByLabel('Activity link',{exact:true}).fill(link)
   await learner.getByRole('button',{name:'Open activity',exact:true}).click()
   await learner.getByLabel('Your name',{exact:true}).fill('Synthetic student')
   await learner.getByRole('button',{name:'Start',exact:true}).click()
   await expect(learner.getByRole('heading',{name:'What is two plus two?',exact:true})).toBeVisible()
   await learner.getByRole('button',{name:'Four',exact:true}).click()
   await learner.reload()
   await learner.getByRole('button',{name:'Submit activity',exact:true}).click()
   await expect(learner.getByRole('heading',{name:'Activity submitted!',exact:true})).toBeVisible()
   if(mode==='Assign homework'){
    await expect(learner.getByText('1 correct out of 1',{exact:true})).toHaveCount(0)
    expect((await page.request.post(`/api/v1/delivery/assignments/${assignmentId}/close`,{headers})).ok()).toBe(true)
    await learner.reload()
   }
   await expect(learner.getByText('1 correct out of 1',{exact:true})).toBeVisible()
  }
 }finally{await context.close()}
})
