import { test, expect } from '@playwright/test'

for (const language of ['en', 'ar'] as const) {
  test(`instructor saves, reviews and approves authored word boards ${language}`, async ({ page, request }) => {
    const origin = process.env.PW_BASE_URL ?? 'http://127.0.0.1:5411'
    expect(new URL(origin).hostname).toMatch(/^(127\.0\.0\.1|localhost)$/)
    const ar = language === 'ar', email = `wordboard-${crypto.randomUUID()}@example.com`, password = crypto.randomUUID() + 'Aa1!'
    expect((await request.post('/api/v1/auth/register/teacher', { data: { name: 'Synthetic board instructor', email, password } })).ok()).toBe(true)
    const login = await request.post('/api/v1/auth/login', { data: { email, password } })
    expect(login.ok()).toBe(true)
    const headers = { Authorization: `Bearer ${(await login.json()).accessToken}` }
    const create = await request.post('/api/v1/activities', { headers, data: { title: ar ? 'لوحات كلمات تجريبية' : 'Synthetic word-board review', subjectId: 1, levelId: 8, purposeId: 2 } })
    expect(create.ok()).toBe(true)
    const { activity } = await create.json()
    const source = await request.post(`/api/v1/activities/${activity.id}/questions`, { headers, data: { kind: 'vocabulary', prompt: ar ? 'اعثر على الكلمات التي راجعناها.' : 'Find the words we reviewed.', payload: { schemaVersion: 1, policy: { version: 1, language, diacritics: 'preserve', tatweel: 'preserve', case: 'preserve', spaces: 'preserve' }, entries: [{ id: 'a', word: ar ? 'بيت' : 'cat', clue: ar ? 'مكان للسكن' : 'A feline' }, { id: 'b', word: ar ? 'نور' : 'dog', clue: ar ? 'ضوء' : 'A canine' }] } } })
    expect(source.ok()).toBe(true)
    await page.context().addCookies((await request.storageState()).cookies)
    await page.addInitScript(lang => localStorage.setItem('asasera.language', lang), language)
    await page.setViewportSize(ar ? { width: 390, height: 844 } : { width: 1440, height: 900 })
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.goto(`/teacher/activities/${activity.id}`)
    await page.getByText(ar ? 'لوحات الكلمات' : 'Word boards', { exact: true }).click()
    const generate = page.getByRole('button', { name: ar ? 'أنشئ اللوحة واحفظها' : 'Generate and save board', exact: true })
    await generate.click()
    await expect(page.getByText(ar ? 'وُضعت كل الكلمات. راجع اللوحة ثم اعتمد النشاط من زر الاعتماد المعتاد.' : 'All words placed. Review the board, then use the existing activity approval button.', { exact: true })).toBeVisible()
    await page.getByRole('combobox', { name: ar ? 'نوع اللوحة' : 'Board type' }).click()
    await page.getByRole('option', { name: ar ? 'الكلمات المتقاطعة' : 'Crossword', exact: true }).click()
    await generate.click()
    await expect(page.getByText(ar ? 'كلمات لم توضع' : 'Unplaced words', { exact: true })).toBeVisible()
    const approval = page.getByRole('button', { name: ar ? 'اعتماد النسخة' : 'Approve version', exact: true })
    const rejected = page.waitForResponse(response => response.url().endsWith(`/activities/${activity.id}/publish`))
    await approval.click()
    expect((await rejected).status()).toBe(422)
    await page.getByRole('textbox', { name: ar ? 'الكلمة 2' : 'Word 2', exact: true }).fill(ar ? 'تين' : 'tap')
    await expect(page.getByRole('table', { name: ar ? 'معاينة اللوحة المحفوظة' : 'Saved board preview' })).toHaveCount(0)
    await page.getByRole('textbox', { name: ar ? 'التلميح 2' : 'Clue 2', exact: true }).fill(ar ? 'فاكهة' : 'A light touch')
    await generate.click()
    await expect(page.getByText(ar ? 'وُضعت كل الكلمات. راجع اللوحة ثم اعتمد النشاط من زر الاعتماد المعتاد.' : 'All words placed. Review the board, then use the existing activity approval button.', { exact: true })).toBeVisible()
    await page.reload()
    await page.getByText(ar ? 'لوحات الكلمات' : 'Word boards', { exact: true }).click()
    const preview = page.getByRole('table', { name: ar ? 'معاينة اللوحة المحفوظة' : 'Saved board preview' })
    await expect(preview).toBeVisible()
    await expect(preview).toHaveAttribute('dir', 'ltr')
    await page.getByRole('checkbox', { name: ar ? 'أظهر حل المعلّم' : 'Show instructor solution' }).check()
    await preview.scrollIntoViewIfNeeded()
    await page.evaluate(async () => { await document.fonts.ready })
    await page.screenshot({ path: `../docs/evidence/interactive/word-board-author-${language}.png`, fullPage: true })
    const approved = page.waitForResponse(response => response.url().endsWith(`/activities/${activity.id}/publish`))
    await approval.click()
    expect((await approved).status()).toBe(200)
    await expect(page.getByRole('button', { name: ar ? 'اعتماد التغييرات' : 'Approve changes', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
  })
}
