import {expect,test} from '@playwright/test'
import {isolatedStackOnly,localShapes} from './local-fixture'
test.beforeAll(isolatedStackOnly)
test('completed empty and stale AI suggestions offer a fresh estimate without a paid retry',async({page})=>{
 const fx=localShapes()
 await page.addInitScript(()=>localStorage.setItem('asasera.language','en'))
 const login=await page.request.post('/api/v1/auth/login',{data:{email:fx.email,password:fx.password}});expect(login.ok()).toBeTruthy()
 const token=(await login.json()).accessToken
 const current=(await (await page.request.get(`/api/v1/activities/${fx.activityId}`,{headers:{authorization:`Bearer ${token}`}})).json()).questions[0]
 let stale=false,paid=0,quotes=0
 const quote={quoteId:crypto.randomUUID(),quoteExpiresAt:'2999-01-01',estimateMillicents:10,maxAuthorizedMillicents:20,estimateAiCredits:10,maxAuthorizedAiCredits:20,usableAiCredits:900,creditPolicyVersion:1,creditUnit:'AI Credits',spendableMillicents:900,usableMillicents:900,allowanceMillicents:900,exposureMillicents:0,affordable:true,pricingAvailable:true,generationAvailable:true,grant:{trialMillicents:900,trialAiCredits:900,claimed:true,eligible:true,reason:null},delivery:'new answers'}
 await page.route('**/api/v1/activity-generation/quote',r=>{quotes++;return r.fulfill({json:quote})})
 await page.route('**/api/v1/activity-generation/jobs',r=>{paid++;return r.fulfill({json:{}})})
 await page.route('**/api/v1/activity-generation/jobs/90909',r=>r.fulfill({json:{job:{id:90909,state:'succeeded',imageKey:stale?'old-image.png':fx.imageKey,result:{candidates:stale?[{key:'old',x:.4,y:.4,w:.2,h:.2,shape:'circle',points:null,label:'Old label'}]:[],appliedIndexes:[],nextRevision:current.revision}}}}))
 await page.setViewportSize({width:1440,height:1050});await page.goto(`/teacher/activities/${fx.activityId}`)
 const saveRecovery=()=>page.evaluate(({activityId,questionId})=>sessionStorage.setItem(`asasera:zone-suggestions:${activityId}:${questionId}`,JSON.stringify({jobId:90909,request:{activityId,questionId,task:'zones',expectedRevision:1,objective:'Shape labels',maxAuthorizedMillicents:20,idempotencyKey:crypto.randomUUID()}})),fx)
 await saveRecovery();await page.getByRole('button',{name:'Suggest answers with AI',exact:true}).click()
 await expect(page.getByText(/There are no new usable areas/)).toBeVisible()
 await page.screenshot({path:'.impeccable/review/pin-suggestions-empty.png',fullPage:true})
 await page.getByRole('button',{name:'Get a fresh estimate'}).click();await expect(page.getByRole('button',{name:'Suggest with AI',exact:true})).toBeEnabled();expect(paid).toBe(0);expect(quotes).toBe(1)
 await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click()
 stale=true;await saveRecovery();await page.getByRole('button',{name:'Suggest answers with AI',exact:true}).click()
 await expect(page.getByText(/Old areas are hidden/)).toBeVisible();await expect(page.getByText('Old label',{exact:true})).toHaveCount(0)
 await page.screenshot({path:'.impeccable/review/pin-suggestions-stale.png',fullPage:true})
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.impeccable/review/pin-suggestions-stale-mobile.png',fullPage:true})
 await page.getByRole('button',{name:'Get a fresh estimate'}).click();await expect(page.getByRole('button',{name:'Suggest with AI',exact:true})).toBeEnabled();expect(paid).toBe(0);expect(quotes).toBe(2)
})
test('image workspace: shapes, labels, brush undo, protected AI review and bilingual layout',async({page})=>{
 const fx=localShapes(),errors:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.addInitScript(()=>{if(!localStorage.getItem('asasera.language'))localStorage.setItem('asasera.language','en')})
 const login=await page.request.post('/api/v1/auth/login',{data:{email:fx.email,password:fx.password}});expect(login.ok()).toBeTruthy()
 await page.setViewportSize({width:1440,height:1050})
 await page.goto(`/teacher/activities/${fx.activityId}`)
 const workspace=page.getByRole('region',{name:'Image answer editor'})
 await expect(workspace).toBeVisible({timeout:20000})
 await expect(workspace.locator('img').first()).toBeVisible()
 await expect.poll(()=>workspace.locator('img').first().evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(640)
 await workspace.getByRole('combobox').first().click()
 await page.getByRole('option',{name:'Drag labels',exact:true}).click()
 await workspace.getByRole('textbox',{name:'Answer for area 1',exact:true}).fill('Square')
 await workspace.getByRole('textbox',{name:'Answer for area 2',exact:true}).fill('Circle')
 await workspace.getByRole('textbox',{name:'Answer for area 3',exact:true}).fill('Hexagon')
 await workspace.getByRole('button',{name:'Circle',exact:true}).click()
 const svg=workspace.locator('svg[aria-label="Editable answer areas"]'),box=(await svg.boundingBox())!
 await page.mouse.move(box.x+box.width*.65,box.y+box.height*.65);await page.mouse.down();await page.mouse.move(box.x+box.width*.9,box.y+box.height*.9,{steps:6});await page.mouse.up()
 await expect(workspace.getByRole('textbox',{name:'Answer for area 4',exact:true})).toBeVisible()
 await workspace.getByRole('textbox',{name:'Answer for area 4',exact:true}).fill('Another circle')
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:'.impeccable/review/pin-desktop.png',fullPage:true})
 await workspace.getByRole('button',{name:'Clean image',exact:true}).click()
 const cleanup=page.getByRole('dialog',{name:'Clean image',exact:true}),canvas=cleanup.locator('canvas')
 await expect.poll(()=>canvas.evaluate((c:HTMLCanvasElement)=>c.width)).toBe(640)
 const initial=await canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL())
 const cb=(await canvas.boundingBox())!
 await page.mouse.click(cb.x+cb.width*.2,cb.y+cb.height*.2)
 await expect(cleanup.getByLabel('Brush colour')).toHaveValue('#dfe8f5')
 await cleanup.getByLabel('Brush colour').fill('#112233')
 await page.mouse.move(cb.x+cb.width*.2,cb.y+cb.height*.2);await page.mouse.down();await page.mouse.move(cb.x+cb.width*.4,cb.y+cb.height*.25,{steps:5});await page.mouse.up()
 expect(await canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL())).not.toBe(initial)
 await cleanup.getByRole('button',{name:'Undo',exact:true}).click()
 expect(await canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL())).toBe(initial)
 await cleanup.getByRole('button',{name:'Redo',exact:true}).click()
 expect(await canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL())).not.toBe(initial)
 await page.screenshot({path:'.impeccable/review/pin-cleanup-desktop.png',fullPage:true})
 await cleanup.getByRole('button',{name:'Cancel',exact:true}).click();await cleanup.getByRole('button',{name:'Discard edits',exact:true}).click()
 let submitted=0
 await page.route('**/api/v1/activity-media/creation/quote',r=>r.fulfill({json:{quoteToken:'test-only',model:'test-image-model',estimateAiCredits:40,maxAiCredits:60,affordable:true,expiresAt:new Date(Date.now()+900000).toISOString()}}))
 const resolved=await (await page.request.post('/api/v1/activity-media/resolve',{headers:{authorization:`Bearer ${(await login.json()).accessToken}`},data:{key:fx.imageKey}})).json()
 const result={id:'test-image-job',state:'succeeded',model:'test-image-model',errorCode:null,reservedAiCredits:60,settledAiCredits:40,imageKey:fx.imageKey,imageUrl:resolved.url}
 await page.route('**/api/v1/activity-media/creation/jobs',r=>{submitted++;return r.fulfill({json:result})})
 await page.route('**/api/v1/activity-media/creation/jobs/test-image-job',r=>r.fulfill({json:result}))
 await workspace.getByRole('button',{name:'AI image',exact:true}).click()
 const creator=page.getByRole('dialog',{name:'Create a question image'})
 await creator.getByRole('textbox').fill('A simple flower diagram without labels')
 await expect(creator.getByRole('button',{name:'Generate image',exact:true})).toBeEnabled()
 expect(submitted).toBe(0)
 await creator.getByRole('button',{name:'Generate image',exact:true}).click()
 await expect(creator.getByRole('button',{name:'Use this image',exact:true})).toBeDisabled()
 await creator.getByRole('checkbox').check()
 await expect(creator.getByRole('button',{name:'Use this image',exact:true})).toBeEnabled()
 await page.screenshot({path:'.impeccable/review/pin-ai-desktop.png',fullPage:true})
 await creator.getByRole('button',{name:'Use this image',exact:true}).click();expect(submitted).toBe(1)
 await workspace.getByRole('button',{name:'Learner preview',exact:true}).click()
 await expect(workspace.getByText('Square',{exact:true})).toBeVisible()
 await workspace.getByRole('button',{name:'Back to editing',exact:true}).click()
 await expect(page.getByText('Saved',{exact:true})).toBeVisible({timeout:10000})
 await page.evaluate(()=>localStorage.setItem('asasera.language','ar'))
 await page.setViewportSize({width:390,height:844});await page.reload()
 const arabic=page.getByRole('region',{name:'محرر إجابات الصورة'})
 await expect(arabic).toBeVisible({timeout:20000});await expect(arabic.getByRole('textbox',{name:'إجابة المنطقة 4',exact:true})).toHaveValue('Another circle')
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'.impeccable/review/pin-mobile-ar.png',fullPage:true})
 await arabic.getByRole('button',{name:'معاينة الطالب',exact:true}).scrollIntoViewIfNeeded()
 await page.screenshot({path:'.impeccable/review/pin-mobile-tools-ar.png',fullPage:true})
 await arabic.locator('img').first().scrollIntoViewIfNeeded()
 await page.screenshot({path:'.impeccable/review/pin-mobile-image-ar.png',fullPage:true})
 await arabic.getByRole('textbox',{name:'إجابة المنطقة 1',exact:true}).scrollIntoViewIfNeeded()
 await page.screenshot({path:'.impeccable/review/pin-mobile-answers-ar.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await arabic.getByRole('button',{name:'نظّف الصورة',exact:true}).click()
 await expect(page.getByRole('dialog').locator('canvas')).toBeVisible()
 await page.screenshot({path:'.impeccable/review/pin-cleanup-mobile-ar.png',fullPage:true})
 expect(errors).toEqual([])
})
