import {test,expect} from '@playwright/test'
import {localTeacher,isolatedStackOnly} from './local-fixture'
for(const [width,ar] of [[1440,false],[390,true]] as const)test(`question properties ${width}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 isolatedStackOnly();await page.setViewportSize({width,height:1000});const teacher=localTeacher()
 await page.addInitScript(ar=>localStorage.setItem('asasera.language',ar?'ar':'en'),ar)
 const login=await page.request.post('/api/v1/auth/login',{data:{email:teacher.email,password:teacher.password}});expect(login.ok()).toBeTruthy();const {accessToken}=await login.json(),headers={authorization:`Bearer ${accessToken}`}
 const r=await page.request.post('/api/v1/activities',{headers,data:{title:'Question properties fixture',subjectId:1,levelId:8,purposeId:2}});const {activity}=await r.json()
 for(let i=0;i<2;i++)await page.request.post(`/api/v1/activities/${activity.id}/questions`,{headers,data:{kind:'mcq',prompt:`Question ${i+1}`,payload:{options:[{key:'a',text:'One'},{key:'b',text:'Two'},{key:'c',text:'Three'},{key:'d',text:'Four'}],correct:'a'},timeLimitS:20}})
 await page.goto(`/teacher/activities/${activity.id}`)
 const toggle=page.locator('[data-properties-toggle]'),panel=page.locator('aside[data-editor-drawer]')
 if(width<1025)await toggle.click()
 await expect(panel.getByRole('heading',{name:ar?'خصائص السؤال':'Question properties'})).toBeVisible()
 await panel.locator('#question-duration').click();await page.getByRole('option',{name:ar?'30 ثانية':'30 seconds',exact:true}).click()
 await panel.getByRole('button',{name:ar?'تطبيق على جميع الأسئلة':'Apply to all questions',exact:true}).click()
 await expect.poll(async()=>{const r=await page.request.get(`/api/v1/activities/${activity.id}`,{headers});return (await r.json()).questions.map((q:{timeLimitS:number})=>q.timeLimitS)}).toEqual([30,30])
 await panel.locator('#question-points').click()
 await expect(page.getByRole('option')).toHaveCount(3)
 await expect(page.locator('[class*="_popup_"]').filter({has:page.getByRole('option').first()})).toHaveCSS('opacity','1')
 await expect(page.getByRole('textbox',{name:ar?'نص السؤال':'Question text',exact:true})).toHaveCount(1)
 await page.screenshot({path:`../screenshots/question-properties-menu-${width}.png`})
 await page.getByRole('option',{name:ar?/نقاط مضاعفة/:/Double points/}).click()
 await expect.poll(async()=>{const r=await page.request.get(`/api/v1/activities/${activity.id}`,{headers});return (await r.json()).questions[0].payload.pointsMultiplier}).toBe(2)
 await page.reload();if(width<1025)await toggle.click()
 await expect(panel.locator('#question-points')).toHaveText(ar?'نقاط مضاعفة':'Double points')
 await expect(panel.locator('#question-duration')).toHaveText(ar?'30 ثانية':'30 seconds')
 await panel.getByRole('button',{name:ar?'أغلق الخصائص':'Close properties',exact:true}).click();await expect(panel).toBeHidden();await toggle.click();await expect(panel).toBeVisible()
 await panel.locator('#question-points').click();await page.getByRole('option',{name:ar?/بدون نقاط/:/No points/}).click()
 await expect.poll(async()=>{const r=await page.request.get(`/api/v1/activities/${activity.id}`,{headers});return (await r.json()).questions[0].payload.pointsMultiplier}).toBe(0)
 expect(errors).toEqual([])
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
