import {test,expect} from '@playwright/test'
import {localTeacher,isolatedStackOnly} from './local-fixture'
for(const width of [1440,390])test(`question formatting ${width}`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 isolatedStackOnly();await page.setViewportSize({width,height:900});const teacher=localTeacher()
 await page.addInitScript(()=>localStorage.setItem('asasera.language','en'))
 const login=await page.request.post('/api/v1/auth/login',{data:{email:teacher.email,password:teacher.password}});expect(login.ok()).toBeTruthy();const {accessToken}=await login.json(),headers={authorization:`Bearer ${accessToken}`}
 const r=await page.request.post('/api/v1/activities',{headers,data:{title:'Question type picker fixture',subjectId:1,levelId:8,purposeId:2}});expect(r.ok()).toBeTruthy();const {activity}=await r.json()
 const q=await page.request.post(`/api/v1/activities/${activity.id}/questions`,{headers,data:{kind:'mcq',prompt:'Which number is even?',payload:{options:[{key:'a',text:'2'},{key:'b',text:'3'},{key:'c',text:'5'},{key:'d',text:'7'}],correct:'a'}}});expect(q.ok()).toBeTruthy()
 await page.goto(`/teacher/activities/${activity.id}`)
 const input=page.getByRole('textbox',{name:'Question text',exact:true});await expect(input).toBeVisible()
 const questionField=page.locator('[data-formatted-field]').filter({has:input})
 const toolbar=questionField.getByRole('toolbar',{includeHidden:true})
 await page.getByRole('textbox',{name:'Activity title',exact:true}).focus();await page.mouse.move(0,0)
 await expect(toolbar).toBeHidden()
 const originalBox=await input.boundingBox()
 // Hover no longer reveals the tools — only focus does — and revealing them must not move the text.
 await input.hover();await expect(toolbar).toBeHidden()
 await input.focus();await expect(toolbar).toBeVisible()
 expect(await input.boundingBox()).toEqual(originalBox)
 await page.getByRole('textbox',{name:'Activity title',exact:true}).focus();await expect(toolbar).toBeHidden()
 await input.focus();await expect(toolbar).toBeVisible()
 await input.fill('Water cycle');await input.press('ControlOrMeta+A')
 await questionField.getByRole('button',{name:'Bold',exact:true}).click();await expect(input).toHaveText('Water cycle');await expect(input.locator('strong')).toHaveText('Water cycle')
 await questionField.getByRole('button',{name:'Italic',exact:true}).click();await expect(input.locator('strong em')).toHaveText('Water cycle')
 await input.press('ControlOrMeta+Z');await expect(input.locator('em')).toHaveCount(0);await expect(input.locator('strong')).toHaveText('Water cycle')
 const answer=page.getByRole('textbox',{name:'Answer 1 text',exact:true}),answerField=page.locator('[data-formatted-field]').filter({has:answer})
 await answer.click();await answer.press('ControlOrMeta+A');await answer.pressSequentially('H2O');await answer.press('ControlOrMeta+A');await answer.press('ArrowLeft');await answer.press('ArrowRight');await answer.press('Shift+ArrowRight')
 await expect.poll(()=>page.evaluate(()=>window.getSelection()?.toString())).toBe('2')
 await answerField.getByRole('button',{name:'Subscript',exact:true}).click();await expect(answer).toHaveText('H2O');await expect(answer.locator('sub')).toHaveText('2')
 await answerField.getByRole('button',{name:'Superscript',exact:true}).click();await expect(answer.locator('sup')).toHaveText('2');await expect(answer.locator('sub')).toHaveCount(0)
 await answerField.getByRole('button',{name:'Superscript',exact:true}).click();await expect(answer.locator('sup')).toHaveCount(0)
 await answerField.getByRole('button',{name:'Subscript',exact:true}).click();await expect(answer.locator('sub')).toHaveText('2')
 await page.screenshot({path:`../screenshots/visual-answer-formatting-${width}.png`})
 await answer.press('ArrowRight');await answer.press('ArrowRight');await answer.press('ArrowRight')
 const chooser=page.waitForEvent('filechooser');await page.locator('[data-answer-cell]').first().getByRole('button',{name:'Answer image',exact:true}).click();await chooser;await answer.focus()
 await answerField.getByRole('button',{name:'Equation',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 const modal=page.getByRole('dialog')
 await expect(modal.getByRole('button',{name:'Insert equation',exact:true})).toBeDisabled()
 await modal.getByRole('button',{name:'Fraction',exact:true}).click()
 // Digits and placeholder navigation come from the physical keyboard; the dialog ships no key pad.
 await modal.locator('math-field').press('1')
 await expect(modal.getByRole('button',{name:'Insert equation',exact:true})).toBeDisabled()
 await modal.locator('math-field').press('Tab')
 await modal.locator('math-field').press('2')
 await expect(modal.getByRole('button',{name:'Insert equation',exact:true})).toBeEnabled()
 await expect(modal.locator('input:not([type=hidden])')).toHaveCount(0)
 await page.screenshot({path:`../screenshots/question-equation-${width}.png`})
 await modal.getByRole('button',{name:'Insert equation',exact:true}).click()
 await expect(input).toHaveText('Water cycle');await expect(answer.locator('math')).toHaveCount(1);await expect(answer.locator('.asasera-equation')).toHaveAttribute('data-equation',/frac/)
 await expect.poll(async()=>{const response=await page.request.get(`/api/v1/activities/${activity.id}`,{headers});const data=await response.json();return JSON.stringify(data.questions)}).toContain('frac')
 await page.reload();await expect(input.locator('strong')).toHaveText('Water cycle')
 await expect(answer.locator('sub')).toHaveText('2');await expect(answer.locator('math')).toHaveCount(1)
 // Reopen the rendered fraction itself, replace it visually, and preserve the rest of the answer.
 await answer.locator('.asasera-equation').click()
 await expect(modal.locator('math-field')).toHaveJSProperty('value','\\frac12')
 await modal.getByRole('button',{name:'Clear equation',exact:true}).click()
 await modal.getByRole('button',{name:'Square root',exact:true}).click()
 await modal.locator('math-field').press('9')
 await modal.getByRole('button',{name:'Insert equation',exact:true}).click()
 await expect(answer.locator('.asasera-equation')).toHaveAttribute('data-equation',/sqrt(?:\{9\}|9)/)
 const savedValue=await answer.textContent(),savedEquation=await answer.locator('.asasera-equation').getAttribute('data-equation')
 await answer.locator('.asasera-equation').click()
 await modal.getByRole('button',{name:'Clear equation',exact:true}).click()
 await modal.getByRole('button',{name:'Power',exact:true}).click()
 await modal.locator('math-field').press('x')
 await modal.locator('math-field').press('Tab')
 await modal.locator('math-field').press('2')
 await expect(modal.locator('math-field')).toHaveJSProperty('value','x^2')
 await modal.getByRole('button',{name:'Cancel',exact:true}).click()
 expect(await answer.textContent()).toBe(savedValue);await expect(answer.locator('.asasera-equation')).toHaveAttribute('data-equation',savedEquation!)
 await answer.locator('.asasera-equation').click();await page.keyboard.press('Escape');await expect(modal).toHaveCount(0)
 expect(errors).toEqual([])
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:`../screenshots/question-formatting-${width}.png`})
 if(width===390){
  await page.locator('button[lang="ar"]').click()
  await page.locator('[data-answer-cell]').first().locator('.asasera-equation').click()
  await expect(modal).toHaveAttribute('dir','rtl')
  await expect(modal.getByRole('button',{name:'إدراج المعادلة',exact:true})).toBeEnabled()
  await page.screenshot({path:'../screenshots/question-equation-ar-390.png'})
  await modal.getByRole('button',{name:'إلغاء',exact:true}).click()
  await page.locator('[data-answer-cell]').first().getByRole('textbox').focus()
  await page.screenshot({path:'../screenshots/visual-answer-formatting-ar-390.png'})
 }
})
