import {test,expect} from '@playwright/test'

test('real live host moderation stays private, preserves wheel state, and ends the revoked learner seat',async({page,request,browser})=>{
 test.setTimeout(60000)
 const origin=process.env.PW_BASE_URL??''
 expect(origin).toBe('http://127.0.0.1:5411')
 const email=`session-moderation-${crypto.randomUUID()}@example.com`,password='Synthetic live test 2026!'
 expect((await request.post('/api/v1/auth/register/teacher',{data:{name:'Synthetic moderation host',email,password}})).ok()).toBe(true)
 const login=await request.post('/api/v1/auth/login',{data:{email,password}}),{accessToken}=await login.json(),headers={authorization:`Bearer ${accessToken}`}
 await page.context().addCookies((await request.storageState()).cookies)
 const made=await request.post('/api/v1/activities',{headers,data:{title:'Synthetic moderation class',subjectId:1,levelId:8,purposeId:2}})
 expect(made.ok()).toBe(true)
 const {activity}=await made.json()
 expect((await request.post(`/api/v1/activities/${activity.id}/questions`,{headers,data:{kind:'tf',prompt:'One plus one equals two',payload:{correct:true}}})).ok()).toBe(true)
 expect((await request.post(`/api/v1/activities/${activity.id}/publish`,{headers})).ok()).toBe(true)
 await page.addInitScript(()=>localStorage.setItem('asasera.language','en'))
 await page.setViewportSize({width:1440,height:900})
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(`/teacher/live/new?activityId=${activity.id}&request=${crypto.randomUUID()}`)
 await expect(page.getByRole('button',{name:'Start class',exact:true})).toBeVisible()
 const pin=await page.locator('strong[dir=ltr]').first().innerText()
 const learnerContext=await browser.newContext({baseURL:origin,viewport:{width:390,height:844}})
 await learnerContext.addInitScript(()=>localStorage.setItem('asasera.language','en'))
 const learner=await learnerContext.newPage()
 const publicFrames:string[]=[]
 learner.on('websocket',socket=>socket.on('framereceived',frame=>publicFrames.push(String(frame.payload))))
 try{
  await learner.goto(`/join?pin=${pin}`)
  await learner.getByLabel('Display name').fill('Amal')
  await learner.getByRole('button',{name:'Join class',exact:true}).click()
  await expect(learner.getByText('You are in. Wait for your teacher to start.')).toBeVisible()
  await expect(learner.getByText(/Manage participants/)).toHaveCount(0)
  await page.getByText('Manage participants (1)').click()
  await page.getByRole('button',{name:'Rename Amal',exact:true}).click()
  await page.getByLabel('Display name').fill('Amal Ali')
  await page.getByRole('button',{name:'Save name',exact:true}).click()
  await expect(learner.getByRole('heading',{name:'Welcome, Amal Ali'})).toBeVisible()
  await page.getByRole('button',{name:'Exclude Amal Ali from wheel'}).click()
  await expect(page.getByText('Excluded from wheel',{exact:true})).toBeVisible()
  await page.screenshot({path:'.impeccable/review/session-participants-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Random wheel',exact:true}).click()
  await expect(page.getByText('Student names appear after they join the class.')).toBeVisible()
  await page.getByRole('button',{name:'Include Amal Ali in wheel'}).click()
  await page.getByRole('button',{name:'Spin the wheel',exact:true}).click()
  await expect(page.locator('[data-random-wheel]')).toHaveAttribute('data-wheel-state','selected',{timeout:8000})
  await page.reload()
  await expect(page.locator('[role=status] strong')).toHaveText('Amal Ali')
  await page.getByRole('button',{name:'Back to class'}).click()
  await page.getByText('Manage participants (1)').click()
  await page.getByRole('button',{name:'Remove Amal Ali',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Remove Amal Ali?'})).toBeVisible()
  const bounds=await page.getByRole('dialog').boundingBox()
  expect(bounds!.x).toBeGreaterThan(100)
  expect(bounds!.y).toBeGreaterThan(100)
  await page.screenshot({path:'.impeccable/review/session-participants-confirm-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Cancel',exact:true}).click()
  await expect(learner.getByText('You are in. Wait for your teacher to start.')).toBeVisible()
  await page.locator('summary[aria-label="Session options"]').click()
  await page.getByRole('button',{name:'العربية',exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:'.impeccable/review/session-participants-mobile-ar.png',fullPage:true})
  await page.emulateMedia({colorScheme:'dark'})
  await expect(page.locator('html')).toHaveClass(/dark/)
  await expect(page.getByRole('button',{name:'تغيير اسم Amal Ali',exact:true})).toHaveCSS('background-color','rgb(34, 34, 34)')
  await page.screenshot({path:'.impeccable/review/session-participants-mobile-ar-dark.png',fullPage:true})
  await page.getByRole('button',{name:'إزالة Amal Ali',exact:true}).click()
  await page.screenshot({path:'.impeccable/review/session-participants-confirm-mobile-ar.png',fullPage:true})
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'إزالة Amal Ali',exact:true})).toBeFocused()
  await page.getByRole('button',{name:'إزالة Amal Ali',exact:true}).click()
  await page.getByRole('button',{name:'إزالة المشارك',exact:true}).click()
  await expect(learner.getByRole('heading',{name:'Your teacher removed you from this class'})).toBeVisible()
  expect(await learner.evaluate(()=>sessionStorage.getItem('asasera:participant'))).toBeNull()
  await expect(learner.getByText('Reconnecting…',{exact:true})).toHaveCount(0)
  await learner.screenshot({path:'.impeccable/review/session-participant-removed-mobile.png',fullPage:true})
  expect(publicFrames.join('\n')).not.toMatch(/wheelExcluded|token_revoked_at|moderationPending/)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect(await learner.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect(errors).toEqual([])
 }finally{await learnerContext.close()}
})
