import {test,expect} from '@playwright/test'

for(const ar of [false,true])test(`real shared box launch, explicit begin, saved answer and resume ${ar?'Arabic mobile':'English desktop'}`,async({page,request,browser})=>{
 test.setTimeout(60000)
 const origin=process.env.PW_BASE_URL??'';expect(origin).toBe('http://127.0.0.1:5411')
 const email=`presentation-live-${crypto.randomUUID()}@example.com`,password='Synthetic live presentation 2026!'
 expect((await request.post('/api/v1/auth/register/teacher',{data:{name:'Synthetic presentation host',email,password}})).ok()).toBe(true)
 const login=await request.post('/api/v1/auth/login',{data:{email,password}}),{accessToken}=await login.json(),headers={authorization:`Bearer ${accessToken}`}
 await page.context().addCookies((await request.storageState()).cookies)
 const made=await request.post('/api/v1/activities',{headers,data:{title:'Synthetic shared box class',subjectId:1,levelId:8,purposeId:2}}),{activity}=await made.json()
 for(const [prompt,correct] of [['First reviewed statement',false],['Second reviewed statement',true]] as const)expect((await request.post(`/api/v1/activities/${activity.id}/questions`,{headers,data:{kind:'tf',prompt,payload:{correct},hint:'A reviewed synthetic hint',challenge:true}})).ok()).toBe(true)
 expect((await request.post(`/api/v1/activities/${activity.id}/publish`,{headers})).ok()).toBe(true)
 await page.addInitScript(language=>{localStorage.setItem('asasera.language',language);localStorage.setItem('asasera:activity-motion','off')},ar?'ar':'en')
 await page.setViewportSize(ar?{width:390,height:844}:{width:1440,height:900})
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
 await page.goto(`/teacher/activities/${activity.id}/play?mode=live`)
 await page.getByRole('radio',{name:ar?/افتح الصندوق/:/Open the box/}).check()
 await page.getByRole('checkbox',{name:ar?'السماح للمعلم بعرض التلميحات المحفوظة للجميع':'Allow the teacher to reveal reviewed hints to everyone'}).check()
 await page.getByRole('button',{name:ar?'ابدأ الحصة المباشرة':'Start live game',exact:true}).click()
 await expect(page.getByRole('button',{name:ar?'افتح الصندوق 2':'Open box 2',exact:true})).toBeVisible()
 await expect(page).toHaveURL(/\/teacher\/live\/\d+$/)
 expect(await page.evaluate(()=>Object.keys(sessionStorage).filter(key=>key.startsWith('asasera.live-launch:')))).toEqual([])
 const pin=await page.locator('strong[dir=ltr]').first().innerText()
 const learnerContext=await browser.newContext({baseURL:origin,viewport:{width:390,height:844}})
 await learnerContext.addInitScript(language=>localStorage.setItem('asasera.language',language),ar?'ar':'en')
 const learner=await learnerContext.newPage(),frames:string[]=[]
 learner.on('websocket',socket=>socket.on('framereceived',frame=>frames.push(String(frame.payload))))
 try{
  await learner.goto(`/join?pin=${pin}`)
  await learner.getByLabel(ar?'اسمك في الحصة':'Display name').fill('Amal')
  await learner.getByRole('button',{name:ar?'انضم':'Join class',exact:true}).click()
  await expect(learner.getByText(ar?'أنت في الحصة. انتظر إشارة المعلّم.':'You are in. Wait for your teacher to start.')).toBeVisible()
  await page.getByRole('button',{name:ar?'افتح الصندوق 2':'Open box 2',exact:true}).click()
  await expect(page.getByRole('button',{name:ar?'ابدأ السؤال':'Begin question',exact:true})).toBeVisible()
  await expect(learner.getByText(ar?'انتظر بدء السؤال من المعلّم.':'Wait for your teacher to begin the question.')).toBeVisible()
  await expect(learner.getByText('Second reviewed statement',{exact:true})).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading',{name:ar?'السؤال 2':'Question 2',exact:true})).toBeVisible()
  await page.getByRole('button',{name:ar?'ابدأ السؤال':'Begin question',exact:true}).click()
  await expect(learner.getByRole('heading',{name:'Second reviewed statement'})).toBeVisible()
  await expect(learner.getByLabel(ar?'انتهى الوقت':'Time is up')).toHaveCount(0)
  await page.getByRole('button',{name:ar?'أظهر تلميحًا':'Show hint',exact:true}).click()
  await expect(learner.getByText('A reviewed synthetic hint',{exact:true})).toBeVisible()
  await learner.getByRole('button',{name:ar?'صح':/True/,exact:ar}).click()
  await expect(learner.getByRole('heading',{name:ar?'تم حفظ إجابتك':'You’re in! Answer saved'})).toBeVisible()
  await page.getByRole('button',{name:ar?'اكشف الإجابة':'Reveal answer',exact:true}).click()
  await expect(learner.getByRole('heading',{name:ar?'إجابة صحيحة!':'You got it!'})).toBeVisible()
  await expect(page.getByRole('button',{name:ar?'افتح الصندوق 2':'Open box 2',exact:true})).toBeDisabled()
  await page.getByRole('button',{name:ar?'افتح الصندوق 1':'Open box 1',exact:true}).scrollIntoViewIfNeeded()
  await page.evaluate(()=>scrollTo(0,0))
  await page.screenshot({path:`.impeccable/review/live-presentation-${ar?'mobile-ar':'desktop-en'}.png`,fullPage:true})
  await learner.evaluate(()=>scrollTo(0,0))
  await learner.screenshot({path:`.impeccable/review/live-presentation-player-${ar?'mobile-ar':'mobile-en'}.png`,fullPage:true})
  expect(frames.join('\n')).not.toMatch(/teamAssignments|teamRoster|wheelExcluded|token_revoked_at/)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect(await learner.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect(errors).toEqual([])
 }finally{await learnerContext.close()}
})
