import {test,expect} from '@playwright/test'

for(const [width,lang,theme] of [[1440,'en','light'],[390,'ar','light'],[390,'en','dark']] as const)test(`select and remove video ${width} ${lang} ${theme}`,async({page})=>{
 const ar=lang==='ar'
 await page.setViewportSize({width,height:900})
 await page.route('https://www.youtube-nocookie.com/**',route=>route.fulfill({contentType:'text/html; charset=utf-8',body:'<body style="margin:0;display:grid;place-items:center;height:100vh;background:#e9eef6;color:#24334c;font:16px sans-serif">Video preview · test fixture</body>'}))
 await page.route('**/api/**',async route=>{
  const url=new URL(route.request().url()),path=url.pathname
  await route.fulfill({json:path.endsWith('/preferences')?{capabilities:{imageCreation:{state:'ready'},videoSuggestions:{state:'ready'}}}
   :{suggestions:[{videoId:url.searchParams.get('videoId')??'abcdefghijk',title:'Evolution of computers',channel:'Example educator',description:'A lesson about early computers.',thumbnail:null,durationSeconds:3723}]}})
 })
 await page.goto(`/e2e/fixtures/image-creator.html?lang=${lang}&theme=${theme}&video=1`)
 await page.getByRole('button',{name:'Open media'}).click()
 await page.getByRole('button',{name:ar?'يوتيوب':'YouTube',exact:true}).click()
 const choose=page.getByRole('button',{name:ar?'استخدم هذا الفيديو':'Use this video',exact:true})
 await expect(choose).toBeVisible()
 expect(await page.locator('dialog[open]').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
 await page.screenshot({path:`/tmp/asasera-video-choice-${width}.png`})
 await choose.click()
 await expect(page.locator('dialog[open]')).toHaveCount(1)
 const from=page.getByLabel(ar?'بداية الفيديو':'Start video at'),to=page.getByLabel(ar?'نهاية الفيديو':'End video at')
 await expect(page.locator('[data-full-video-length]')).toContainText(ar?'مدة الفيديو الكاملة':'Full video length')
 await expect(page.locator('[data-full-video-length]')).toContainText('1:02:03')
 await to.fill('1:02:04')
 await expect(page.getByRole('button',{name:ar?'إضافة الفيديو':'Add video',exact:true})).toBeDisabled()
 await page.getByRole('button',{name:ar?'الفيديو كاملًا':'Use full video',exact:true}).click()
 await expect(from).toHaveValue('00:00');await expect(to).toHaveValue('')
 await from.fill(ar?'٠٠:٠٥':'00:05');await to.fill('00:25')
 if(!ar)await expect(page.locator('[data-selected-clip]')).toContainText('20 sec')
 await page.getByRole('button',{name:ar?'معاينة هذا الجزء':'Preview clip',exact:true}).click()
 await expect(page.getByTitle(ar?'معاينة مقطع الفيديو':'Video clip preview')).toHaveAttribute('src',/start=5&end=25/)
 await expect(page.frameLocator(`iframe[title="${ar?'معاينة مقطع الفيديو':'Video clip preview'}"]`).getByText('Video preview · test fixture')).toBeVisible()
 expect(await page.locator('dialog[open]').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
 if(width===1440)expect((await page.locator('dialog[open]').boundingBox())!.height).toBeLessThan(720)
 await page.screenshot({path:`/tmp/asasera-video-time-${width}-${lang}-${theme}.png`})
 if(theme==='light')await page.screenshot({path:`.impeccable/review/video-time-${width}.png`})
 await page.getByRole('button',{name:ar?'إضافة الفيديو':'Add video',exact:true}).click()
 await expect(page.locator('dialog[open]')).toHaveCount(0)
 await expect(page.locator('output')).toHaveText('abcdefghijk')
 await expect(page.getByTitle(ar?'الفيديو المرفق':'Attached video')).toHaveAttribute('src',/youtube-nocookie.com\/embed\/abcdefghijk/)
 await expect(page.frameLocator(`iframe[title="${ar?'الفيديو المرفق':'Attached video'}"]`).getByText('Video preview · test fixture')).toBeVisible()
 await expect(page.getByRole('link',{name:ar?'افتح في يوتيوب':'Open on YouTube'})).toHaveCount(0)
 const info=page.getByRole('button',{name:ar?'معلومات الفيديو':'Video information',exact:true})
 await expect(page.locator('[data-video-duration]')).toContainText(ar?'مدة الفيديو':'Video length')
 if(!ar){
  await expect(page.locator('[data-video-duration]')).toContainText('1 hr 2 min 3 sec')
  await expect(page.locator('[data-video-duration]')).toContainText('Selected clip: 20 sec')
 }
 await expect(info).toHaveAttribute('aria-expanded','false')
 expect(await page.locator('[data-question-image]').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
 const frame=await page.getByTitle(ar?'الفيديو المرفق':'Attached video').boundingBox()
 expect(frame!.width).toBeLessThanOrEqual(600)
 expect(frame!.width/frame!.height).toBeCloseTo(16/9,1)
 const infoSize=await info.boundingBox()
 expect(infoSize!.width).toBe(44)
 expect(infoSize!.height).toBe(44)
 await page.screenshot({path:`/tmp/asasera-video-card-${width}-${lang}-${theme}.png`})
 await page.screenshot({path:`/tmp/asasera-video-attached-${width}.png`})
 await page.getByRole('button',{name:ar?'تعديل التوقيت':'Edit timeframe',exact:true}).click()
 await expect(from).toHaveValue('00:05');await expect(to).toHaveValue('00:25')
 await to.fill('00:04')
 const save=page.getByRole('button',{name:ar?'حفظ التوقيت':'Save timeframe',exact:true})
 await expect(save).toBeDisabled()
 await to.fill('00:35');await save.click()
 await expect(page.getByTitle(ar?'الفيديو المرفق':'Attached video')).toHaveAttribute('src',/start=5&end=35/)
 if(!ar)await expect(page.locator('[data-video-duration]')).toContainText('Selected clip: 30 sec')
 await info.click()
 await expect(info).toHaveAttribute('aria-expanded','true')
 await expect(page.getByRole('link',{name:ar?'افتح في يوتيوب':'Open on YouTube'})).toBeVisible()
 await page.getByRole('button',{name:ar?'استبدال الفيديو':'Replace video',exact:true}).click()
 await page.getByRole('textbox').fill('https://youtu.be/lmnopqrstuv')
 await expect(page.locator('dialog iframe')).toHaveAttribute('src',/embed\/lmnopqrstuv/)
 await choose.focus()
 await page.keyboard.press('Enter')
 await expect(from).toHaveValue('00:00');await expect(to).toHaveValue('')
 await page.getByRole('button',{name:ar?'إضافة الفيديو':'Add video',exact:true}).click()
 await expect(page.locator('output')).toHaveText('lmnopqrstuv')
 await expect(page.getByTitle(ar?'الفيديو المرفق':'Attached video')).toHaveAttribute('src',/embed\/lmnopqrstuv/)
 await expect(page.locator('[data-video-duration] small')).toHaveCount(0)
 await page.getByRole('button',{name:ar?'إزالة الفيديو':'Remove video',exact:true}).click()
 await expect(page.locator('output')).toHaveText('')
 await expect(page.getByTitle(ar?'الفيديو المرفق':'Attached video')).toHaveCount(0)
})

test('unavailable duration does not block the attached video or its controls',async({page})=>{
 await page.route('https://www.youtube-nocookie.com/**',route=>route.fulfill({body:'Video fixture'}))
 await page.route('**/api/**',route=>{
  const url=new URL(route.request().url())
  if(url.searchParams.has('videoId'))return route.fulfill({status:503,json:{error:{code:'video_search_unavailable',message:'Unavailable'}}})
  return route.fulfill({json:url.pathname.endsWith('/preferences')?{capabilities:{videoSuggestions:{state:'ready'}}}:{suggestions:[{videoId:'abcdefghijk',title:'Example',channel:'Educator',description:'',thumbnail:null}]}})
 })
 await page.goto('/e2e/fixtures/image-creator.html?lang=en&video=1')
 await page.getByRole('button',{name:'Open media'}).click()
 await page.getByRole('button',{name:'YouTube',exact:true}).click()
 await page.getByRole('button',{name:'Use this video',exact:true}).click()
 await page.getByRole('button',{name:'Add video',exact:true}).click()
 await expect(page.locator('[data-video-duration]')).toContainText('Length unavailable')
 await expect(page.getByTitle('Attached video')).toBeVisible()
 await expect(page.getByRole('button',{name:'Edit timeframe',exact:true})).toBeEnabled()
 await page.getByRole('button',{name:'Remove video',exact:true}).click()
 await expect(page.getByTitle('Attached video')).toHaveCount(0)
})
