import {test,expect} from '@playwright/test'
test.use({viewport:{width:1440,height:900},video:{mode:'on',size:{width:1440,height:900}}})

for(const [lang,width,theme,fallback] of [['en',1440,'light',false],['ar',390,'dark',true]] as const){
 test(`reference wheel ${lang}: modes, zoom, sound, fullscreen and same result`,async({page})=>{
  test.setTimeout(45000)
  const ar=lang==='ar',errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.setViewportSize({width,height:900})
  await page.goto(`/e2e/fixtures/wheel-reference.html?lang=${lang}&theme=${theme}${fallback?'&fallback=1':''}`)
  const wheel=page.locator('[data-random-wheel]'),spin=page.getByRole('button',{name:ar?'أدر العجلة':'Spin the wheel',exact:true})
  await expect(page.getByRole('radio',{name:ar?/الطلاب فقط/:/Students only/})).toBeChecked()
  await page.getByRole('radio',{name:ar?/طالب وسؤال/:/Student \+ question/}).click()
  await expect(page.getByRole('radio',{name:ar?/طالب وسؤال/:/Student \+ question/})).toBeChecked()
  await page.getByRole('button',{name:ar?'تشغيل الصوت':'Turn sound on'}).click()
  await expect(page.getByRole('button',{name:ar?'كتم الصوت':'Mute sound'})).toBeVisible()
  await page.getByRole('button',{name:ar?'ملء الشاشة':'Fullscreen',exact:true}).click()
  await expect(wheel).toHaveAttribute('data-fullscreen','true')
  await page.screenshot({path:`../docs/evidence/interactive/wheel-video-${lang}-ready.png`})
  await spin.click()
  await expect(wheel).toHaveAttribute('data-wheel-state','spinning')
  await expect(page.getByRole('button',{name:ar?'تدور العجلة…':'Spinning…',exact:true})).toBeDisabled()
  await expect(wheel.locator('[role=status]')).toBeHidden()
  // The camera begins the reference zoom only once rotation has settled.
  const camera=page.locator('[data-wheel-playback]>div')
  await expect.poll(()=>camera.evaluate(el=>new DOMMatrix(getComputedStyle(el).transform).a),{timeout:6500}).toBeGreaterThan(1.08)
  await page.screenshot({path:`../docs/evidence/interactive/wheel-video-${lang}-zoom.png`})
  await expect.poll(()=>camera.evaluate(el=>{const style=getComputedStyle(el);return new DOMMatrix(style.transform).e > 10 && Number(style.opacity)<.9 && Number(style.opacity)>.05}),{timeout:2000,intervals:[25]}).toBe(true)
  await expect(wheel.locator('[role=status]')).toBeHidden()
  await page.screenshot({path:`../docs/evidence/interactive/wheel-video-${lang}-exit.png`})
  await expect(wheel).toHaveAttribute('data-wheel-state','selected',{timeout:8000})
  await expect(wheel.locator('[role=status] strong')).toHaveText(ar?'علي':'Ali')
  await expect(wheel.locator('[role=status] p')).toHaveText(ar?'ما أكبر كوكب؟':'Which is the largest planet?')
  await expect(page.locator('[data-wheel-playback]')).toHaveCount(0)
  const ticks=await page.evaluate(()=>((window as unknown as {wheelEvidence:{ticks:number[]}}).wheelEvidence.ticks))
  expect(ticks.length).toBeGreaterThan(2)
  expect(ticks.length).toBeLessThan(65)
  for(let i=1;i<ticks.length;i++)expect(ticks[i]!-ticks[i-1]!).toBeGreaterThan(45)
  await page.screenshot({path:`../docs/evidence/interactive/wheel-video-${lang}-result.png`})
  await page.getByRole('button',{name:ar?'الخروج من ملء الشاشة':'Exit fullscreen'}).click()
  await expect(wheel).toHaveAttribute('data-fullscreen','false')
  await page.getByRole('button',{name:ar?'عرض العجلة':'Show wheel'}).click()
  const geometry=await page.locator('[data-wheel-rotor]').evaluate(el=>{
   const m=new DOMMatrix(getComputedStyle(el).transform);return Math.atan2(m.b,m.a)*180/Math.PI
  })
  const sector=Math.floor((((-geometry)%360)+360)%360/120)
  expect(sector).toBe(1)
  await expect(page.locator('[data-wheel-disc]')).toHaveAttribute('data-pointer-angle','180')
  await page.getByRole('radio',{name:ar?/الأسئلة فقط/:/Questions only/}).click()
  await expect(page.getByRole('radio',{name:ar?/الأسئلة فقط/:/Questions only/})).toBeChecked()
  await spin.click();await page.getByRole('button',{name:ar?'تخطي الحركة':'Skip animation'}).click()
  await expect(wheel.locator('[role=status] strong')).toHaveText(ar?'ما مصدر الضوء؟':'What gives us daylight?')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect(errors).toEqual([])
 })
}
test('reduced motion and refused fullscreen retain selection and keyboard exit',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/e2e/fixtures/wheel-reference.html?fallback=1')
 const wheel=page.locator('[data-random-wheel]')
 await page.getByRole('button',{name:'Fullscreen',exact:true}).click()
 await expect(wheel).toHaveAttribute('data-expanded','true')
 await page.keyboard.press('Escape')
 await expect(wheel).toHaveAttribute('data-fullscreen','false')
 await expect(page.getByRole('button',{name:'Fullscreen',exact:true})).toBeFocused()
 await page.getByRole('button',{name:'Spin the wheel',exact:true}).click()
 await expect(wheel).toHaveAttribute('data-wheel-state','selected')
 await expect(wheel.locator('[role=status] strong')).toHaveText('Ali')
 expect(await page.evaluate(()=>((window as unknown as {wheelEvidence:{ticks:number[]}}).wheelEvidence.ticks))).toEqual([])
})

test('expanded desktop motion recording retains the complete stage',async({page})=>{
 await page.goto('/e2e/fixtures/wheel-reference.html?fallback=1')
 await page.getByRole('radio',{name:/Student \+ question/}).click()
 await page.getByRole('button',{name:'Turn sound on'}).click()
 await page.getByRole('button',{name:'Fullscreen',exact:true}).click()
 await expect(page.locator('[data-random-wheel]')).toHaveAttribute('data-expanded','true')
 await page.getByRole('button',{name:'Spin the wheel',exact:true}).click()
 await expect(page.locator('[data-random-wheel]')).toHaveAttribute('data-wheel-state','selected',{timeout:8000})
 await expect(page.locator('[role=status] strong')).toHaveText('Ali')
 await expect(page.locator('[role=status] p')).toHaveText('Which is the largest planet?')
 await page.screenshot({path:'../docs/evidence/interactive/wheel-video-en-expanded-result.png'})
})
