import {useTranslation} from 'react-i18next'
import type {LiveRules} from '@/shared/live-rules'
import type {PresentationSelection} from '@/shared/presentation'
import {useQuery} from '@tanstack/react-query'
import {ChevronDown,Clock3,Lightbulb,ShieldCheck,SlidersHorizontal,Sparkles,Trophy} from 'lucide-react'
import {api} from '@/lib/api'
import styles from './Presentations.module.css'
export function LiveRulesSetup({rules,onChange,disabled,activityId,selection,onSemantics}:{rules:LiveRules;onChange:(rules:LiveRules)=>void;disabled:boolean;activityId:number;selection:PresentationSelection;onSemantics:(semantics:'scored'|'practice')=>void}){
 const {i18n}=useTranslation(),ar=i18n.language.startsWith('ar'),t=(a:string,e:string)=>ar?a:e
 const content=useQuery({queryKey:['presentation-compatibility',activityId,'live'],queryFn:()=>api.get<{items:{questionId:number;number:number;prompt:string;challenge:boolean;hintAvailable:boolean}[]}>(`/api/v1/presentations/activities/${activityId}/compatibility?context=live`)})
 const practice=selection.config.semantics==='practice',graded=selection.config.semantics==='scored'||practice
 const selectedBonus=rules.bonus.questionIds.length
 const customized=practice||rules.extraPracticeAttempt||rules.timing==='timed'||rules.speedWeighting||rules.hints||rules.thinkTogether||selectedBonus>0||rules.bonus.points>0
 return <details className={styles.liveRules}>
  <summary><span className={styles.rulesSummaryIcon} aria-hidden="true"><SlidersHorizontal size={24}/></span><span className={styles.rulesSummaryCopy}><strong>{t('تخصيص الحصة المباشرة','Customize live game')}</strong><small>{t('اختياري — غيّر التقييم أو الوقت أو التلميحات أو النقاط الإضافية.','Optional — change scoring, timing, hints, or bonus points.')}</small></span><span className={styles.rulesSummaryState}>{customized?t('إعدادات مخصصة','Custom settings'):t('الإعدادات المقترحة مفعّلة','Recommended settings')}</span><ChevronDown className={styles.rulesChevron} size={22} aria-hidden="true"/></summary>
  <div className={styles.rulesBody}>
   <p className={styles.rulesIntro}><ShieldCheck size={22} aria-hidden="true"/><span>{t('الإعداد المقترح: تُحتسب الإجابة الأولى، ويتحكم المعلم بوقت الانتقال، وتمنح الإجابة الصحيحة 100 نقطة لعب.','Recommended setup: the first answer counts, you control the pace, and every correct answer earns 100 game points.')}</span></p>
   <fieldset className={styles.rulesFields} disabled={disabled}><legend className="sr-only">{t('إعدادات الحصة المباشرة','Live game settings')}</legend>
    {graded&&<section className={styles.ruleGroup}><header><ShieldCheck size={21} aria-hidden="true"/><div><strong>{t('التقييم','Scoring')}</strong><span>{t('حدد ما إذا كانت إجابات الطلاب ستظهر في التقارير.','Choose whether learner answers count in reports.')}</span></div></header><label className={styles.ruleOption}><input type="checkbox" checked={!practice} onChange={e=>{onSemantics(e.target.checked?'scored':'practice');if(e.target.checked)onChange({...rules,extraPracticeAttempt:false})}}/><span><strong>{t('احتساب إجابات الطلاب','Score learner answers')}</strong><small>{t('تُحفظ الإجابة الأولى لكل طالب في التقرير.','Each learner’s first answer is saved in the report.')}</small></span></label>{practice&&<label className={styles.ruleOption}><input type="checkbox" checked={rules.extraPracticeAttempt} onChange={e=>onChange({...rules,extraPracticeAttempt:e.target.checked})}/><span><strong>{t('السماح بمحاولة تدريب إضافية','Allow one practice retry')}</strong><small>{t('تبقى الإجابة الأولى محفوظة، والمحاولة الثانية للتعلّم فقط.','The first answer stays saved; the retry is for practice only.')}</small></span></label>}</section>}
    <section className={styles.ruleGroup}><header><Clock3 size={21} aria-hidden="true"/><div><strong>{t('الوقت والسرعة','Timing and pace')}</strong><span>{t('تحكم أنت بالانتقال، أو استخدم وقت كل سؤال.','Control the pace yourself or use each question’s timer.')}</span></div></header><label className={styles.ruleOption}><input type="checkbox" checked={rules.timing==='timed'} onChange={e=>onChange({...rules,timing:e.target.checked?'timed':'host-paced',speedWeighting:e.target.checked?rules.speedWeighting:false,thinkTogether:e.target.checked?rules.thinkTogether:false})}/><span><strong>{t('استخدام وقت كل سؤال','Use each question’s time limit')}</strong><small>{t('عند إيقافه، تقرر أنت متى تغلق السؤال.','When off, you decide when to close each question.')}</small></span></label>{rules.timing==='timed'&&<><label className={styles.ruleOption}><input type="checkbox" checked={rules.speedWeighting} onChange={e=>onChange({...rules,speedWeighting:e.target.checked})}/><span><strong>{t('مكافأة الإجابات السريعة','Reward faster answers')}</strong><small>{t('تحصل الإجابات الصحيحة الأسرع على نقاط لعب أكثر.','Faster correct answers earn more game points.')}</small></span></label><label className={styles.ruleOption}><input type="checkbox" checked={rules.thinkTogether} onChange={e=>onChange({...rules,thinkTogether:e.target.checked})}/><span><strong>{t('إتاحة 15 ثانية إضافية للتفكير','Allow 15 extra thinking seconds')}</strong><small>{t('يمكنك منح الوقت الإضافي للجميع مرة واحدة في كل سؤال.','You can give everyone extra time once per question.')}</small></span></label></>}</section>
    <section className={styles.ruleGroup}><header><Lightbulb size={21} aria-hidden="true"/><div><strong>{t('مساعدة الطلاب','Learner support')}</strong><span>{t('اعرض المساعدة المعتمدة بالتساوي لجميع الطلاب.','Offer the same reviewed support to everyone.')}</span></div></header><label className={styles.ruleOption}><input type="checkbox" checked={rules.hints} onChange={e=>onChange({...rules,hints:e.target.checked})}/><span><strong>{t('السماح بعرض التلميحات المحفوظة','Allow saved hints')}</strong><small>{t('يمكنك كشف التلميح المعتمد للجميع أثناء السؤال.','You can reveal the reviewed hint to everyone during the question.')}</small></span></label></section>
    {graded&&<details className={styles.bonus}><summary><span aria-hidden="true"><Sparkles size={21}/></span><span><strong>{t('إضافة نقاط لبعض الأسئلة','Add bonus points to selected questions')}</strong><small>{selectedBonus?t(`${selectedBonus} من الأسئلة محددة`,`${selectedBonus} questions selected`):t('غير مفعّل','Not set')}</small></span><ChevronDown size={20} aria-hidden="true"/></summary><div className={styles.bonusBody}><p>{t('اختر الأسئلة التي تستحق نقاط لعب إضافية. لا تتغير صحة الإجابة أو درجتها التعليمية.','Choose questions that earn extra game points. Correctness and learning marks do not change.')}</p><label className={styles.bonusPoints}><span>{t('النقاط الإضافية لكل إجابة صحيحة','Extra game points per correct answer')}</span><input type="number" min={0} max={500} step={1} value={rules.bonus.points} onChange={e=>onChange({...rules,bonus:{...rules.bonus,points:Math.max(0,Math.min(500,Math.floor(Number(e.target.value)||0)))}})}/></label><div className={styles.bonusQuestions}>{content.data?.items?.filter(item=>selection.selectedQuestionIds.includes(item.questionId)).map(item=><label className={styles.bonusQuestion} key={item.questionId}><input type="checkbox" checked={rules.bonus.questionIds.includes(item.questionId)} onChange={e=>onChange({...rules,bonus:{...rules.bonus,questionIds:e.target.checked?[...rules.bonus.questionIds,item.questionId]:rules.bonus.questionIds.filter(id=>id!==item.questionId)}})}/><span className={styles.questionNumber}>{item.number}</span><span dir="auto">{item.prompt.replace(/^\s*[0-9٠-٩۰-۹]+[.)،-]?\s*/,'')}</span></label>)}</div>{content.isPending&&<p>{t('تحميل الأسئلة المعتمدة…','Loading approved questions…')}</p>}{content.error&&<p role="alert">{t('تعذّر تحميل أسئلة النقاط الإضافية.','Could not load bonus questions.')}</p>}</div></details>}
   </fieldset>
   {selection.definitionId==='class-competition'&&<p className={styles.teamNote}><Trophy size={21} aria-hidden="true"/><span>{t('ستختار من فريقين إلى ستة فرق في شاشة الانتظار. تُحسب نقاط كل فريق بمتوسط نتائج أعضائه.','You will choose two to six teams in the lobby. Each team’s points use the average of its members’ results.')}</span></p>}
  </div>
 </details>
}
