import {FormattedText} from '@/components/formatted-text/FormattedText'
import {BackLink} from '@/design/BackLink'
import {useState} from 'react'
import {useParams,Link,useNavigate} from 'react-router-dom'
import {useQuery} from '@tanstack/react-query'
import {useTranslation} from 'react-i18next'
import {api,reports,encodeDraft,type HostReportRecord,type PracticeResponse,type ReportQuestion} from '@/lib/api'
import {Button,LoadingState,FailureState} from '@/design'
import styles from '../shelf/Workspace.module.css'
interface AuthorReport{title:string;status:string;totalParticipation?:number;classCount?:number;reuseCount?:number;teacherCount?:number;modifications?:{field:string;editors:number}[];questions:{questionId:number;versionId:number;status:string;answered?:number;correct?:number}[]}
const usd=(value:number)=>new Intl.NumberFormat('en',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:5}).format(value/100000)
/*
 * Two meanings, two badges (v5.1 C5). "Needs review" is an understanding heuristic
 * from observed answers only and always names its sample size; "Insufficient
 * evidence" says no claim is possible from zero or one answer. Participation
 * (who has not answered) is a plain line under each question, never a badge.
 * Tokens only: the surfaces follow the workspace in light and dark mode.
 */
const badge:React.CSSProperties={display:'inline-block',padding:'2px 12px',borderRadius:999,background:'var(--raised)',border:'1px solid var(--line)',color:'var(--danger-ink)',fontSize:14,fontWeight:700,marginInlineStart:8,verticalAlign:'middle'}
const quietBadge:React.CSSProperties={...badge,color:'var(--muted)',borderStyle:'dashed',fontWeight:600}
const okBadge:React.CSSProperties={...badge,color:'var(--evidence-ink)'}
const check:React.CSSProperties={display:'flex',alignItems:'flex-start',gap:12,cursor:'pointer'}
export default function Reports({author=false}:{author?:boolean}){
  const {id}=useParams(),{i18n}=useTranslation(),ar=i18n.language.startsWith('ar'),t=(a:string,e:string)=>ar?a:e,navigate=useNavigate()
  const list=useQuery({queryKey:['reports-list'],queryFn:()=>api.get<{runs:{id:number;title:string;mode:string;endReason:string;endedAt:string}[]}>('/api/v1/reports'),enabled:!id})
  const report=useQuery({queryKey:['report',id,author],queryFn:()=>api.get<HostReportRecord|AuthorReport>(`/api/v1/reports/${author?'authors':'runs'}/${id}`),enabled:!!id,refetchInterval:q=>{const d=q.state.data;return d&&'open'in d&&d.open?15000:false}})
  // Practice selection is the teacher's alone: nothing is preselected from flags or from non-completion.
  const [selected,setSelected]=useState<number[]>([]),[practice,setPractice]=useState<PracticeResponse|null>(null),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState('')
  const health=(code:string)=>({too_easy:t('إشارة: سهل جدًا','Review signal: too easy'),needs_review:t('يحتاج مراجعة','Needs review'),inactive_distractor:t('مشتت لم يُختر','Inactive distractor'),normal:t('ضمن النطاق المعتاد','Within the expected range'),insufficient_evidence:t('الدليل غير كافٍ','Insufficient evidence'),small_cells_suppressed:t('تفاصيل محجوبة لحماية الخصوصية','Details withheld for privacy')}[code]??code)
  const statusLabel=(code:string)=>({submitted:t('سُلّم','Submitted'),expired:t('أُغلق دون تسليم','Closed without submitting'),in_progress:t('قيد العمل','In progress'),not_started:t('لم يبدأ','Not started'),active:t('قيد العمل','In progress'),disconnected:t('غير متصل','Disconnected'),unanswered:t('لم يُجب','No answers'),participated:t('شارك','Participated')} as Record<string,string>)[code]??code
  const answers=(n:number)=>ar?(n===0?'بلا إجابات':n===1?'إجابة واحدة':n===2?'إجابتان':n<=10?`${n} إجابات`:`${n} إجابة`):(n===0?'no answers':n===1?'1 answer':`${n} answers`)
  const work=async(key:string,fn:()=>Promise<void>)=>{if(busy)return;setBusy(key);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:t('تعذّر تنفيذ الطلب','Request failed'))}finally{setBusy(null)}}
  const download=(runId:number,format:'xlsx'|'csv')=>work(format,async()=>{const {blob,filename}=await reports.download(runId,format);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)})
  const toggle=(questionId:number)=>{setPractice(null);setSelected(s=>s.includes(questionId)?s.filter(x=>x!==questionId):[...s,questionId])}
  const current=id?report:list
  /* Understanding: badge text carries the sample size; nothing is said from zero or one answer. */
  const understandingBadge=(q:ReportQuestion,open:boolean)=>q.evidence==='insufficient'
    ?<span style={quietBadge}>{t('دليل غير كافٍ','Insufficient evidence')} · {q.answered===0&&open?t('لا إجابات بعد','no answers yet'):answers(q.answered)}</span>
    :q.needsReview?<span style={badge}>{t('يحتاج مراجعة','Needs review')} · {t(`${q.incorrect} من ${q.answered} إجابات خاطئة`,`${q.incorrect} of ${q.answered} answers wrong`)}</span>:null
  const correctLine=(q:ReportQuestion,open:boolean)=>q.answered===0
    ?t(`نسبة الصحيح: غير متاحة — لا إجابات${open?' بعد':''}`,`Correct rate: unavailable — no answers${open?' yet':''}`)
    :q.evidence==='observed'?t(`صحيح: ${q.correct} من ${q.answered} إجابات (${q.correctPercent}%)`,`Correct: ${q.correct} of ${q.answered} answers (${q.correctPercent}%)`)
    :t(`صحيح: ${q.correct} من إجابة واحدة`,`Correct: ${q.correct} of 1 answer`)
  return <section className={`asas ${styles.workspace}`}><header className={styles.heading}><div><h1>{t(author?'دليل المؤلّف':'تقارير الحصص',author?'Author evidence':'Class reports')}</h1><p>{t('الإجابات دليل للمراجعة، وليست حكمًا على الطالب.','Answers support review. They are not a judgment of the learner.')}</p></div><BackLink to="/teacher/shelf">{t('العودة إلى الرف','Back to shelf')}</BackLink></header>
    {current.isPending?<LoadingState/>:current.error?<FailureState title={t('تعذّر فتح التقرير','Report unavailable')} body={current.error.message} actions={<Button onClick={()=>void current.refetch()}>{t('أعد المحاولة','Retry')}</Button>}/>:!id?<div className={styles.reportList}>{list.data?.runs.length?list.data.runs.map(r=><Link key={r.id} to={`/teacher/reports/runs/${r.id}`}><strong><bdi>{r.title}</bdi></strong><span>{new Date(r.endedAt).toLocaleString(ar?'ar':'en')} · {({live:t('حصة مباشرة','Live class'),homework:t('واجب','Homework'),study:t('دراسة ذاتية','Self-study'),self_study:t('دراسة ذاتية','Self-study')} as Record<string,string>)[r.mode]??r.mode}</span></Link>):<p>{t('أكمل حصة لتظهر نتائجها هنا.','Finish a class to see its report here.')}</p>}</div>:report.data&&'participants'in report.data?(()=>{const data=report.data as HostReportRecord,denominator=data.denominator==='attempts'?t('محاولة','attempts'):t('مشاركًا','participants'),pending=data.participation.inProgress+data.participation.notStarted;return <>
      <h2><bdi>{data.title}</bdi>{data.open&&<span style={okBadge}>{t('قيد التقدم','In progress')}</span>}</h2>
      {data.open&&<p className={styles.evidence}>{t('الواجب ما زال مفتوحًا؛ يعرض هذا التقرير ما وصل حتى الآن ويتحدّث تلقائيًا.','This assignment is still open; the report shows what has arrived so far and refreshes automatically.')}{data.deadline&&<> {t('الموعد النهائي','Deadline')}: <time dateTime={data.deadline}>{new Date(data.deadline).toLocaleString(ar?'ar':'en')}</time></>}
        <br/>{pending>0?t(`المشاركة: بانتظار ${pending} من ${data.participation.total} محاولات (${data.participation.notStarted} لم تبدأ). ذكّرهم أو انتظر التسليم — الأسئلة غير المجابة ليست دليلًا على الفهم.`,`Participation: waiting for ${pending} of ${data.participation.total} attempts (${data.participation.notStarted} not started). Remind them or wait for submissions — unanswered questions are not evidence about understanding.`):t(`المشاركة: سُلّمت جميع المحاولات (${data.participation.total}).`,`Participation: all ${data.participation.total} attempts are submitted.`)}</p>}
      {data.followUpOf&&<p className={styles.evidence}>{t(`هذا تدريب متابعة. ${data.followUpOf.sharedParticipants} من ${data.followUpOf.totalParticipants} مشاركين أدّوا أيضًا الحصة الأصلية.`,`This is a follow-up practice. ${data.followUpOf.sharedParticipants} of ${data.followUpOf.totalParticipants} participants also took the original run.`)} <Link to={`/teacher/reports/runs/${data.followUpOf.runId}`}>{t('افتح تقرير الحصة الأصلية','Open the original run report')}</Link></p>}
      {!data.open&&<p className={styles.evidence}>{data.pattern?t(`${data.pattern.count} إجابات تستحق مراجعة هذا النمط: ${data.pattern.reason}`,`${data.pattern.count} responses suggest reviewing this pattern: ${data.pattern.reason}`):data.closing.kind==='completed_review'?t('اكتملت الإجابات. اختر ما يحتاج إلى شرح أو ممارسة إضافية.','Responses are complete. Choose what needs explanation or further practice.'):t('لا نمط خطأ مشترك في الإجابات المرصودة. اختر بنفسك ما يحتاج إلى شرح أو تدريب.','No shared error pattern in the observed answers. Choose yourself what needs explanation or practice.')}
        {data.participation.incomplete>0&&<><br/>{t(`المشاركة: ${data.participation.incomplete} من ${data.participation.total} ${denominator} لم يُجيبوا عن كل الأسئلة — فجوة مشاركة، لا دليل على الفهم. ذكّرهم أو أعد التكليف، واختر أسئلة التدريب بنفسك أدناه.`,`Participation: ${data.participation.incomplete} of ${data.participation.total} ${denominator} did not answer every question — a participation gap, not evidence about understanding. Remind them or reassign, and choose practice questions yourself below.`)}</>}</p>}
      <div className={styles.actions} style={{padding:0}}>
        <Button loading={busy==='xlsx'} disabled={!!busy} onClick={()=>void download(data.runId,'xlsx')}>{t('تصدير XLSX','Export XLSX')}</Button>
        <Button loading={busy==='csv'} disabled={!!busy} onClick={()=>void download(data.runId,'csv')}>{t('تصدير CSV','Export CSV')}</Button>
        <small>{t(`المشاركون الذين انضموا: ${data.participantCount} · الأسئلة: ${data.questionCount}`,`Participants who joined: ${data.participantCount} · Questions: ${data.questionCount}`)}</small>
      </div>
      {error&&<p role="alert" style={{color:'var(--danger-ink)'}}>{error}</p>}
      <div className={styles.tableWrap}><table><thead><tr><th>{t('المشارك','Participant')}</th><th>{t('أجاب','Answered')}</th><th>{t('صحيح','Correct')}</th><th>{t('غير صحيح','Incorrect')}</th><th>{data.open?t('لم يُجب بعد','Not yet answered'):t('بلا إجابة','Unanswered')}</th>{data.gameMode&&data.gameMode!=='quiz'&&<th>{t('نقاط اللعبة','Game points')}</th>}</tr></thead><tbody>{data.participants.map(p=><tr key={p.id}><th><bdi>{p.name}</bdi><small style={{display:'block'}}>{statusLabel(p.status)}{p.submittedAt&&<> · <time dateTime={p.submittedAt}>{new Date(p.submittedAt).toLocaleString(ar?'ar':'en')}</time></>}</small></th><td>{t(`${p.answered} من ${data.questionCount}`,`${p.answered} of ${data.questionCount}`)}</td><td>{p.correctCount}</td><td>{p.incorrect}</td><td>{p.unanswered}{p.remedialAnswered>0&&<small> · {t(`تحقق إضافي: ${p.remedialCorrect}/${p.remedialAnswered}`,`Verification: ${p.remedialCorrect}/${p.remedialAnswered}`)}</small>}</td>{data.gameMode&&data.gameMode!=='quiz'&&<td>{p.gamePoints??0}</td>}</tr>)}</tbody></table></div>
      <p><small>{t('«يحتاج مراجعة» قاعدة تقريبية من هذه الحصة فقط: إجابتان على الأقل وأقل من نصفها صحيح. الإجابة الواحدة أو عدمها دليل غير كافٍ. من لم يُجب مشاركةٌ تُعرض على حِدة — ليست دليلًا على الفهم ولا حكمًا على أحد.','"Needs review" is a heuristic from this run only: at least two answers were recorded and fewer than half were correct. One answer or none is insufficient evidence. Who has not answered is participation, shown separately — never evidence about understanding, and never a judgment of anyone.')}</small></p>
      {data.questions.map(q=><section key={q.index} className={styles.questionReport}>
        <label style={check}><input type="checkbox" checked={selected.includes(q.questionId)} onChange={()=>toggle(q.questionId)} aria-label={t(`اختر السؤال ${q.index+1} للتدريب`,`Select question ${q.index+1} for practice`)} style={{width:22,height:22,marginTop:6,flexShrink:0}}/><h3 style={{margin:0}}>{q.index+1}. <bdi><FormattedText text={q.prompt}/></bdi>{q.remedial&&` · ${t('سؤال تحقق','Verification question')}`}{understandingBadge(q,data.open)}</h3></label>
        {q.correctLabel&&!q.distribution.some(d=>d.isCorrect)&&<p><strong>✓ <bdi>{q.correctLabel}</bdi></strong>: <strong>0</strong></p>}
        {q.distribution.map(d=>{const label=d.label&&d.label!==d.key?d.label:({true:t('صح','True'),false:t('خطأ','False'),correct:t('إجابة صحيحة','Correct'),incorrect:t('إجابة غير صحيحة','Incorrect')} as Record<string,string>)[d.key]??d.label??d.key;return <p key={d.key}>{d.isCorrect?<strong>✓ <bdi>{label}</bdi></strong>:<bdi>{label}</bdi>}: <strong>{d.count}</strong></p>})}
        <p style={{display:'block'}}>{correctLine(q,data.open)}</p>
        <p style={{display:'block',color:'var(--muted)'}}>{data.open&&t(`لم يُجب بعد: ${q.participation.notYetAnswered} من ${data.participantCount} ${denominator}`,`Not yet answered: ${q.participation.notYetAnswered} of ${data.participantCount} ${denominator}`)}{data.open&&q.participation.unanswered>0&&' · '}{(!data.open||q.participation.unanswered>0)&&t(`بلا إجابة: ${q.participation.unanswered} من ${data.participantCount} ${denominator}`,`No answer: ${q.participation.unanswered} of ${data.participantCount} ${denominator}`)}</p>
        {q.explanation&&<p style={{display:'block',color:'var(--muted)'}}>{t('الشرح','Explanation')}: <bdi>{q.explanation}</bdi></p>}
      </section>)}
      <div className={styles.actions} style={{padding:0,borderTop:'1px solid var(--line)'}}>
        <Button variant="primary" loading={busy==='practice'} disabled={!!busy||selected.length===0} onClick={()=>void work('practice',async()=>{setPractice(await reports.practice(data.runId,{questionIds:selected,language:ar?'ar':'en'}))})}>{t('أنشئ تدريبًا على هذه النقاط','Create practice for these points')}</Button>
        <small>{selected.length?t(`${selected.length} أسئلة مختارة`,`${selected.length} selected`):t('اختر سؤالًا واحدًا على الأقل من الأسئلة أعلاه. لا يُختار شيء تلقائيًا.','Select at least one question above. Nothing is selected for you.')}</small>
      </div>
      {practice&&<section className={styles.evidence} aria-live="polite" style={{fontSize:'inherit'}}>
        <h3 style={{marginTop:0}}><bdi>{practice.title}</bdi></h3>
        <p>{t('أُنشئ نشاط تدريب خاص مرتبط بهذه الحصة. راجع التكلفة قبل بدء التوليد:','A private practice activity linked to this run was created. Review the cost before generating:')}</p>
        <ul style={{lineHeight:1.9,paddingInlineStart:24}}>
          <li>{t('التقدير','Estimate')}: <strong dir="ltr">{usd(practice.quote.estimateMillicents)}</strong></li>
          <li>{t('الحد الأقصى','Maximum charge')}: <strong dir="ltr">{usd(practice.quote.maxAuthorizedMillicents)}</strong></li>
          <li>{t('الرصيد القابل للاستخدام','Usable credit')}: <strong dir="ltr">{usd(practice.quote.usableMillicents)}</strong></li>
          <li>{t(`${practice.draft.count} أسئلة من ${practice.draft.segments.length} مقاطع من مصدرك`,`${practice.draft.count} questions from ${practice.draft.segments.length} segments of your source`)}</li>
        </ul>
        <p><small>{t('راجع الأسئلة قبل إضافتها. ستظهر التكلفة المحدّثة في المحرّر قبل الإنشاء.','Review the questions before adding them. The editor shows an updated cost before creation.')}</small></p>
        {!practice.quote.grant.eligible&&practice.quote.grant.reason==='email_not_verified'&&<p>{t(`أكّد بريدك الإلكتروني لتستلم رصيد التجربة (${usd(practice.quote.grant.trialMillicents)}).`,`Verify your email to receive the trial credit (${usd(practice.quote.grant.trialMillicents)}).`)}</p>}
        {!practice.quote.generationAvailable&&<p>{t('خدمة التوليد غير مهيأة في هذه البيئة. يمكنك كتابة أسئلة التدريب يدويًا.','Generation is not configured here. You can write the practice questions manually.')}</p>}
        {!practice.quote.pricingAvailable&&<p>{t('لم تُعتمد أسعار التوليد في هذه البيئة بعد.','Generation pricing is not approved for this environment.')}</p>}
        {practice.quote.pricingAvailable&&practice.quote.generationAvailable&&!practice.quote.affordable&&<p role="status"><strong>{t('رصيد التوليد غير كافٍ.','Not enough generation credit.')}</strong> {t('الأنشطة المحفوظة والحصص والواجبات والتقارير تعمل كما هي، ويمكنك تعديل التدريب يدويًا.','Saved activities, sessions, assignments and reports keep working, and you can edit the practice manually.')}</p>}
        {practice.reusable.length>0&&<div><p><strong>{t('بديل بلا تكلفة','A no-cost alternative')}</strong>: {t('لديك أسئلة معتمدة مرتبطة بهذه النقاط:','you already linked approved questions to these points:')}</p><ul style={{paddingInlineStart:24}}>{practice.reusable.map(r=><li key={r.targetQuestionId}><bdi>{r.prompt}</bdi></li>)}</ul></div>}
        <div className={styles.actions} style={{padding:0}}>
          {practice.quote.affordable&&practice.quote.generationAvailable&&<Button variant="primary" onClick={()=>navigate(`/teacher/activities/${practice.practiceActivityId}?generate=1&draft=${encodeDraft(practice.draft)}`)}>{t('تابع إلى المحرر وابدأ التوليد ضمن هذا الحد','Continue to the editor and generate within this cap')}</Button>}
          <Button onClick={()=>navigate(`/teacher/activities/${practice.practiceActivityId}`)}>{t('افتح التدريب دون توليد','Open the practice without generating')}</Button>
          <Button variant="quiet" onClick={()=>setPractice(null)}>{t('إغلاق','Close')}</Button>
        </div>
      </section>}
      {data.followUps.length>0&&<section className={styles.questionReport}><h3>{t('تدريبات المتابعة من هذه الحصة','Follow-up practices from this run')}</h3>{data.followUps.map(f=><p key={f.id} style={{display:'block'}}><Link to={`/teacher/activities/${f.practiceActivityId}`}><bdi>{f.title}</bdi></Link> · {f.approved?t('معتمد','Approved'):t('مسودة','Draft')} · {t(`${f.runs} تشغيلات`,`${f.runs} runs`)} · <time dateTime={f.createdAt}>{new Date(f.createdAt).toLocaleDateString(ar?'ar':'en')}</time>{f.generationJobId&&<> · {t('توليد مسجّل','Generation recorded')}</>}</p>)}</section>}
    </>})():report.data&&'status'in report.data?<><h2>{report.data.title}</h2><p>{report.data.status==='insufficient_students'?t('لا توجد بيانات كافية لعرض أرقام تحمي خصوصية الطلاب.','There is not enough evidence to show privacy-preserving totals.'):report.data.status==='coarse_only'?t(`إجمالي المشاركات: ${report.data.totalParticipation}. يظهر التفصيل بعد ثلاثة صفوف.`,`Total participations: ${report.data.totalParticipation}. Details need three distinct classes.`):t(`${report.data.totalParticipation} مشاركة في ${report.data.classCount} صفوف`,`${report.data.totalParticipation} participations across ${report.data.classCount} classes`)}</p>{report.data.status==='aggregate'&&<p>{t(`${report.data.reuseCount} استخدامات مؤهلة بواسطة ${report.data.teacherCount} معلّمين`,`${report.data.reuseCount} eligible uses by ${report.data.teacherCount} teachers`)}</p>}{report.data.modifications?.map(m=><p key={m.field}>{t('عدّل معلّمون هذا الحقل','Teachers edited this field')}: {({prompt:t('السؤال','Question'),payload:t('الإجابات','Answers'),timeLimitS:t('الوقت','Time'),mediaKey:t('الصورة','Image')} as Record<string,string>)[m.field]} · {m.editors}</p>)}<Link to={`/teacher/activities/${id}`}>{t('راجع النشاط وعدّله','Review and edit activity')}</Link>{report.data.questions.map(q=><p key={`${q.versionId}:${q.questionId}`}>{t('السؤال','Question')} {q.questionId} · {t("النسخة","Version")} {q.versionId}: {health(q.status)}{q.answered!==undefined?` · ${q.correct}/${q.answered}`:''}</p>)}</>:null}
  </section>
}
