import {useParams,Link} from 'react-router-dom'
import {useQuery} from '@tanstack/react-query'
import {useTranslation} from 'react-i18next'
import {api} from '@/lib/api'
import {Button,LoadingState,FailureState} from '@/design'
import styles from '../shelf/Workspace.module.css'
interface HostReport {runId:number;title:string;endReason:string;mode:string;closing:{kind:string};questionCount:number;participants:{id:string;name:string;score:number;correctCount:number;answered:number;connected:boolean;status:string;remedialAnswered:number;remedialCorrect:number;originalCorrect:number}[];questions:{index:number;prompt:string;remedial:boolean;distribution:{key:string;label?:string;count:number}[]}[];pattern:{count:number;reason:string}|null}
interface AuthorReport{title:string;status:string;totalParticipation?:number;classCount?:number;reuseCount?:number;teacherCount?:number;modifications?:{field:string;editors:number}[];questions:{questionId:number;versionId:number;status:string;answered?:number;correct?:number}[]}
export default function Reports({author=false}:{author?:boolean}){
  const {id}=useParams(),{i18n}=useTranslation(),ar=i18n.language.startsWith('ar'),t=(a:string,e:string)=>ar?a:e
  const list=useQuery({queryKey:['reports-list'],queryFn:()=>api.get<{runs:{id:number;title:string;mode:string;endReason:string;endedAt:string}[]}>('/api/v1/reports'),enabled:!id})
  const report=useQuery({queryKey:['report',id,author],queryFn:()=>api.get<HostReport|AuthorReport>(`/api/v1/reports/${author?'authors':'runs'}/${id}`),enabled:!!id})
  const health=(code:string)=>({too_easy:t('إشارة: سهل جدًا','Review signal: too easy'),needs_review:t('يحتاج مراجعة','Needs review'),inactive_distractor:t('مشتت لم يُختر','Inactive distractor'),normal:t('ضمن النطاق المعتاد','Within the expected range'),insufficient_evidence:t('الدليل غير كافٍ','Insufficient evidence'),small_cells_suppressed:t('تفاصيل محجوبة لحماية الخصوصية','Details withheld for privacy')}[code]??code)
  const current=id?report:list
  return <main className={`asas ${styles.workspace}`}><header className={styles.heading}><div><h1>{t(author?'دليل المؤلّف':'تقارير الحصص',author?'Author evidence':'Class reports')}</h1><p>{t('الإجابات دليل للمراجعة، وليست حكمًا على الطالب.','Answers support review. They are not a judgment of the learner.')}</p></div><Link to="/teacher/shelf">{t('العودة إلى الرف','Back to shelf')}</Link></header>
    {current.isPending?<LoadingState/>:current.error?<FailureState title={t('تعذّر فتح التقرير','Report unavailable')} body={current.error.message} actions={<Button onClick={()=>void current.refetch()}>{t('أعد المحاولة','Retry')}</Button>}/>:!id?<div className={styles.reportList}>{list.data?.runs.length?list.data.runs.map(r=><Link key={r.id} to={`/teacher/reports/runs/${r.id}`}><strong>{r.title}</strong><span>{new Date(r.endedAt).toLocaleString(ar?'ar':'en')} · {({live:t('حصة مباشرة','Live class'),homework:t('واجب','Homework'),self_study:t('دراسة ذاتية','Self-study')} as Record<string,string>)[r.mode]??r.mode}</span></Link>):<p>{t('أكمل حصة لتظهر نتائجها هنا.','Finish a class to see its report here.')}</p>}</div>:report.data&&'participants'in report.data?<>
      <h2>{report.data.title}</h2><p className={styles.evidence}>{report.data.pattern?t(`${report.data.pattern.count} إجابات تستحق مراجعة هذا النمط: ${report.data.pattern.reason}`,`${report.data.pattern.count} responses suggest reviewing this pattern: ${report.data.pattern.reason}`):report.data.closing.kind==='completed_review'?t('اكتملت الإجابات. اختر ما يحتاج إلى شرح أو ممارسة إضافية.','Responses are complete. Choose what needs explanation or further practice.'):t('راجع الأسئلة غير المجابة مع الصف قبل الانتقال.','Review unanswered questions with the class before moving on.')}</p>
      <div className={styles.tableWrap}><table><thead><tr><th>{t('المشارك','Participant')}</th><th>{t('الدليل','Evidence')}</th><th>{t('بلا إجابة','Unanswered')}</th></tr></thead><tbody>{report.data.participants.map(p=><tr key={p.id}><th>{p.name}<small style={{display:'block'}}>{({submitted:t('سُلّم','Submitted'),expired:t('انتهى الموعد','Deadline passed'),active:t('قيد العمل','In progress'),disconnected:t('غير متصل','Disconnected'),unanswered:t('لم يُجب','No answers'),participated:t('شارك','Participated')} as Record<string,string>)[p.status]}</small></th><td>{t(`أجاب عن ${p.correctCount} من ${p.answered} إجابات بشكل صحيح`,`${p.correctCount} of ${p.answered} answers correct`)}</td><td>{Math.max(0,(report.data as HostReport).questionCount-p.answered)}{p.remedialAnswered>0&&<small> · {t(`تحقق إضافي: ${p.remedialCorrect}/${p.remedialAnswered}`,`Verification: ${p.remedialCorrect}/${p.remedialAnswered}`)}</small>}</td></tr>)}</tbody></table></div>
      {report.data.questions.map(q=><section key={q.index} className={styles.questionReport}><h3>{q.index+1}. {q.prompt}{q.remedial&&` · ${t("سؤال تحقق","Verification question")}`}</h3>{q.distribution.map(d=><p key={d.key}>{d.label&&d.label!==d.key?d.label:({true:t('صح','True'),false:t('خطأ','False'),correct:t('إجابة صحيحة','Correct'),incorrect:t('إجابة غير صحيحة','Incorrect')} as Record<string,string>)[d.key]??d.label??d.key}: <strong>{d.count}</strong></p>)}</section>)}
    </>:report.data&&'status'in report.data?<><h2>{report.data.title}</h2><p>{report.data.status==='insufficient_students'?t('لا توجد بيانات كافية لعرض أرقام تحمي خصوصية الطلاب.','There is not enough evidence to show privacy-preserving totals.'):report.data.status==='coarse_only'?t(`إجمالي المشاركات: ${report.data.totalParticipation}. يظهر التفصيل بعد ثلاثة صفوف.`,`Total participations: ${report.data.totalParticipation}. Details need three distinct classes.`):t(`${report.data.totalParticipation} مشاركة في ${report.data.classCount} صفوف`,`${report.data.totalParticipation} participations across ${report.data.classCount} classes`)}</p>{report.data.status==='aggregate'&&<p>{t(`${report.data.reuseCount} استخدامات مؤهلة بواسطة ${report.data.teacherCount} معلّمين`,`${report.data.reuseCount} eligible uses by ${report.data.teacherCount} teachers`)}</p>}{report.data.modifications?.map(m=><p key={m.field}>{t('عدّل معلّمون هذا الحقل','Teachers edited this field')}: {({prompt:t('السؤال','Question'),payload:t('الإجابات','Answers'),timeLimitS:t('الوقت','Time'),mediaKey:t('الصورة','Image')} as Record<string,string>)[m.field]} · {m.editors}</p>)}<Link to={`/teacher/activities/${id}`}>{t('راجع النشاط وعدّله','Review and edit activity')}</Link>{report.data.questions.map(q=><p key={`${q.versionId}:${q.questionId}`}>{t('السؤال','Question')} {q.questionId} · {t("النسخة","Version")} {q.versionId}: {health(q.status)}{q.answered!==undefined?` · ${q.correct}/${q.answered}`:''}</p>)}</>:null}
  </main>
}
